/**
 * Provisioning generator — Statamic.
 *
 * Turns the canonical slot definitions + design tokens into the artifacts a
 * Statamic site needs: a context-slot fieldset (YAML), the block render
 * template (Antlers) and the tokens stylesheet. The addon's `php please mc:sync`
 * fetches these via /api/v1/provision/manifest and writes them to disk, so the
 * CMS stays in lockstep with the platform.
 */

import fs from "node:fs";
import path from "node:path";
import { SLOT_DEFINITIONS, DEFINITIONS_VERSION, type SlotDef, type SlotFieldDef } from "@/provisioning/definitions";
import { generateTokensCss, type TokenOverrides } from "@/provisioning/tokens-css";

export interface ProvisionArtifact {
  /** Path relative to the Statamic project root. */
  path: string;
  contents: string;
}

export interface ProvisionManifest {
  cms: "statamic";
  version: string;
  artifacts: ProvisionArtifact[];
}

const STATAMIC_FIELD_TYPE: Record<SlotFieldDef["type"], string> = {
  text: "text",
  textarea: "textarea",
  url: "text",
  media: "assets",
  select: "select",
};

/** Build the context-slot fieldset YAML from the canonical field definitions. */
function buildFieldsetYaml(): string {
  // Union of fields across slots, de-duplicated by handle (a single fieldset
  // drives every slot; slot_type selects which fields are rendered).
  const seen = new Set<string>();
  const fields: SlotFieldDef[] = [];
  for (const slot of SLOT_DEFINITIONS) {
    for (const f of slot.fields) {
      if (!seen.has(f.handle)) {
        seen.add(f.handle);
        fields.push(f);
      }
    }
  }

  const slotOptions = SLOT_DEFINITIONS.map((s) => `        ${s.id}: ${s.label}`).join("\n");

  const fieldYaml = (f: SlotFieldDef): string => {
    const lines = [
      `  -`,
      `    handle: ${f.handle}`,
      `    field:`,
      `      type: ${STATAMIC_FIELD_TYPE[f.type]}`,
      `      display: '${f.label}'`,
    ];
    if (f.type === "select" && f.options) {
      lines.push(`      options:`);
      for (const [k, v] of Object.entries(f.options)) lines.push(`        ${k}: '${v}'`);
    }
    if (f.type === "media") {
      lines.push(`      container: assets`, `      max_files: 1`);
    }
    if (f.half) lines.push(`      width: 50`);
    if (f.instructions) lines.push(`      instructions: '${f.instructions}'`);
    return lines.join("\n");
  };

  return `title: 'Mister Chameleon — Context Slot'
# Generated by the Mister Chameleon platform (v${DEFINITIONS_VERSION}). Do not edit by hand.
fields:
  -
    handle: slot_type
    field:
      type: select
      display: 'Slot type'
      instructions: 'Which personalisation slot this block fills.'
      options:
${slotOptions}
      default: hero
      width: 50
  -
    handle: variant_key
    field:
      type: text
      display: 'Default variant key'
      instructions: 'CMS-authored fallback served to bots and when the platform is unavailable.'
      width: 50
${fields.map(fieldYaml).join("\n")}
`;
}

/** Build the Antlers render template — one {{ if }} block per slot. */
function buildBlockTemplate(): string {
  const renderField = (slot: SlotDef): string => {
    const parts: string[] = [];
    parts.push(`{{ if slot_type == '${slot.id}' }}`);
    parts.push(`    <section class="mc-slot mc-slot--${slot.id}">`);
    for (const f of slot.fields) {
      if (f.handle === "tag") {
        parts.push(`        {{ if content:tag }}<p class="mc-eyebrow">{{ content:tag }}</p>{{ /if }}`);
      } else if (f.handle === "heading") {
        const tag = slot.id === "hero" ? "h1" : "h2";
        parts.push(`        {{ if content:heading }}<${tag} class="mc-heading">{{ content:heading }}</${tag}>{{ /if }}`);
      } else if (f.handle === "body" || f.handle === "message") {
        parts.push(`        {{ if content:${f.handle} }}<p class="mc-body">{{ content:${f.handle} }}</p>{{ /if }}`);
      } else if (f.handle === "media") {
        parts.push(`        {{ if content:media }}<img class="mc-media" src="{{ content:media }}" alt="{{ content:heading }}">{{ /if }}`);
      }
    }
    const hasCta = slot.fields.some((f) => f.handle === "cta_label");
    if (hasCta) {
      parts.push(
        `        {{ if content:cta_label }}<a class="mc-btn mc-btn--primary" href="{{ content:cta_url ?? '#' }}">{{ content:cta_label }}</a>{{ /if }}`,
      );
    }
    parts.push(`    </section>`);
    parts.push(`{{ /if }}`);
    return parts.join("\n");
  };

  return `{{#
    Mister Chameleon — context-slot renderer.
    Generated by the platform (v${DEFINITIONS_VERSION}). Do not edit by hand:
    run \`php please mc:sync\` to refresh. Receives: slot_type, variant_key, content.
#}}

${SLOT_DEFINITIONS.map(renderField).join("\n\n")}
`;
}

/**
 * Content-block fieldsets (the `mrc_*` family) live as canonical YAML files in
 * provisioning/statamic/fieldsets/. They are shipped to the tenant verbatim —
 * the platform owns them, `mc:sync` writes them into resources/fieldsets/, and
 * the site's blueprints import them. Editing the YAML here and re-syncing rolls
 * the change out everywhere, exactly like the context-slot artifacts above.
 *
 * The directory is bundled into the serverless function via
 * `outputFileTracingIncludes` in next.config.mjs. Read lazily + cached so the
 * disk hit happens at most once per warm instance.
 */
const CONTENT_FIELDSETS_DIR = path.join(process.cwd(), "provisioning", "statamic", "fieldsets");
let _contentFieldsetCache: ProvisionArtifact[] | null = null;

function readContentFieldsets(): ProvisionArtifact[] {
  if (_contentFieldsetCache) return _contentFieldsetCache;
  let files: string[] = [];
  try {
    files = fs.readdirSync(CONTENT_FIELDSETS_DIR).filter((f) => f.endsWith(".yaml"));
  } catch {
    // Directory missing (e.g. tracing not applied) — degrade gracefully to the
    // context-slot artifacts rather than failing the whole manifest.
    return [];
  }
  files.sort();
  _contentFieldsetCache = files.map((name) => ({
    path: `resources/fieldsets/${name}`,
    contents: fs.readFileSync(path.join(CONTENT_FIELDSETS_DIR, name), "utf8"),
  }));
  return _contentFieldsetCache;
}

/**
 * Build the per-block "Design token set" fieldset. When the tenant has named
 * block token sets, emit a SELECT dropdown listing them by name (so authors pick
 * instead of typing a key); otherwise fall back to a free-text field.
 */
export function buildBlockDesignFieldset(
  sets: ReadonlyArray<{ key: string; name?: string }> = [],
): string {
  const header = `title: 'Mister Chameleon — Block Design'
# Managed by the Mister Chameleon platform. Do not edit by hand — run
# \`php please mc:sync\` to refresh.
#
# Imported by every content-block set in mc_page_blocks so any block can override
# the site-wide design tokens for itself.
fields:
  -
    handle: mc_token_set
    field:`;

  const valid = sets.filter((s) => s.key && s.key.trim());
  if (valid.length === 0) {
    return `${header}
      type: text
      display: 'Design token set'
      instructions: "Optional. Enter the key of a design token set (defined in Admin → Design → Blocks) to restyle just this block. Leave empty to inherit the site-wide design tokens."
      width: 100
`;
  }

  const esc = (s: string) => s.replace(/'/g, "''");
  const options = valid
    .map((s) => `        ${s.key.trim()}: '${esc(s.name?.trim() || s.key.trim())}'`)
    .join("\n");

  return `${header}
      type: select
      display: 'Design token set'
      instructions: "Optional. Pick a design token set to restyle just this block. Leave empty to inherit the site-wide design tokens."
      clearable: true
      width: 100
      options:
${options}
`;
}

/** Produce the full Statamic provisioning manifest for a tenant. */
export function generateStatamicManifest(
  tokenOverrides: TokenOverrides = {},
  blockTokenSets: ReadonlyArray<{ key: string; name?: string }> = [],
): ProvisionManifest {
  // Ship all content fieldsets verbatim EXCEPT mrc_block_design — that one is
  // generated per-tenant so its dropdown lists the tenant's own token sets.
  const contentFieldsets = readContentFieldsets().filter(
    (a) => !a.path.endsWith("/mrc_block_design.yaml"),
  );

  return {
    cms: "statamic",
    version: DEFINITIONS_VERSION,
    artifacts: [
      {
        path: "resources/fieldsets/mc_context_slot.yaml",
        contents: buildFieldsetYaml(),
      },
      {
        path: "resources/views/vendor/mister-chameleon/blocks/context_slot.antlers.html",
        contents: buildBlockTemplate(),
      },
      {
        path: "resources/css/mister-chameleon-tokens.css",
        contents: generateTokensCss(tokenOverrides),
      },
      // Per-tenant: dropdown of the tenant's own named block token sets.
      {
        path: "resources/fieldsets/mrc_block_design.yaml",
        contents: buildBlockDesignFieldset(blockTokenSets),
      },
      // Content-block fieldsets (mrc_*) — shipped verbatim from the platform.
      ...contentFieldsets,
    ],
  };
}
