/**
 * Provisioning generator — Statamic.
 *
 * Turns the canonical slot definitions + design tokens into the artifacts a
 * Statamic site needs: a context-slot fieldset (YAML), the block render
 * template (Antlers) and the tokens stylesheet. The addon's `php please mc:sync`
 * fetches these via /api/v1/provision/manifest and writes them to disk, so the
 * CMS stays in lockstep with the platform.
 */

import { SLOT_DEFINITIONS, DEFINITIONS_VERSION, type SlotDef, type SlotFieldDef } from "@/provisioning/definitions";
import { generateTokensCss, type TokenOverrides } from "@/provisioning/tokens-css";

export interface ProvisionArtifact {
  /** Path relative to the Statamic project root. */
  path: string;
  contents: string;
}

export interface ProvisionManifest {
  cms: "statamic";
  version: string;
  artifacts: ProvisionArtifact[];
}

const STATAMIC_FIELD_TYPE: Record<SlotFieldDef["type"], string> = {
  text: "text",
  textarea: "textarea",
  url: "text",
  media: "assets",
  select: "select",
};

/** Build the context-slot fieldset YAML from the canonical field definitions. */
function buildFieldsetYaml(): string {
  // Union of fields across slots, de-duplicated by handle (a single fieldset
  // drives every slot; slot_type selects which fields are rendered).
  const seen = new Set<string>();
  const fields: SlotFieldDef[] = [];
  for (const slot of SLOT_DEFINITIONS) {
    for (const f of slot.fields) {
      if (!seen.has(f.handle)) {
        seen.add(f.handle);
        fields.push(f);
      }
    }
  }

  const slotOptions = SLOT_DEFINITIONS.map((s) => `        ${s.id}: ${s.label}`).join("\n");

  const fieldYaml = (f: SlotFieldDef): string => {
    const lines = [
      `  -`,
      `    handle: ${f.handle}`,
      `    field:`,
      `      type: ${STATAMIC_FIELD_TYPE[f.type]}`,
      `      display: '${f.label}'`,
    ];
    if (f.type === "select" && f.options) {
      lines.push(`      options:`);
      for (const [k, v] of Object.entries(f.options)) lines.push(`        ${k}: '${v}'`);
    }
    if (f.type === "media") {
      lines.push(`      container: assets`, `      max_files: 1`);
    }
    if (f.half) lines.push(`      width: 50`);
    if (f.instructions) lines.push(`      instructions: '${f.instructions}'`);
    return lines.join("\n");
  };

  return `title: 'Mister Chameleon — Context Slot'
# Generated by the Mister Chameleon platform (v${DEFINITIONS_VERSION}). Do not edit by hand.
fields:
  -
    handle: slot_type
    field:
      type: select
      display: 'Slot type'
      instructions: 'Which personalisation slot this block fills.'
      options:
${slotOptions}
      default: hero
      width: 50
  -
    handle: variant_key
    field:
      type: text
      display: 'Default variant key'
      instructions: 'CMS-authored fallback served to bots and when the platform is unavailable.'
      width: 50
${fields.map(fieldYaml).join("\n")}
`;
}

/** Build the Antlers render template — one {{ if }} block per slot. */
function buildBlockTemplate(): string {
  const renderField = (slot: SlotDef): string => {
    const parts: string[] = [];
    parts.push(`{{ if slot_type == '${slot.id}' }}`);
    parts.push(`    <section class="mc-slot mc-slot--${slot.id}">`);
    for (const f of slot.fields) {
      if (f.handle === "tag") {
        parts.push(`        {{ if content:tag }}<p class="mc-eyebrow">{{ content:tag }}</p>{{ /if }}`);
      } else if (f.handle === "heading") {
        const tag = slot.id === "hero" ? "h1" : "h2";
        parts.push(`        {{ if content:heading }}<${tag} class="mc-heading">{{ content:heading }}</${tag}>{{ /if }}`);
      } else if (f.handle === "body" || f.handle === "message") {
        parts.push(`        {{ if content:${f.handle} }}<p class="mc-body">{{ content:${f.handle} }}</p>{{ /if }}`);
      } else if (f.handle === "media") {
        parts.push(`        {{ if content:media }}<img class="mc-media" src="{{ content:media }}" alt="{{ content:heading }}">{{ /if }}`);
      }
    }
    const hasCta = slot.fields.some((f) => f.handle === "cta_label");
    if (hasCta) {
      parts.push(
        `        {{ if content:cta_label }}<a class="mc-btn mc-btn--primary" href="{{ content:cta_url ?? '#' }}">{{ content:cta_label }}</a>{{ /if }}`,
      );
    }
    parts.push(`    </section>`);
    parts.push(`{{ /if }}`);
    return parts.join("\n");
  };

  return `{{#
    Mister Chameleon — context-slot renderer.
    Generated by the platform (v${DEFINITIONS_VERSION}). Do not edit by hand:
    run \`php please mc:sync\` to refresh. Receives: slot_type, variant_key, content.
#}}

${SLOT_DEFINITIONS.map(renderField).join("\n\n")}
`;
}

/** Produce the full Statamic provisioning manifest for a tenant. */
export function generateStatamicManifest(tokenOverrides: TokenOverrides = {}): ProvisionManifest {
  return {
    cms: "statamic",
    version: DEFINITIONS_VERSION,
    artifacts: [
      {
        path: "resources/fieldsets/mc_context_slot.yaml",
        contents: buildFieldsetYaml(),
      },
      {
        path: "resources/views/vendor/mister-chameleon/blocks/context_slot.antlers.html",
        contents: buildBlockTemplate(),
      },
      {
        path: "resources/css/mister-chameleon-tokens.css",
        contents: generateTokensCss(tokenOverrides),
      },
    ],
  };
}
