/**
 * Next.js Middleware — Session Cookie Initialisation
 *
 * Runs at the Edge before any route handler or Server Component.
 * Responsibilities:
 *
 *   1. Read mc_session_id and mc_seen from the incoming Cookie header.
 *   2. Generate a new session UUID if mc_session_id is absent.
 *   3. Write any new cookies onto the response (browser persists them).
 *   4. Forward mc_session_id in the request headers so Server Components
 *      can read the session ID without a second cookie parse.
 *
 * ─── Cookie forwarding strategy ───────────────────────────────────────────────
 *
 *   mc_session_id is injected into the forwarded request headers so the
 *   homepage Server Component always sees a populated session ID, even on
 *   the very first request before the browser receives the Set-Cookie response.
 *
 *   mc_seen is deliberately NOT injected into the forwarded request headers
 *   on a first visit — its absence is what signals "new" to detectVisitorContext().
 *   On subsequent visits the browser sends mc_seen itself, so the forwarded
 *   Cookie header naturally includes it and visitType resolves to "returning".
 *
 * ─── Performance ──────────────────────────────────────────────────────────────
 *
 *   This middleware performs zero I/O — it only reads/writes cookies and
 *   header strings. The Edge runtime handles it in microseconds.
 *
 * ─── Matcher ──────────────────────────────────────────────────────────────────
 *
 *   Runs on all site pages. Excluded paths (see `config.matcher`):
 *     - Next.js internals (_next/*)
 *     - API routes (api/*)
 *     - Static files (anything with a file extension)
 *
 * ─── Dev tenant override via ?tenant= ────────────────────────────────────────
 *
 *   In development, if a `?tenant=<tenantId>` query parameter is present,
 *   the middleware injects it as an `x-tenant-override` request header so
 *   Server Components can resolve the correct tenant without carrying the
 *   query param through every internal link.
 *
 *   The `x-tenant-override` header is read by getActiveTenant() — it takes
 *   priority over even the mc_dev_tenant cookie so that a single ?tenant= URL
 *   can temporarily override any persistent cookie setting.
 *
 *   This forwarding is dev-only: the `if` is on process.env.NODE_ENV which is
 *   a compile-time constant — the branch is dead-code-eliminated in production.
 *
 * ─── Dependency ───────────────────────────────────────────────────────────────
 *
 *   resolveSession() is importable from the Edge runtime because it uses
 *   only the Web Crypto API (crypto.randomUUID) and pure string parsing —
 *   no Node.js built-ins, no server-only guards.
 */

import { type NextRequest, NextResponse } from "next/server";
import { resolveSession, SESSION_COOKIE } from "@/data/session";

export function middleware(request: NextRequest): NextResponse {
  const cookieHeader = request.headers.get("cookie");
  const session = resolveSession(cookieHeader);

  // Build modified request headers so Server Components see mc_session_id.
  // We clone the incoming headers and either leave mc_session_id as-is
  // (returning visitor — already in the Cookie header) or append it
  // (new visitor — just generated by resolveSession).
  const requestHeaders = new Headers(request.headers);

  if (session.isNewSession) {
    // Append the freshly-generated session ID to the forwarded Cookie header.
    // This ensures the homepage Server Component can read it via headers().get("cookie")
    // on the same request that generates it — before the browser acknowledges
    // the Set-Cookie response.
    const existing = requestHeaders.get("cookie") ?? "";
    const separator = existing.length > 0 ? "; " : "";
    requestHeaders.set(
      "cookie",
      `${existing}${separator}${SESSION_COOKIE}=${session.sessionId}`,
    );
  }

  // ── Dev tenant override ─────────────────────────────────────────────────────
  // In development, forward ?tenant=<id> as the x-tenant-override header so
  // Server Components resolve the correct tenant from a single URL param
  // rather than requiring a persistent cookie.  Dead-code-eliminated in prod.
  if (process.env.NODE_ENV === "development") {
    const tenantParam = request.nextUrl.searchParams.get("tenant")?.trim();
    if (tenantParam) {
      requestHeaders.set("x-tenant-override", tenantParam);
    }
  }

  // Pass the (possibly modified) request headers to the downstream handler.
  const response = NextResponse.next({
    request: { headers: requestHeaders },
  });

  // Write any new cookies onto the response so the browser persists them.
  // On first visit this sets both mc_session_id and mc_seen.
  // On a returning visit with both cookies present, cookiesToSet is empty
  // and this loop is a no-op.
  for (const spec of session.cookiesToSet) {
    response.cookies.set(spec.name, spec.value, {
      maxAge: spec.maxAge,
      path: spec.path,
      httpOnly: spec.httpOnly,
      sameSite: spec.sameSite,
      secure: spec.secure,
    });
  }

  return response;
}

// ── Route matcher ─────────────────────────────────────────────────────────────

export const config = {
  matcher: [
    /*
     * Match all request paths EXCEPT:
     *   - _next/static   (static assets bundled by Next.js)
     *   - _next/image    (Next.js Image Optimisation API)
     *   - api/*          (route handlers — they manage their own auth)
     *   - favicon.ico    (browser default icon request)
     *   - Any path ending in a file extension (e.g. .png, .svg, .js, .css)
     *     These are public assets served from /public — no session needed.
     *
     * The negative lookahead `(?!...)` excludes those paths.
     * The trailing `(.*)` matches the rest of the URL.
     */
    "/((?!_next/static|_next/image|api/|favicon.ico|.*\\..*).*)",
  ],
};
