/**
 * GET /api/admin/deployment/setup-script
 *
 * Returns a downloadable `setup.sh` shell script that bootstraps the
 * Mister Chameleon platform on a fresh Vercel + Supabase Cloud environment.
 *
 * ─── Safety ──────────────────────────────────────────────────────────────────
 *
 *   • Requires a valid platform-admin session (same guard as all admin routes).
 *   • The script never contains actual secrets — it only references env var
 *     names that the operator must fill in manually.
 *   • All destructive commands (db push, seed) are behind `--confirm` prompts
 *     so the script cannot be accidentally run twice without operator intent.
 *
 * ─── Usage ───────────────────────────────────────────────────────────────────
 *
 *   Download from the Deployment dashboard → "Download setup.sh"
 *   Then on a terminal with the project cloned:
 *
 *     chmod +x setup.sh
 *     ./setup.sh
 */

import { NextResponse }            from "next/server";
import { getRequiredAdminSession } from "@/lib/admin-auth/authorization";

export async function GET() {
  await getRequiredAdminSession();

  const script = `#!/usr/bin/env bash
# =============================================================================
#  Mister Chameleon — Platform Bootstrap Script
#  Generated by the Deployment Dashboard.
#
#  Run this script on a fresh clone of the repository to set up the platform
#  on Vercel + Supabase Cloud.
#
#  IMPORTANT: Fill in all <PLACEHOLDER> values before running.
#             Never commit this file with real secrets.
#
#  Usage:
#    chmod +x setup.sh
#    ./setup.sh
# =============================================================================

set -euo pipefail

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\\033[0;31m'; YELLOW='\\033[1;33m'; GREEN='\\033[0;32m'
CYAN='\\033[0;36m'; BOLD='\\033[1m'; RESET='\\033[0m'

log()  { echo -e "\\n\${CYAN}\${BOLD}[setup]\${RESET} $*"; }
ok()   { echo -e "\${GREEN}✓\${RESET} $*"; }
warn() { echo -e "\${YELLOW}⚠\${RESET} $*"; }
err()  { echo -e "\${RED}✗\${RESET} $*" >&2; exit 1; }

confirm() {
  read -r -p "$1 [y/N] " ans
  [[ "\${ans,,}" == "y" ]] || { echo "Skipped."; return 1; }
}

# ── Prerequisites check ───────────────────────────────────────────────────────
log "Checking prerequisites…"

command -v node    >/dev/null 2>&1 || err "node not found — install Node.js 18+"
command -v npm     >/dev/null 2>&1 || err "npm not found"
command -v supabase >/dev/null 2>&1 || warn "supabase CLI not found — install from https://supabase.com/docs/guides/cli"
command -v vercel  >/dev/null 2>&1 || warn "vercel CLI not found — run: npm i -g vercel"

NODE_VERSION=\$(node -e "process.stdout.write(process.version.slice(1).split('.')[0])")
(( NODE_VERSION >= 18 )) || err "Node.js 18+ required (found v\${NODE_VERSION})"
ok "Prerequisites satisfied"

# ── Step 1 — Install dependencies ────────────────────────────────────────────
log "Step 1/8 — Installing npm dependencies…"
npm install
ok "Dependencies installed"

# ── Step 2 — Link Supabase project ───────────────────────────────────────────
log "Step 2/8 — Linking Supabase project…"
echo ""
echo "  You will need:"
echo "    • Your Supabase project reference (from Project Settings → General)"
echo "    • Your database password"
echo ""

if confirm "Run 'supabase link' now?"; then
  supabase link
  ok "Supabase project linked"
fi

# ── Step 3 — Apply database migrations ───────────────────────────────────────
log "Step 3/8 — Applying database migrations…"
warn "This will push all pending migrations to your linked Supabase project."
warn "Irreversible on production — make sure you have a backup first."
echo ""

if confirm "Run 'supabase db push' now?"; then
  supabase db push
  ok "Migrations applied"
fi

# ── Step 4 — Seed enrichment pricing ─────────────────────────────────────────
log "Step 4/8 — Seeding enrichment pricing…"
warn "This seeds default credit costs for all enrichment types."
echo ""

if confirm "Run platform seed now?"; then
  npx tsx cms/seed/platform-seed.ts
  ok "Platform seed complete"
fi

# ── Step 5 — Configure environment variables ──────────────────────────────────
log "Step 5/8 — Environment variable checklist"
echo ""
echo "  Copy .env.example to .env.local and fill in all required values:"
echo ""
echo "  \${BOLD}Supabase\${RESET}"
echo "    NEXT_PUBLIC_SUPABASE_URL        — Project URL from API settings"
echo "    NEXT_PUBLIC_SUPABASE_ANON_KEY   — Anon key from API settings"
echo "    SUPABASE_SERVICE_ROLE_KEY       — Service role key (keep secret!)"
echo ""
echo "  \${BOLD}Auth\${RESET}"
echo "    ADMIN_SESSION_SECRET            — Random 32+ char string (openssl rand -base64 32)"
echo "    ADMIN_TOTP_ISSUER               — Label shown in the 2FA authenticator app"
echo ""
echo "  \${BOLD}AI\${RESET}"
echo "    ANTHROPIC_API_KEY               — From https://console.anthropic.com"
echo "    OPENAI_API_KEY                  — From https://platform.openai.com"
echo ""
echo "  \${BOLD}Enrichment\${RESET}"
echo "    MAXMIND_DB_PATH                 — Path to the local MaxMind GeoLite database"
echo "    IPINFO_TOKEN                    — From https://ipinfo.io/account"
echo "    CLEARBIT_SECRET_KEY             — From https://dashboard.clearbit.com"
echo "    LEADINFO_API_KEY                — From your Leadinfo account"
echo ""
echo "  \${BOLD}Email\${RESET}"
echo "    RESEND_API_KEY                  — From https://resend.com/api-keys"
echo "    MAIL_FROM_ADDRESS               — Verified sender address"
echo "    BACKOFFICE_EMAIL                — Fallback recipient for form notifications"
echo "    EMAIL_ENCRYPTION_KEY            — 32-byte hex; encrypts per-tenant transports (never change)"
echo ""
echo "  \${BOLD}Storage\${RESET}"
echo "    R2_ACCOUNT_ID                   — Cloudflare account ID"
echo "    R2_ACCESS_KEY_ID                — R2 API token key ID"
echo "    R2_SECRET_ACCESS_KEY            — R2 API token secret"
echo "    R2_BUCKET_NAME                  — Your R2 bucket name"
echo "    R2_PUBLIC_URL                   — Public URL for the R2 bucket (no trailing slash)"
echo ""
echo "  \${BOLD}CMS\${RESET}"
echo "    NEXT_PUBLIC_SANITY_PROJECT_ID   — From https://sanity.io/manage"
echo "    NEXT_PUBLIC_SANITY_DATASET      — Usually 'production'"
echo "    SANITY_API_TOKEN                — From Sanity API settings"
echo ""
echo "  \${BOLD}Payments\${RESET}"
echo "    STRIPE_SECRET_KEY               — From https://dashboard.stripe.com/apikeys"
echo "    STRIPE_WEBHOOK_SECRET           — From Stripe webhook settings"
echo "    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY — From Stripe API keys"
echo ""
echo "  \${BOLD}HubSpot\${RESET}"
echo "    HUBSPOT_ACCESS_TOKEN            — From HubSpot → Settings → Integrations → Private Apps"
echo ""
echo "  \${BOLD}Vercel Domains\${RESET}"
echo "    VERCEL_API_TOKEN                — From https://vercel.com/account/tokens"
echo "    VERCEL_PROJECT_ID               — Required together with the token"
echo "    VERCEL_TEAM_ID                  — Only for team-scoped tokens"
echo ""
echo "  \${BOLD}CMS — Statamic\${RESET}"
echo "    STATAMIC_API_URL                — Base URL of the Statamic site (no trailing slash)"
echo "    STATAMIC_API_KEY                — API token AND shared secret for the CMS write route"
echo "                                      (must equal MISTER_CHAMELEON_CMS_WRITE_TOKEN in Ploi)"
echo ""
echo "  \${BOLD}Cron\${RESET}"
echo "    CRON_SECRET                     — Gates every /api/cron/* endpoint (auto-injected on Vercel)"
echo ""
echo "  \${BOLD}Lead base & webhooks\${RESET}"
echo "    LEAD_INBOUND_SECRET             — x-mc-secret for /api/webhooks/inbound-form"
echo "                                      (same value in the Statamic app .env)"
echo "    LEAD_SUPPRESSION_SECRET         — x-mc-secret for /api/webhooks/suppression"
echo ""
echo "  \${BOLD}Google Calendar (demo bookings)\${RESET}"
echo "    GOOGLE_SERVICE_ACCOUNT_EMAIL       — Service account for Google Calendar"
echo "    GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY — Private key for that service account"
echo "    GOOGLE_CALENDAR_ID                 — Target calendar"
echo ""
echo "  \${BOLD}Note\${RESET}"
echo "    Google Ads (retargeting + conversions) has no env vars by design — configure"
echo "    it per tenant under Audience → Retargeting. Meilisearch is likewise per tenant"
echo "    under Platform → Search."
echo ""
echo "  Most credentials can also be set via Admin → Platform → Integrations, which"
echo "  stores them encrypted in the database and takes precedence over env vars."
echo "  See .env.example for the full list and documentation."

# ── Step 6 — Local development build test ─────────────────────────────────────
log "Step 6/8 — Verifying local build…"
echo ""

if confirm "Run 'npm run build' to verify the build locally?"; then
  npm run build
  ok "Build succeeded"
fi

# ── Step 7 — Deploy to Vercel ─────────────────────────────────────────────────
log "Step 7/8 — Deploy to Vercel…"
echo ""
echo "  Before deploying, make sure all environment variables above are set"
echo "  in your Vercel project settings (Settings → Environment Variables)."
echo ""

if confirm "Run 'vercel deploy --prod' now?"; then
  vercel deploy --prod
  ok "Deployed to production"
fi

# ── Step 8 — Post-deploy verification ────────────────────────────────────────
log "Step 8/8 — Post-deploy verification checklist"
echo ""
echo "  After deploy, verify the following in the admin dashboard:"
echo ""
echo "  1. Open /admin/platform/deployment — all checks should be green"
echo "  2. Enrichment pricing rows should show non-zero credit costs"
echo "     If any show 0 cr, click 'Reset to defaults'"
echo "  3. Open /admin/tenants and verify at least one tenant exists"
echo "  4. Test a scenario enrichment run from the Scenario Control Panel"
echo "  5. Check /admin/ai-logs for any connection errors"
echo ""
echo "  Automated backup setup (recommended):"
echo "    • Set up Supabase scheduled backups in Project Settings → Backups"
echo "    • Or run: npm run backup  (saves to R2)"
echo "    • Schedule with cron: 0 3 * * * cd /path/to/project && npm run backup"
echo ""

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "\${GREEN}\${BOLD}╔══════════════════════════════════════════════════════════╗\${RESET}"
echo -e "\${GREEN}\${BOLD}║  Setup complete — Mister Chameleon is ready to launch!  ║\${RESET}"
echo -e "\${GREEN}\${BOLD}╚══════════════════════════════════════════════════════════╝\${RESET}"
echo ""
echo "  Next steps:"
echo "    • Visit your deployment URL and log in as platform admin"
echo "    • Open /admin/platform/deployment to verify all systems"
echo "    • Create your first tenant at /admin/onboarding"
echo ""
`;

  return new NextResponse(script, {
    status: 200,
    headers: {
      "Content-Type":        "text/plain; charset=utf-8",
      "Content-Disposition": 'attachment; filename="setup.sh"',
      "Cache-Control":       "no-store",
    },
  });
}
