/**
 * Supabase Database Type Definitions
 *
 * Strongly-typed schema for the Mister Chameleon Supabase database.
 * These types are consumed by the Supabase JS client via the generic
 * parameter in `createClient<Database>(...)`, providing end-to-end
 * type safety for all table reads and writes.
 *
 * ─── Schema overview ──────────────────────────────────────────────────────────
 *
 *   sessions        — one row per visitor session
 *   served_variants — the variant set resolved for each session
 *   events          — arbitrary named events tied to a session
 *
 * ─── Keeping types in sync ────────────────────────────────────────────────────
 *
 *   This file is the hand-authored source of truth until the Supabase CLI
 *   type generator is wired in. When the SQL schema changes, update the
 *   `Row`, `Insert`, and `Update` types below to match.
 *
 *   To switch to auto-generated types:
 *     npx supabase gen types typescript --project-id <id> > src/data/database.types.ts
 *   Then re-export from this file or replace it.
 *
 * ─── SQL migration reference ──────────────────────────────────────────────────
 *
 *   See supabase/migrations/ for the CREATE TABLE statements that define
 *   the backing schema.
 */

// ── sessions ──────────────────────────────────────────────────────────────────

export interface SessionRow {
  /** UUID primary key, generated by the database. */
  id: string;
  /** ISO-8601 timestamp set by the database on insert. */
  created_at: string;
  /** Resolved traffic source — linkedin | google | direct | unknown */
  source: string;
  /** Detected device class — mobile | desktop */
  device: string;
  /** First or returning visit — new | returning */
  visit_type: string;
  /** Pathname of the page that triggered session creation, e.g. "/" */
  pathname: string;
  /** Full Referer header value, null if absent */
  referrer: string | null;
  /** utm_source query parameter */
  utm_source: string | null;
  /** utm_medium query parameter */
  utm_medium: string | null;
  /** utm_campaign query parameter */
  utm_campaign: string | null;
}

export interface SessionInsert {
  /** Optional: omit to let the database generate a UUID. */
  id?: string;
  /** Optional: omit to let the database set to now(). */
  created_at?: string;
  source: string;
  device: string;
  visit_type: string;
  pathname: string;
  referrer?: string | null;
  utm_source?: string | null;
  utm_medium?: string | null;
  utm_campaign?: string | null;
}

// ── served_variants ───────────────────────────────────────────────────────────

export interface ServedVariantRow {
  /** UUID primary key, generated by the database. */
  id: string;
  /** FK → sessions.id */
  session_id: string;
  /** ISO-8601 timestamp set by the database on insert. */
  created_at: string;
  /** Selected hero variant key, e.g. "hero_google_problem" */
  hero_key: string;
  /** Selected proof variant key, e.g. "proof_cases" */
  proof_key: string;
  /** Selected CTA variant key, e.g. "cta_meeting" */
  cta_key: string;
  /** Human-readable reason the rule fired */
  reason: string;
  /**
   * Tenant slug this row belongs to, e.g. "mister-chameleon" | "workengine".
   * Null for rows written before migration 20240101000008 (treated as unscoped).
   */
  tenant_id: string | null;
}

export interface ServedVariantInsert {
  /** Optional: omit to let the database generate a UUID. */
  id?: string;
  session_id: string;
  /** Optional: omit to let the database set to now(). */
  created_at?: string;
  hero_key: string;
  proof_key: string;
  cta_key: string;
  reason: string;
  /** Tenant slug — omit only for legacy back-compat inserts. */
  tenant_id?: string | null;
}

// ── events ────────────────────────────────────────────────────────────────────

export interface EventRow {
  /** UUID primary key, generated by the database. */
  id: string;
  /** FK → sessions.id */
  session_id: string;
  /** ISO-8601 timestamp set by the database on insert. */
  created_at: string;
  /** Named event type, e.g. "page_view" | "cta_click" | "form_submit" */
  event_type: string;
  /** Arbitrary JSON payload — defaults to {} at the database level */
  payload: Record<string, unknown>;
  /**
   * Tenant slug this event belongs to, e.g. "mister-chameleon" | "workengine".
   * Null for rows written before migration 20240101000008 (treated as unscoped).
   */
  tenant_id: string | null;
}

export interface EventInsert {
  /** Optional: omit to let the database generate a UUID. */
  id?: string;
  session_id: string;
  /** Optional: omit to let the database set to now(). */
  created_at?: string;
  event_type: string;
  /** Defaults to {} at the database level; omit for events with no metadata. */
  payload?: Record<string, unknown>;
  /** Tenant slug — omit only for legacy back-compat inserts. */
  tenant_id?: string | null;
}

// ── ai_decision_logs ──────────────────────────────────────────────────────────

/**
 * JSONB shape stored in `ai_decision_logs.live_plan` and `shadow_plan`.
 * Matches the ExperiencePlan structure plus AI-specific metadata fields
 * (confidence, policy verdict, model info) for the shadow column.
 */
export interface AiPlanSnapshot {
  heroKey: string;
  proofKey: string;
  ctaKey: string;
  reason: string;
  /** AI self-reported confidence (0-1), only present in shadow_plan */
  confidence?: number;
  /** Confidence policy verdict, only present in shadow_plan */
  policyVerdict?: string;
  /** Context richness score at decision time, only present in shadow_plan */
  contextRichness?: number;
  /**
   * Structural validation score for the AI plan (0 or 1):
   * 1.0 = all keys present and in allowed vocabulary; 0.0 = hard-validation failure.
   * Only present in shadow_plan.
   */
  validationScore?: number;
  /**
   * Visitor context strength score (0..1): how much context signal supports
   * trusting the AI output.  Only present in shadow_plan.
   */
  contextStrength?: number;
  /**
   * Composite final confidence (0..1):
   *   finalConfidence = aiConfidence×0.60 + validationScore×0.20 + contextStrength×0.20
   * Only present in shadow_plan.
   */
  finalConfidence?: number;
  /**
   * The configured confidence threshold at decision time.
   * Only present in shadow_plan.
   */
  configuredThreshold?: number;
  /** Model that produced this plan, only present in shadow_plan */
  modelId?: string;
  /** Inference latency in ms, only present in shadow_plan */
  latencyMs?: number;
  /** Policy gate results, only present in shadow_plan */
  gateResults?: Array<{ gate: string; passed: boolean; score?: number }>;
}

/** JSONB shape stored in `ai_decision_logs.context` */
export interface AiContextSnapshot {
  source: string;
  device: string;
  visitType: string;
  utmSource: string | null;
  utmMedium: string | null;
  utmCampaign: string | null;
  referrerDomain: string | null;
  pathname?: string;
}

export interface AiDecisionLogRow {
  /** UUID primary key, generated by the database */
  id: string;
  /** FK → sessions.id */
  session_id: string;
  /** ISO-8601 timestamp */
  created_at: string;
  /**
   * Tenant slug that originated the decision, e.g. "mister-chameleon".
   * Null for rows written before migration 20240101000007.
   */
  tenant_id: string | null;
  /** Page the decision was for, e.g. "homepage" */
  page_type: string;
  /** Name of the provider that produced the rendered plan, e.g. "rules" | "ai:claude" */
  live_provider: string;
  /** JSONB snapshot of the rendered ExperiencePlan */
  live_plan: AiPlanSnapshot;
  /** Name of the AI provider that ran, e.g. "claude" | "openai" */
  shadow_provider: string;
  /** JSONB snapshot of the AI ExperiencePlan with confidence metadata */
  shadow_plan: AiPlanSnapshot;
  /** true when heroKey + proofKey + ctaKey match across live and shadow plans */
  plans_match: boolean;
  /** JSONB snapshot of the VisitorContext at decision time */
  context: AiContextSnapshot;
}

export interface AiDecisionLogInsert {
  id?: string;
  session_id: string;
  created_at?: string;
  /**
   * Tenant slug that originated the decision.
   * Omit (or pass undefined/null) when the tenant is unknown.
   * Never pass API keys or credentials — those stay in process.env only.
   */
  tenant_id?: string | null;
  page_type: string;
  live_provider: string;
  live_plan: AiPlanSnapshot;
  shadow_provider: string;
  shadow_plan: AiPlanSnapshot;
  plans_match: boolean;
  context: AiContextSnapshot;
}

// ── experiments ───────────────────────────────────────────────────────────────

/**
 * One row per defined A/B experiment.
 * Managed via the Supabase dashboard or direct SQL inserts.
 */
export interface ExperimentRow {
  /** Stable text slug, e.g. "hero_problem_vs_brand_2025_q2" */
  id: string;
  /** Human-readable label for the dashboard */
  name: string;
  /** Which page slot is being tested: hero | proof | cta */
  slot: "hero" | "proof" | "cta";
  /**
   * Ordered array of variant keys.
   * Index 0 → bucket 0, index 1 → bucket 1, etc.
   * Must contain at least two entries.
   */
  variants: string[];
  /** Lifecycle state */
  status: "active" | "paused" | "ended";
  /** Proportion of sessions enrolled: 0 < f ≤ 1.0 */
  traffic_fraction: number;
  /** ISO-8601 creation timestamp */
  created_at: string;
  /** ISO-8601 timestamp set when status transitions to "ended", or null */
  ended_at: string | null;
}

export interface ExperimentInsert {
  /** Required stable slug */
  id: string;
  name: string;
  slot: "hero" | "proof" | "cta";
  variants: string[];
  /** Defaults to "active" in the database */
  status?: "active" | "paused" | "ended";
  /** Defaults to 1.0 in the database */
  traffic_fraction?: number;
  created_at?: string;
  ended_at?: string | null;
}

// ── experiment_assignments ─────────────────────────────────────────────────────

/**
 * One row per (session × experiment) pair.
 * Written on the first request a session is enrolled in an experiment;
 * subsequent requests reuse the deterministic bucket without another write.
 */
export interface ExperimentAssignmentRow {
  /** UUID primary key */
  id: string;
  /** FK → sessions.id */
  session_id: string;
  /** FK → experiments.id */
  experiment_id: string;
  /** 0-based bucket index into experiments.variants */
  bucket: number;
  /** Resolved variant key (denormalised for query convenience) */
  variant_key: string;
  /** ISO-8601 assignment timestamp */
  created_at: string;
}

export interface ExperimentAssignmentInsert {
  id?: string;
  session_id: string;
  experiment_id: string;
  bucket: number;
  variant_key: string;
  created_at?: string;
}

// ── plan_experiments ──────────────────────────────────────────────────────────

/**
 * A plan-based A/B experiment that targets a specific rule.
 *
 * When the rule fires for a visitor, the experiment determines whether that
 * visitor receives the rule's control plan (bucket 0) or the challenger plan
 * (bucket 1, which merges challenger_plan onto the control plan).
 */
export interface PlanExperimentRow {
  /** Stable text slug used in the bucket hash. */
  id: string;
  /** Human-readable label for the dashboard. */
  name: string;
  /** Tenant that owns this experiment (matches tenantConfig.tenantId). */
  tenant_id: string;
  /** Soft reference to the rule ID this experiment targets. */
  rule_id: string;
  /**
   * Partial ExperiencePlan applied to bucket-1 visitors.
   * Keys present override the corresponding control-plan slot.
   * Missing keys inherit from the control plan unchanged.
   */
  challenger_plan: {
    heroKey?:       string;
    proofKey?:      string;
    ctaKey?:        string;
    featureKey?:    string;
    conversionKey?: string;
  };
  /** Lifecycle state */
  status: "draft" | "active" | "paused" | "ended";
  /** Fraction of matching sessions enrolled: 0 < f ≤ 1.0 */
  traffic_fraction: number;
  /** ISO-8601 creation timestamp */
  created_at: string;
  /** ISO-8601 end timestamp, or null while active/paused/draft */
  ended_at: string | null;
}

export interface PlanExperimentInsert {
  id: string;
  name: string;
  /**
   * Tenant that owns this experiment.
   * Optional here so form components can omit it — the server action always
   * sets it explicitly before the DB insert (via `tenant_id: tenantId` spread).
   */
  tenant_id?: string;
  rule_id: string;
  challenger_plan?: PlanExperimentRow["challenger_plan"];
  status?: "draft" | "active" | "paused" | "ended";
  traffic_fraction?: number;
  created_at?: string;
  ended_at?: string | null;
}

// ── plan_experiment_assignments ───────────────────────────────────────────────

/**
 * One row per (session × plan_experiment) pair.
 * bucket 0 = control (rule plan unchanged)
 * bucket 1 = challenger (challenger_plan applied)
 */
export interface PlanExperimentAssignmentRow {
  /** UUID primary key */
  id: string;
  /** FK → sessions.id */
  session_id: string;
  /** FK → plan_experiments.id */
  experiment_id: string;
  /** 0 = control, 1 = challenger */
  bucket: 0 | 1;
  /** ISO-8601 assignment timestamp */
  created_at: string;
}

export interface PlanExperimentAssignmentInsert {
  id?: string;
  session_id: string;
  experiment_id: string;
  bucket: 0 | 1;
  created_at?: string;
}

// ── form_submissions ──────────────────────────────────────────────────────────

/**
 * One row per submitted and validated form — written by the
 * /api/forms/[formKey] route when formDef.action.storeSubmissions is true.
 *
 * SQL:
 *   form_submissions (
 *     id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
 *     created_at  timestamptz NOT NULL DEFAULT now(),
 *     form_key    text        NOT NULL,
 *     values      jsonb       NOT NULL,
 *     session_id  uuid        NULL REFERENCES sessions(id) ON DELETE SET NULL,
 *     tenant_id   text        NULL
 *   )
 */
export interface FormSubmissionRow {
  /** UUID primary key, generated by the database. */
  id:          string;
  /** ISO-8601 timestamp set by the database on insert. */
  created_at:  string;
  /** Registered form key, e.g. "contact" | "application" */
  form_key:    string;
  /** Validated, trimmed submission values keyed by field key. */
  values:      Record<string, string>;
  /** FK → sessions.id — nullable; absent for submissions without a platform session. */
  session_id:  string | null;
  /** Owning tenant slug, e.g. "workengine". Null for legacy un-scoped rows. */
  tenant_id:   string | null;
}

export interface FormSubmissionInsert {
  /** Optional: omit to let the database generate a UUID. */
  id?:         string;
  /** Optional: omit to let the database set to now(). */
  created_at?: string;
  form_key:    string;
  values:      Record<string, string>;
  session_id?: string | null;
  tenant_id?:  string | null;
}

// ── tenant_settings ───────────────────────────────────────────────────────────

/**
 * One row per platform tenant.
 * Stores the full TenantSettings object as JSONB.
 * Replaces the local tenant/tenants.json file store.
 *
 * SQL migration: supabase/migrations/20240101000009_create_tenant_settings.sql
 *
 * ─── Column notes ────────────────────────────────────────────────────────────
 *
 *   id         — primary row identifier; set to the same value as tenant_id
 *                (the tenant slug, e.g. "mister-chameleon").  Required by the
 *                live schema; must be included in every INSERT / UPSERT.
 *
 *   tenant_id  — the natural key used for ON CONFLICT / application lookups.
 *                Mirrors `id` — they always hold the same slug string.
 *
 * Having both columns is a historical artefact of the Supabase dashboard
 * adding an `id` column when the table was inspected after the original
 * migration (which defined only tenant_id as PK) was applied.  Both columns
 * are kept in sync by always writing `id = tenantId` in the application layer.
 */
export interface TenantSettingsRow {
  /** Row identity — same value as tenant_id (the tenant slug). */
  id:         string;
  /** Stable tenant slug (TenantSettings.tenantId), e.g. "workengine". */
  tenant_id:  string;
  /** Full TenantSettings object serialised as JSONB. */
  settings:   Record<string, unknown>;
  /** Last write timestamp. */
  updated_at: string;
}

export interface TenantSettingsInsert {
  /** Row identity — must equal tenant_id (the tenant slug). */
  id:          string;
  tenant_id:   string;
  settings:    Record<string, unknown>;
  /** Optional: omit to let the database set to now(). */
  updated_at?: string;
}

// ── rules_config ──────────────────────────────────────────────────────────────

/**
 * Stores operator-authored homepage rules configurations as JSONB.
 * Replaces the local decision/rules/runtime-rules.json file.
 *
 * SQL migration: supabase/migrations/20240101000010_create_rules_config.sql
 */
export interface RulesConfigRow {
  /** Logical config name — currently always "homepage". */
  key:        string;
  /** Full StoredRulesConfig object serialised as JSONB. */
  config:     Record<string, unknown>;
  /** Last write timestamp. */
  updated_at: string;
}

export interface RulesConfigInsert {
  key:         string;
  config:      Record<string, unknown>;
  /** Optional: omit to let the database set to now(). */
  updated_at?: string;
}

// ── pages ─────────────────────────────────────────────────────────────────────

/**
 * One row per admin-editable page.
 * Stores the full EditablePage object as JSONB.
 * Replaces the local page-store/data/pages.json file.
 *
 * SQL migration: supabase/migrations/20240101000011_create_pages.sql
 */
export interface PageRow {
  /** Stable page identifier (CMS _id or admin-generated UUID). */
  id:         string;
  /** Owning tenant slug, e.g. "workengine". */
  tenant_id:  string;
  /** URL slug without leading slash, e.g. "about-us". */
  slug:       string;
  /** Human-readable page title, mirrors EditablePage.title for indexed lookups. */
  title:      string;
  /** Full EditablePage object serialised as JSONB. */
  page:       Record<string, unknown>;
  /** Row creation timestamp. */
  created_at: string;
  /** Last write timestamp. */
  updated_at: string;
}

export interface PageInsert {
  id:          string;
  tenant_id:   string;
  slug:        string;
  /** Human-readable page title — NOT NULL in the DB. */
  title:       string;
  page:        Record<string, unknown>;
  /** Optional: omit to let the database set to now(). */
  created_at?: string;
  /** Optional: omit to let the database set to now(). */
  updated_at?: string;
}

// ── tenant_domains ────────────────────────────────────────────────────────────

/**
 * Status of a custom domain registration.
 *
 *   pending — domain added; DNS / Vercel verification not yet confirmed.
 *   active  — domain is verified and fully operational.
 *   error   — domain verification failed or was rejected by Vercel.
 */
export type DomainStatus = "pending" | "active" | "error";

/**
 * One row per custom domain registered for a tenant.
 *
 * SQL migration: supabase/migrations/20240101000012_create_tenant_domains.sql
 */
export interface TenantDomainRow {
  /** UUID primary key. */
  id:                  string;
  /** Owning tenant slug, e.g. "workengine". */
  tenant_id:           string;
  /** Normalised hostname without protocol or trailing slash, e.g. "acme.com". */
  hostname:            string;
  /** True when this is the tenant's primary domain. */
  is_primary:          boolean;
  /** Verification and routing status. */
  status:              DomainStatus;
  /** Vercel domain ID returned by the Domains API, null when not using Vercel. */
  vercel_domain_id:    string | null;
  /** Vercel DNS verification records (CNAME / TXT) as returned by the API. */
  vercel_verification: Record<string, unknown> | null;
  /** Row creation timestamp. */
  created_at:          string;
  /** Last write timestamp. */
  updated_at:          string;
}

export interface TenantDomainInsert {
  /** Optional: omit to let the database generate a UUID. */
  id?:                  string;
  tenant_id:            string;
  hostname:             string;
  is_primary?:          boolean;
  /** Defaults to "pending" at the database level. */
  status?:              DomainStatus;
  vercel_domain_id?:    string | null;
  vercel_verification?: Record<string, unknown> | null;
  created_at?:          string;
  updated_at?:          string;
}

// ── context_variable_metadata ─────────────────────────────────────────────────

/**
 * One row per context variable that has been given admin-editable metadata.
 *
 * Built-in variables (is_custom = false) have their system fields (type, source,
 * operators, allowedValues) defined in context/registry.ts — only the editable
 * overlay fields are stored here.
 *
 * Custom variables (is_custom = true) are fully described by this row; they do
 * not exist in the registry.  custom_type and custom_source are required for them.
 *
 * SQL migration: supabase/migrations/20240101000013_create_context_variable_metadata.sql
 */
export interface ContextVariableMetadataRow {
  /** The stable context variable key, e.g. "source" or "company_name". */
  key:             string;
  /** Operator-edited human-readable label; null means use the registry default. */
  label:           string | null;
  /** Operator-edited description; null means use the registry default. */
  description:     string | null;
  /** When false the variable is hidden from rules / AI selection. */
  enabled:         boolean;
  /** Runtime gate for rules availability; null means defer to registry flag. */
  usable_in_rules: boolean | null;
  /** Runtime gate for AI availability; null means defer to registry flag. */
  usable_in_ai:    boolean | null;
  /** Optional grouping label shown in the admin UI. */
  category:        string | null;
  /** Display order within a group; defaults to 0. */
  sort_order:      number;
  /** True only for variables created via the admin UI; false for registry vars. */
  is_custom:       boolean;
  /**
   * Required when is_custom = true.
   * One of: string | enum | number | boolean
   */
  custom_type:     string | null;
  /**
   * Required when is_custom = true.
   * One of: request | session | history | tenant | page | enrichment
   */
  custom_source:   string | null;
  /** Row creation timestamp. */
  created_at:      string;
  /** Last modification timestamp. */
  updated_at:      string;
}

export interface ContextVariableMetadataInsert {
  key:              string;
  label?:           string | null;
  description?:     string | null;
  enabled?:         boolean;
  usable_in_rules?: boolean | null;
  usable_in_ai?:    boolean | null;
  category?:        string | null;
  sort_order?:      number;
  is_custom?:       boolean;
  custom_type?:     string | null;
  custom_source?:   string | null;
  created_at?:      string;
  updated_at?:      string;
}

/** Subset of fields that can be changed after creation. */
export interface ContextVariableMetadataUpdate {
  label?:           string | null;
  description?:     string | null;
  enabled?:         boolean;
  usable_in_rules?: boolean | null;
  usable_in_ai?:    boolean | null;
  category?:        string | null;
  sort_order?:      number;
}

// ── platform_settings ─────────────────────────────────────────────────────────

/**
 * One row per platform-wide integration section.
 * Stores secrets and provider configuration as JSONB.
 *
 * Well-known keys: "sanity" | "maxmind" | "ai" | "vercel"
 *
 * SQL migration: supabase/migrations/20240101000016_create_platform_settings.sql
 *
 * ─── Security ─────────────────────────────────────────────────────────────────
 *
 *   `value` is a JSONB blob that MAY contain API keys and write tokens.
 *   It must NEVER be returned to the browser client — only boolean presence
 *   flags (e.g. hasSanityWriteToken) should cross the server→client boundary.
 */
export interface PlatformSettingsRow {
  /** Integration section name, e.g. "sanity" | "maxmind" | "ai" | "vercel". */
  key:        string;
  /**
   * Full settings blob serialised as JSONB.
   * Contains secrets — never serialise to the client.
   */
  value:      Record<string, unknown>;
  /** Last write timestamp. */
  updated_at: string;
}

export interface PlatformSettingsInsert {
  key:         string;
  value:       Record<string, unknown>;
  /** Optional: omit to let the database set to now(). */
  updated_at?: string;
}

// ── admin_users ───────────────────────────────────────────────────────────────

/**
 * One row per platform admin/operator user.
 *
 * two_factor_secret         — live TOTP shared secret (server-side only, never sent to client)
 * two_factor_pending_secret — temporary secret stored during 2FA setup, before verification
 * two_factor_backup_codes   — array of SHA-256 hashed one-time recovery codes
 *
 * SQL migration: supabase/migrations/20240101000020_create_admin_users.sql
 */
export interface AdminUserRow {
  /** UUID primary key. */
  id:                        string;
  /** Normalised email address (lower-cased). */
  email:                     string;
  /** bcrypt-hashed password. Never returned to client code. */
  password_hash:             string;
  /** Display name, e.g. "Jasper Mulders". */
  name:                      string;
  /** "superadmin" | "tenant_admin" (legacy: "admin") */
  role:                      string;
  /** False when the account has been deactivated by a superadmin. */
  is_active:                 boolean;
  /** True when TOTP 2FA is active for this account. */
  two_factor_enabled:        boolean;
  /** Live TOTP shared secret. Null until 2FA is enabled. */
  two_factor_secret:         string | null;
  /** Temporary TOTP secret during setup flow (before verification). Cleared on enable. */
  two_factor_pending_secret: string | null;
  /** Array of SHA-256 hashed one-time backup codes. */
  two_factor_backup_codes:   string[] | null;
  /** ISO-8601 timestamp when 2FA was enabled. */
  two_factor_enabled_at:     string | null;
  /** ISO-8601 timestamp of last successful login. */
  last_login_at:             string | null;
  /** Row creation timestamp. */
  created_at:                string;
  /** Last write timestamp. */
  updated_at:                string;
}

export interface AdminUserInsert {
  id?:                        string;
  email:                      string;
  password_hash:              string;
  name:                       string;
  role?:                      string;
  is_active?:                 boolean;
  two_factor_enabled?:        boolean;
  two_factor_secret?:         string | null;
  two_factor_pending_secret?: string | null;
  two_factor_backup_codes?:   string[] | null;
  two_factor_enabled_at?:     string | null;
  last_login_at?:             string | null;
  created_at?:                string;
  updated_at?:                string;
}

// ── admin_user_tenants ─────────────────────────────────────────────────────────

/**
 * One row per user ↔ tenant assignment.
 * Junction table for the many-to-many relationship between admin_users and tenants.
 * Superadmin users bypass this table — they can access all tenants implicitly.
 *
 * SQL migration: supabase/migrations/20240101000021_admin_user_management.sql
 */
export interface AdminUserTenantRow {
  id:          string;
  user_id:     string;
  tenant_id:   string;
  assigned_at: string;
}

export interface AdminUserTenantInsert {
  id?:          string;
  user_id:      string;
  tenant_id:    string;
  assigned_at?: string;
}

// ── tenant_form_settings ──────────────────────────────────────────────────────

/**
 * Row shape for the `tenant_form_settings` table.
 * SQL migration: supabase/migrations/20240101000024_create_tenant_form_settings.sql
 *
 *   tenant_form_settings (
 *     id         uuid        PRIMARY KEY DEFAULT gen_random_uuid()
 *     tenant_id  text        UNIQUE NOT NULL
 *     settings   jsonb       NOT NULL DEFAULT '{}'
 *     updated_at timestamptz NOT NULL DEFAULT now()
 *   )
 */
export interface TenantFormSettingsRow {
  id:         string;
  tenant_id:  string;
  settings:   Record<string, unknown>;
  updated_at: string;
}

export interface TenantFormSettingsInsert {
  id?:         string;
  tenant_id:   string;
  settings:    Record<string, unknown>;
  updated_at?: string;
}

// ── tenant_email_transport ────────────────────────────────────────────────────

/**
 * Row shape for the `tenant_email_transport` table.
 * SQL migration: supabase/migrations/20240101000025_create_tenant_email_transport.sql
 *
 * Stores per-tenant email transport configuration.  SMTP credentials should
 * be stored encrypted (application-layer encryption) in the `config` JSONB
 * column and decrypted by the admin actions before use.
 *
 *   tenant_email_transport (
 *     id           uuid        PRIMARY KEY DEFAULT gen_random_uuid()
 *     tenant_id    text        UNIQUE NOT NULL
 *     config       jsonb       NOT NULL DEFAULT '{}'
 *     updated_at   timestamptz NOT NULL DEFAULT now()
 *   )
 *
 * The `config` column maps to TenantEmailTransport in tenant/types.ts.
 */
export interface TenantEmailTransportRow {
  id:         string;
  tenant_id:  string;
  config:     Record<string, unknown>;
  updated_at: string;
}

export interface TenantEmailTransportInsert {
  id?:         string;
  tenant_id:   string;
  config:      Record<string, unknown>;
  updated_at?: string;
}

// ── interest_profiles ─────────────────────────────────────────────────────────

/**
 * Row shape for the `interest_profiles` table.
 * SQL migration: supabase/migrations/20240101000026_create_interest_profiles.sql
 *
 * Operators manage profiles via /admin/interest-profiles.
 * The scoring engine reads active profiles to compute per-visitor interest scores.
 *
 *   interest_profiles (
 *     id          uuid        PRIMARY KEY DEFAULT gen_random_uuid()
 *     key         text        UNIQUE NOT NULL
 *     name        text        NOT NULL
 *     description text
 *     tags        jsonb       NOT NULL DEFAULT '[]'
 *     is_active   boolean     NOT NULL DEFAULT true
 *     created_at  timestamptz NOT NULL DEFAULT now()
 *     updated_at  timestamptz NOT NULL DEFAULT now()
 *   )
 */
export interface InterestProfileRow {
  /** UUID primary key. */
  id:          string;
  /** URL-safe slug identifier, e.g. "logistics". */
  key:         string;
  /** Human-readable label shown in admin UI. */
  name:        string;
  /** Optional operator notes. */
  description: string | null;
  /** JSONB array of { keyword: string, weight: number }. */
  tags:        Array<{ keyword: string; weight: number }>;
  /** Only active profiles are evaluated at runtime. */
  is_active:   boolean;
  /** Row creation timestamp. */
  created_at:  string;
  /** Last modification timestamp. */
  updated_at:  string;
}

export interface InterestProfileInsert {
  /** Optional: omit to let the database generate a UUID. */
  id?:          string;
  key:          string;
  name:         string;
  description?: string | null;
  tags:         Array<{ keyword: string; weight: number }>;
  is_active?:   boolean;
  created_at?:  string;
  updated_at?:  string;
}

// ── Platform CMS content ──────────────────────────────────────────────────────

/**
 * platform_cms_content
 *
 * Stores variant documents for tenants using the built-in "platform" CMS.
 * One row per (tenant_id, variant_type, variant_key) triple.
 *
 *   platform_cms_content (
 *     id           uuid        PRIMARY KEY DEFAULT gen_random_uuid()
 *     tenant_id    text        NOT NULL
 *     variant_type text        NOT NULL  CHECK IN ('hero','proof','cta','feature','conversion')
 *     variant_key  text        NOT NULL
 *     content      jsonb       NOT NULL DEFAULT '{}'
 *     created_at   timestamptz NOT NULL DEFAULT now()
 *     updated_at   timestamptz NOT NULL DEFAULT now()
 *     UNIQUE (tenant_id, variant_type, variant_key)
 *   )
 */
export interface PlatformCmsContentRow {
  id:           string;
  tenant_id:    string;
  variant_type: "hero" | "proof" | "cta" | "feature" | "conversion" | "notification";
  variant_key:  string;
  content:      Record<string, unknown>;
  created_at:   string;
  updated_at:   string;
}

export interface PlatformCmsContentInsert {
  id?:           string;
  tenant_id:     string;
  variant_type:  "hero" | "proof" | "cta" | "feature" | "conversion" | "notification";
  variant_key:   string;
  content?:      Record<string, unknown>;
  created_at?:   string;
  updated_at?:   string;
}

// ── Adaptive blocks (Content Matrix) ─────────────────────────────────────────

/**
 * Row shape of the `adaptive_blocks` Supabase table.
 * default_variant and adaptive_variants are stored as JSONB.
 */
export interface AdaptiveBlockRow {
  id:                 string;
  created_at:         string;
  updated_at:         string;
  key:                string;
  tenant_id:          string | null;
  label:              string | null;
  is_active:          boolean;
  default_variant:    Record<string, unknown>;   // AdaptiveVariantContent shape
  adaptive_variants:  Record<string, unknown>[];  // AdaptiveVariantEntry[] shape
}

export interface AdaptiveBlockInsert {
  id?:                string;
  created_at?:        string;
  updated_at?:        string;
  key:                string;
  tenant_id?:         string | null;
  label?:             string | null;
  is_active?:         boolean;
  default_variant:    Record<string, unknown>;
  adaptive_variants?: Record<string, unknown>[];
}

// ── Database schema (Supabase client generic) ─────────────────────────────────

/**
 * Top-level database schema type consumed by `createClient<Database>()`.
 * The `public` schema matches Supabase's default schema name.
 */
export interface Database {
  public: {
    Tables: {
      sessions: {
        Row: SessionRow;
        Insert: SessionInsert;
        Update: Partial<SessionInsert>;
      };
      served_variants: {
        Row: ServedVariantRow;
        Insert: ServedVariantInsert;
        Update: Partial<ServedVariantInsert>;
      };
      events: {
        Row: EventRow;
        Insert: EventInsert;
        Update: Partial<EventInsert>;
      };
      experiments: {
        Row: ExperimentRow;
        Insert: ExperimentInsert;
        Update: Partial<ExperimentInsert>;
      };
      experiment_assignments: {
        Row: ExperimentAssignmentRow;
        Insert: ExperimentAssignmentInsert;
        Update: Partial<ExperimentAssignmentInsert>;
      };
      plan_experiments: {
        Row: PlanExperimentRow;
        Insert: PlanExperimentInsert;
        Update: Partial<PlanExperimentInsert>;
      };
      plan_experiment_assignments: {
        Row: PlanExperimentAssignmentRow;
        Insert: PlanExperimentAssignmentInsert;
        Update: Partial<PlanExperimentAssignmentInsert>;
      };
      ai_decision_logs: {
        Row: AiDecisionLogRow;
        Insert: AiDecisionLogInsert;
        Update: Partial<AiDecisionLogInsert>;
      };
      form_submissions: {
        Row:    FormSubmissionRow;
        Insert: FormSubmissionInsert;
        Update: Partial<FormSubmissionInsert>;
      };
      tenant_settings: {
        Row:    TenantSettingsRow;
        Insert: TenantSettingsInsert;
        Update: Partial<TenantSettingsInsert>;
      };
      rules_config: {
        Row:    RulesConfigRow;
        Insert: RulesConfigInsert;
        Update: Partial<RulesConfigInsert>;
      };
      pages: {
        Row:    PageRow;
        Insert: PageInsert;
        Update: Partial<PageInsert>;
      };
      tenant_domains: {
        Row:    TenantDomainRow;
        Insert: TenantDomainInsert;
        Update: Partial<TenantDomainInsert>;
      };
      context_variable_metadata: {
        Row:    ContextVariableMetadataRow;
        Insert: ContextVariableMetadataInsert;
        Update: ContextVariableMetadataUpdate;
      };
      platform_settings: {
        Row:    PlatformSettingsRow;
        Insert: PlatformSettingsInsert;
        Update: Partial<PlatformSettingsInsert>;
      };
      admin_users: {
        Row:    AdminUserRow;
        Insert: AdminUserInsert;
        Update: Partial<AdminUserInsert>;
      };
      admin_user_tenants: {
        Row:    AdminUserTenantRow;
        Insert: AdminUserTenantInsert;
        Update: Partial<AdminUserTenantInsert>;
      };
      tenant_form_settings: {
        Row:    TenantFormSettingsRow;
        Insert: TenantFormSettingsInsert;
        Update: Partial<TenantFormSettingsInsert>;
      };
      tenant_email_transport: {
        Row:    TenantEmailTransportRow;
        Insert: TenantEmailTransportInsert;
        Update: Partial<TenantEmailTransportInsert>;
      };
      interest_profiles: {
        Row:    InterestProfileRow;
        Insert: InterestProfileInsert;
        Update: Partial<InterestProfileInsert>;
      };
      platform_cms_content: {
        Row:    PlatformCmsContentRow;
        Insert: PlatformCmsContentInsert;
        Update: Partial<PlatformCmsContentInsert>;
      };
      adaptive_blocks: {
        Row:    AdaptiveBlockRow;
        Insert: AdaptiveBlockInsert;
        Update: Partial<AdaptiveBlockInsert>;
      };
    };
  };
}
