/**
 * Supabase Database Type Definitions
 *
 * Strongly-typed schema for the Mister Chameleon Supabase database.
 * These types are consumed by the Supabase JS client via the generic
 * parameter in `createClient<Database>(...)`, providing end-to-end
 * type safety for all table reads and writes.
 *
 * ─── Schema overview ──────────────────────────────────────────────────────────
 *
 *   sessions        — one row per visitor session
 *   served_variants — the variant set resolved for each session
 *   events          — arbitrary named events tied to a session
 *
 * ─── Keeping types in sync ────────────────────────────────────────────────────
 *
 *   This file is the hand-authored source of truth until the Supabase CLI
 *   type generator is wired in. When the SQL schema changes, update the
 *   `Row`, `Insert`, and `Update` types below to match.
 *
 *   To switch to auto-generated types:
 *     npx supabase gen types typescript --project-id <id> > src/data/database.types.ts
 *   Then re-export from this file or replace it.
 *
 * ─── SQL migration reference ──────────────────────────────────────────────────
 *
 *   See supabase/migrations/ for the CREATE TABLE statements that define
 *   the backing schema.
 */

// ── sessions ──────────────────────────────────────────────────────────────────

export interface SessionRow {
  /** UUID primary key, generated by the database. */
  id: string;
  /** ISO-8601 timestamp set by the database on insert. */
  created_at: string;
  /** Resolved traffic source — linkedin | google | direct | unknown */
  source: string;
  /** Detected device class — mobile | desktop */
  device: string;
  /** First or returning visit — new | returning */
  visit_type: string;
  /** Pathname of the page that triggered session creation, e.g. "/" */
  pathname: string;
  /** Full Referer header value, null if absent */
  referrer: string | null;
  /** utm_source query parameter */
  utm_source: string | null;
  /** utm_medium query parameter */
  utm_medium: string | null;
  /** utm_campaign query parameter */
  utm_campaign: string | null;
}

export interface SessionInsert {
  /** Optional: omit to let the database generate a UUID. */
  id?: string;
  /** Optional: omit to let the database set to now(). */
  created_at?: string;
  source: string;
  device: string;
  visit_type: string;
  pathname: string;
  referrer?: string | null;
  utm_source?: string | null;
  utm_medium?: string | null;
  utm_campaign?: string | null;
}

// ── served_variants ───────────────────────────────────────────────────────────

export interface ServedVariantRow {
  /** UUID primary key, generated by the database. */
  id: string;
  /** FK → sessions.id */
  session_id: string;
  /** ISO-8601 timestamp set by the database on insert. */
  created_at: string;
  /** Selected hero variant key, e.g. "hero_google_problem" */
  hero_key: string;
  /** Selected proof variant key, e.g. "proof_cases" */
  proof_key: string;
  /** Selected CTA variant key, e.g. "cta_meeting" */
  cta_key: string;
  /** Human-readable reason the rule fired */
  reason: string;
  /**
   * Tenant slug this row belongs to, e.g. "mister-chameleon" | "workengine".
   * Null for rows written before migration 20240101000008 (treated as unscoped).
   */
  tenant_id: string | null;
}

export interface ServedVariantInsert {
  /** Optional: omit to let the database generate a UUID. */
  id?: string;
  session_id: string;
  /** Optional: omit to let the database set to now(). */
  created_at?: string;
  hero_key: string;
  proof_key: string;
  cta_key: string;
  reason: string;
  /** Tenant slug — omit only for legacy back-compat inserts. */
  tenant_id?: string | null;
}

// ── events ────────────────────────────────────────────────────────────────────

export interface EventRow {
  /** UUID primary key, generated by the database. */
  id: string;
  /** FK → sessions.id */
  session_id: string;
  /** ISO-8601 timestamp set by the database on insert. */
  created_at: string;
  /** Named event type, e.g. "page_view" | "cta_click" | "form_submit" */
  event_type: string;
  /** Arbitrary JSON payload — defaults to {} at the database level */
  payload: Record<string, unknown>;
  /**
   * Tenant slug this event belongs to, e.g. "mister-chameleon" | "workengine".
   * Null for rows written before migration 20240101000008 (treated as unscoped).
   */
  tenant_id: string | null;
}

export interface EventInsert {
  /** Optional: omit to let the database generate a UUID. */
  id?: string;
  session_id: string;
  /** Optional: omit to let the database set to now(). */
  created_at?: string;
  event_type: string;
  /** Defaults to {} at the database level; omit for events with no metadata. */
  payload?: Record<string, unknown>;
  /** Tenant slug — omit only for legacy back-compat inserts. */
  tenant_id?: string | null;
}

// ── ai_decision_logs ──────────────────────────────────────────────────────────

/**
 * JSONB shape stored in `ai_decision_logs.live_plan` and `shadow_plan`.
 * Matches the ExperiencePlan structure plus AI-specific metadata fields
 * (confidence, policy verdict, model info) for the shadow column.
 */
export interface AiPlanSnapshot {
  heroKey: string;
  proofKey: string;
  ctaKey: string;
  reason: string;
  /** AI confidence score (0-1), only present in shadow_plan */
  confidence?: number;
  /** Confidence policy verdict, only present in shadow_plan */
  policyVerdict?: string;
  /** Context richness score at decision time, only present in shadow_plan */
  contextRichness?: number;
  /** Model that produced this plan, only present in shadow_plan */
  modelId?: string;
  /** Inference latency in ms, only present in shadow_plan */
  latencyMs?: number;
  /** Policy gate results, only present in shadow_plan */
  gateResults?: Array<{ gate: string; passed: boolean; score?: number }>;
}

/** JSONB shape stored in `ai_decision_logs.context` */
export interface AiContextSnapshot {
  source: string;
  device: string;
  visitType: string;
  utmSource: string | null;
  utmMedium: string | null;
  utmCampaign: string | null;
  referrerDomain: string | null;
  pathname?: string;
}

export interface AiDecisionLogRow {
  /** UUID primary key, generated by the database */
  id: string;
  /** FK → sessions.id */
  session_id: string;
  /** ISO-8601 timestamp */
  created_at: string;
  /**
   * Tenant slug that originated the decision, e.g. "mister-chameleon".
   * Null for rows written before migration 20240101000007.
   */
  tenant_id: string | null;
  /** Page the decision was for, e.g. "homepage" */
  page_type: string;
  /** Name of the provider that produced the rendered plan, e.g. "rules" | "ai:claude" */
  live_provider: string;
  /** JSONB snapshot of the rendered ExperiencePlan */
  live_plan: AiPlanSnapshot;
  /** Name of the AI provider that ran, e.g. "claude" | "openai" */
  shadow_provider: string;
  /** JSONB snapshot of the AI ExperiencePlan with confidence metadata */
  shadow_plan: AiPlanSnapshot;
  /** true when heroKey + proofKey + ctaKey match across live and shadow plans */
  plans_match: boolean;
  /** JSONB snapshot of the VisitorContext at decision time */
  context: AiContextSnapshot;
}

export interface AiDecisionLogInsert {
  id?: string;
  session_id: string;
  created_at?: string;
  /**
   * Tenant slug that originated the decision.
   * Omit (or pass undefined/null) when the tenant is unknown.
   * Never pass API keys or credentials — those stay in process.env only.
   */
  tenant_id?: string | null;
  page_type: string;
  live_provider: string;
  live_plan: AiPlanSnapshot;
  shadow_provider: string;
  shadow_plan: AiPlanSnapshot;
  plans_match: boolean;
  context: AiContextSnapshot;
}

// ── experiments ───────────────────────────────────────────────────────────────

/**
 * One row per defined A/B experiment.
 * Managed via the Supabase dashboard or direct SQL inserts.
 */
export interface ExperimentRow {
  /** Stable text slug, e.g. "hero_problem_vs_brand_2025_q2" */
  id: string;
  /** Human-readable label for the dashboard */
  name: string;
  /** Which page slot is being tested: hero | proof | cta */
  slot: "hero" | "proof" | "cta";
  /**
   * Ordered array of variant keys.
   * Index 0 → bucket 0, index 1 → bucket 1, etc.
   * Must contain at least two entries.
   */
  variants: string[];
  /** Lifecycle state */
  status: "active" | "paused" | "ended";
  /** Proportion of sessions enrolled: 0 < f ≤ 1.0 */
  traffic_fraction: number;
  /** ISO-8601 creation timestamp */
  created_at: string;
  /** ISO-8601 timestamp set when status transitions to "ended", or null */
  ended_at: string | null;
}

export interface ExperimentInsert {
  /** Required stable slug */
  id: string;
  name: string;
  slot: "hero" | "proof" | "cta";
  variants: string[];
  /** Defaults to "active" in the database */
  status?: "active" | "paused" | "ended";
  /** Defaults to 1.0 in the database */
  traffic_fraction?: number;
  created_at?: string;
  ended_at?: string | null;
}

// ── experiment_assignments ─────────────────────────────────────────────────────

/**
 * One row per (session × experiment) pair.
 * Written on the first request a session is enrolled in an experiment;
 * subsequent requests reuse the deterministic bucket without another write.
 */
export interface ExperimentAssignmentRow {
  /** UUID primary key */
  id: string;
  /** FK → sessions.id */
  session_id: string;
  /** FK → experiments.id */
  experiment_id: string;
  /** 0-based bucket index into experiments.variants */
  bucket: number;
  /** Resolved variant key (denormalised for query convenience) */
  variant_key: string;
  /** ISO-8601 assignment timestamp */
  created_at: string;
}

export interface ExperimentAssignmentInsert {
  id?: string;
  session_id: string;
  experiment_id: string;
  bucket: number;
  variant_key: string;
  created_at?: string;
}

// ── form_submissions ──────────────────────────────────────────────────────────

/**
 * One row per submitted and validated form — written by the
 * /api/forms/[formKey] route when formDef.action.storeSubmissions is true.
 *
 * SQL:
 *   form_submissions (
 *     id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
 *     created_at  timestamptz NOT NULL DEFAULT now(),
 *     form_key    text        NOT NULL,
 *     values      jsonb       NOT NULL,
 *     session_id  uuid        NULL REFERENCES sessions(id) ON DELETE SET NULL
 *   )
 */
export interface FormSubmissionRow {
  /** UUID primary key, generated by the database. */
  id:          string;
  /** ISO-8601 timestamp set by the database on insert. */
  created_at:  string;
  /** Registered form key, e.g. "contact" | "application" */
  form_key:    string;
  /** Validated, trimmed submission values keyed by field key. */
  values:      Record<string, string>;
  /** FK → sessions.id — nullable; absent for submissions without a platform session. */
  session_id:  string | null;
}

export interface FormSubmissionInsert {
  /** Optional: omit to let the database generate a UUID. */
  id?:         string;
  /** Optional: omit to let the database set to now(). */
  created_at?: string;
  form_key:    string;
  values:      Record<string, string>;
  session_id?: string | null;
}

// ── tenant_settings ───────────────────────────────────────────────────────────

/**
 * One row per platform tenant.
 * Stores the full TenantSettings object as JSONB.
 * Replaces the local tenant/tenants.json file store.
 *
 * SQL migration: supabase/migrations/20240101000009_create_tenant_settings.sql
 */
export interface TenantSettingsRow {
  /** Stable tenant slug (TenantSettings.tenantId), e.g. "workengine". */
  tenant_id:  string;
  /** Full TenantSettings object serialised as JSONB. */
  settings:   Record<string, unknown>;
  /** Last write timestamp. */
  updated_at: string;
}

export interface TenantSettingsInsert {
  tenant_id:   string;
  settings:    Record<string, unknown>;
  /** Optional: omit to let the database set to now(). */
  updated_at?: string;
}

// ── rules_config ──────────────────────────────────────────────────────────────

/**
 * Stores operator-authored homepage rules configurations as JSONB.
 * Replaces the local decision/rules/runtime-rules.json file.
 *
 * SQL migration: supabase/migrations/20240101000010_create_rules_config.sql
 */
export interface RulesConfigRow {
  /** Logical config name — currently always "homepage". */
  key:        string;
  /** Full StoredRulesConfig object serialised as JSONB. */
  config:     Record<string, unknown>;
  /** Last write timestamp. */
  updated_at: string;
}

export interface RulesConfigInsert {
  key:         string;
  config:      Record<string, unknown>;
  /** Optional: omit to let the database set to now(). */
  updated_at?: string;
}

// ── pages ─────────────────────────────────────────────────────────────────────

/**
 * One row per admin-editable page.
 * Stores the full EditablePage object as JSONB.
 * Replaces the local page-store/data/pages.json file.
 *
 * SQL migration: supabase/migrations/20240101000011_create_pages.sql
 */
export interface PageRow {
  /** Stable page identifier (CMS _id or admin-generated UUID). */
  id:         string;
  /** Owning tenant slug, e.g. "workengine". */
  tenant_id:  string;
  /** URL slug without leading slash, e.g. "about-us". */
  slug:       string;
  /** Full EditablePage object serialised as JSONB. */
  page:       Record<string, unknown>;
  /** Row creation timestamp. */
  created_at: string;
  /** Last write timestamp. */
  updated_at: string;
}

export interface PageInsert {
  id:          string;
  tenant_id:   string;
  slug:        string;
  page:        Record<string, unknown>;
  /** Optional: omit to let the database set to now(). */
  created_at?: string;
  /** Optional: omit to let the database set to now(). */
  updated_at?: string;
}

// ── tenant_domains ────────────────────────────────────────────────────────────

/**
 * Status of a custom domain registration.
 *
 *   pending — domain added; DNS / Vercel verification not yet confirmed.
 *   active  — domain is verified and fully operational.
 *   error   — domain verification failed or was rejected by Vercel.
 */
export type DomainStatus = "pending" | "active" | "error";

/**
 * One row per custom domain registered for a tenant.
 *
 * SQL migration: supabase/migrations/20240101000012_create_tenant_domains.sql
 */
export interface TenantDomainRow {
  /** UUID primary key. */
  id:                  string;
  /** Owning tenant slug, e.g. "workengine". */
  tenant_id:           string;
  /** Normalised hostname without protocol or trailing slash, e.g. "acme.com". */
  hostname:            string;
  /** True when this is the tenant's primary domain. */
  is_primary:          boolean;
  /** Verification and routing status. */
  status:              DomainStatus;
  /** Vercel domain ID returned by the Domains API, null when not using Vercel. */
  vercel_domain_id:    string | null;
  /** Vercel DNS verification records (CNAME / TXT) as returned by the API. */
  vercel_verification: Record<string, unknown> | null;
  /** Row creation timestamp. */
  created_at:          string;
  /** Last write timestamp. */
  updated_at:          string;
}

export interface TenantDomainInsert {
  /** Optional: omit to let the database generate a UUID. */
  id?:                  string;
  tenant_id:            string;
  hostname:             string;
  is_primary?:          boolean;
  /** Defaults to "pending" at the database level. */
  status?:              DomainStatus;
  vercel_domain_id?:    string | null;
  vercel_verification?: Record<string, unknown> | null;
  created_at?:          string;
  updated_at?:          string;
}

// ── Database schema (Supabase client generic) ─────────────────────────────────

/**
 * Top-level database schema type consumed by `createClient<Database>()`.
 * The `public` schema matches Supabase's default schema name.
 */
export interface Database {
  public: {
    Tables: {
      sessions: {
        Row: SessionRow;
        Insert: SessionInsert;
        Update: Partial<SessionInsert>;
      };
      served_variants: {
        Row: ServedVariantRow;
        Insert: ServedVariantInsert;
        Update: Partial<ServedVariantInsert>;
      };
      events: {
        Row: EventRow;
        Insert: EventInsert;
        Update: Partial<EventInsert>;
      };
      experiments: {
        Row: ExperimentRow;
        Insert: ExperimentInsert;
        Update: Partial<ExperimentInsert>;
      };
      experiment_assignments: {
        Row: ExperimentAssignmentRow;
        Insert: ExperimentAssignmentInsert;
        Update: Partial<ExperimentAssignmentInsert>;
      };
      ai_decision_logs: {
        Row: AiDecisionLogRow;
        Insert: AiDecisionLogInsert;
        Update: Partial<AiDecisionLogInsert>;
      };
      form_submissions: {
        Row:    FormSubmissionRow;
        Insert: FormSubmissionInsert;
        Update: Partial<FormSubmissionInsert>;
      };
      tenant_settings: {
        Row:    TenantSettingsRow;
        Insert: TenantSettingsInsert;
        Update: Partial<TenantSettingsInsert>;
      };
      rules_config: {
        Row:    RulesConfigRow;
        Insert: RulesConfigInsert;
        Update: Partial<RulesConfigInsert>;
      };
      pages: {
        Row:    PageRow;
        Insert: PageInsert;
        Update: Partial<PageInsert>;
      };
      tenant_domains: {
        Row:    TenantDomainRow;
        Insert: TenantDomainInsert;
        Update: Partial<TenantDomainInsert>;
      };
    };
  };
}
