/**
 * Tenant Theme — Types, Presets, and CSS Variable Generator
 *
 * This file is the bridge between the design system and tenant configuration.
 *
 * ─── What lives here ─────────────────────────────────────────────────────────
 *
 *   TenantTheme          The shape every tenant theme must satisfy.
 *   RADIUS_PRESETS       Three personality presets — sharp, balanced, soft.
 *   tenantThemeToCSS()   Converts a TenantTheme to inline CSS custom property
 *                        declarations that override the :root defaults from
 *                        theme.css without touching any component code.
 *
 * ─── How it plugs into the design system ────────────────────────────────────
 *
 *   theme.css defines the base :root semantic vars (--primary, --bg, --text, …)
 *   that all components consume. The CSS generated by tenantThemeToCSS() uses
 *   the exact same variable names, so injecting it as an inline <style> block
 *   in the root layout overrides those defaults at the :root level — zero
 *   component changes needed.
 *
 *   The full palette (brand.50–950, neutral.0–950) remains unchanged in the
 *   @theme layer — TenantTheme only overrides the semantic alias variables,
 *   not the raw palette.
 *
 * ─── What TenantTheme does NOT control ──────────────────────────────────────
 *
 *   • The raw palette tokens (--color-brand-*, --color-neutral-*) — these are
 *     part of the Tailwind @theme layer and are compile-time constants.
 *   • Typography scale, spacing scale — shared across all tenants.
 *   • Dark mode overrides — tenants can add a `dark` sub-theme later if needed.
 *   • Component variants, layout structure — shared via the design system.
 *
 * ─── Adding a second tenant ──────────────────────────────────────────────────
 *
 *   Create tenant/<slug>-theme.ts satisfying TenantTheme, set the fields, and
 *   reference it from the tenant config. No other files change.
 */

import { brand, neutral } from "../tokens/colors";
import { radii } from "../tokens/radii";
import type { RadiusKey } from "../tokens/radii";
import { fontFamily } from "../tokens/typography";
import { shadows } from "../tokens/shadow";
import { isLight, lighten, mix, contrastRatio, readableText } from "@/lib/color";
import {
  type BlockStyleProfile,
  DEFAULT_BLOCK_STYLE_PROFILE,
  blockStyleProfileToVars,
} from "./block-style-profile";
import {
  isFeaturedFamilyKey,
  familyTypographyToVars,
  familyStructuralToVars,
} from "./theme-families.config";

// ── Brand color surface ───────────────────────────────────────────────────────

export interface TenantBrandColors {
  /** --primary: main interactive colour — button bg, active link, badge fill */
  primary: string;
  /** --primary-hover: :hover / :focus-visible state of primary elements */
  primaryHover: string;
  /** --primary-active: :active / pressed state of primary elements */
  primaryActive: string;
  /** --primary-subtle: lightly tinted background behind primary elements */
  primarySubtle: string;
  /** --primary-text: text on a primary-coloured background (usually white) */
  primaryText: string;
  /** --ring: colour of the keyboard focus ring */
  ring: string;
  /** --text-brand: brand-coloured inline text (links, callouts) */
  textBrand: string;
}

// ── Text color surface ────────────────────────────────────────────────────────

export interface TenantTextColors {
  /** --text: default body text colour */
  text: string;
  /** --text-muted: secondary / descriptive text */
  textMuted: string;
  /** --text-subtle: placeholder text, disabled states, timestamps */
  textSubtle: string;
  /** --text-inverse: text on dark / coloured backgrounds */
  textInverse: string;
}

// ── Background / surface color surface ───────────────────────────────────────

export interface TenantBackgroundColors {
  /** --bg: default page background */
  bg: string;
  /** --bg-subtle: recessed areas — sidebars, alternate rows, code blocks */
  bgSubtle: string;
  /** --bg-inverse: dark background for inverse sections */
  bgInverse: string;
}

// ── Border color surface ──────────────────────────────────────────────────────

export interface TenantBorderColors {
  /** --border: default dividers and input borders */
  border: string;
  /** --border-strong: stronger dividers, active input borders */
  borderStrong: string;
}

// ── Radius personality ────────────────────────────────────────────────────────
//
// Rather than exposing every radius token, tenants pick a personality.
// The RADIUS_PRESETS map translates each personality into component-level
// CSS var values injected alongside the colour vars.

export type RadiusPersonality = "sharp" | "balanced" | "soft";

export interface TenantRadiusValues {
  interactive: string; // --radius-interactive
  card: string;        // --radius-card
  popover: string;     // --radius-popover
}

export const RADIUS_PRESETS: Record<RadiusPersonality, TenantRadiusValues> = {
  sharp: {
    interactive: radii.xs,   //  2px
    card:        radii.sm,   //  4px
    popover:     radii.xs,   //  2px
  },
  balanced: {
    interactive: radii.md,   //  8px
    card:        radii.xl,   // 16px
    popover:     radii.lg,   // 12px
  },
  soft: {
    interactive: radii.lg,       // 12px
    card:        radii["2xl"],   // 24px
    popover:     radii.xl,       // 16px
  },
} as const satisfies Record<RadiusPersonality, Record<string, (typeof radii)[RadiusKey]>>;

// ── Typography overrides ──────────────────────────────────────────────────────

export interface ThemeTypography {
  /**
   * Body / UI sans-serif font stack. Overrides --font-sans.
   * Use a full CSS font-family stack, e.g. "'DM Sans', system-ui, sans-serif".
   * When set to a supported Google Font name, the font-redirect layer in
   * layout.tsx automatically connects --font-sans to the pre-loaded @font-face.
   */
  fontSans?: string;
  /**
   * Serif font stack. Overrides --font-serif.
   * Use a full CSS font-family stack, e.g. "'Playfair Display', Georgia, serif".
   * When set to a supported Google Font name, the font-redirect layer in
   * layout.tsx automatically connects --font-serif to the pre-loaded @font-face.
   */
  fontSerif?: string;
  /**
   * Monospace font stack. Overrides --font-mono.
   * Use a full CSS font-family stack, e.g. "'JetBrains Mono', monospace".
   * When set to a supported Google Font name, the font-redirect layer in
   * layout.tsx automatically connects --font-mono to the pre-loaded @font-face.
   */
  fontMono?: string;
  /** Heading font-family stack. Overrides --font-heading. */
  headingFont?: string;
  /** Heading font-weight. Overrides --font-heading-weight. Defaults to "700". */
  headingWeight?: string;
  /** Sub-heading font-weight. Overrides --font-subheading-weight. Defaults to "600". */
  subheadingWeight?: string;
}

// ── Button component tokens ───────────────────────────────────────────────────
//
// A dedicated token group for button surfaces.  Using these instead of
// --primary / --primary-hover directly means button style can diverge from
// the global brand accent colour when needed.
//
// All fields are optional — absent values derive from the brand color surface
// in tenantThemeToCSS().

export interface ThemeButtonTokens {
  /** --btn-bg: default button background. Defaults to --primary. */
  bg?: string;
  /** --btn-text: text on the button background. Defaults to --primary-text. */
  text?: string;
  /** --btn-hover-bg: :hover / :focus-visible background. */
  hoverBg?: string;
  /** --btn-active-bg: :active / pressed background. */
  activeBg?: string;
  /** --btn-ring: focus ring colour. Defaults to --ring. */
  ring?: string;
  /** --btn-radius: border-radius. Defaults to --radius-interactive. */
  radius?: string;
  /** --btn-shadow: optional lift shadow. Defaults to shadow-sm. */
  shadow?: string;
  /** --btn-font-weight: label font-weight. Defaults to "600". */
  fontWeight?: string;
}

// ── Motion tokens ─────────────────────────────────────────────────────────────
//
// Transition timing and easing for the tenant's interaction feel.
// Optional — platform defaults (150ms ease-in-out) apply when absent.

export interface ThemeMotionTokens {
  /** --transition-fast: micro-interaction speed. Default "100ms ease-in-out". */
  transitionFast?: string;
  /** --transition-base: default speed. Default "150ms ease-in-out". */
  transitionBase?: string;
  /** --transition-slow: panel/overlay speed. Default "300ms ease-in-out". */
  transitionSlow?: string;
  /** --ease-default: standard easing. */
  easingDefault?: string;
  /** --ease-spring: bouncy easing for expressive interactions. */
  easingSpring?: string;
}

// ── Component-level style tokens ──────────────────────────────────────────────
//
// Optional per-tenant overrides for common component surface patterns.
// When absent, values are derived from the TenantTheme color fields.

export interface ThemeComponentStyles {
  // ── Section backgrounds ─────────────────────────────────────────────────────
  /** Hero section background. Defaults to neutral-950. */
  heroBg?: string;
  /** CTA section/block background. Defaults to --primary. */
  ctaBg?: string;
  /** Body text colour on a CTA background. Defaults to --primary-subtle. */
  ctaBodyText?: string;
  /** Subtle section background (proof, features, FAQ). */
  subtleSectionBg?: string;
  /** Border on subtle sections. */
  subtleSectionBorder?: string;

  // ── Card tokens ─────────────────────────────────────────────────────────────
  /** Card/panel background. Defaults to #ffffff. */
  cardBg?: string;
  /** Card border colour. */
  cardBorderColor?: string;
  /** Card border-radius. Defaults to --radius-card. */
  cardRadius?: string;
  /** Card box-shadow. Defaults to shadow-sm. */
  cardShadow?: string;
  /** Pull-quote / accent colour. Defaults to --primary. */
  quoteColor?: string;

  // ── Hero expansion ──────────────────────────────────────────────────────────
  /** Glow decoration colour. Defaults to --primary. */
  heroGlowColor?: string;
  /** Opacity of the hero glow (0–1 string). Defaults to "0.2". */
  heroGlowOpacity?: string;
  /** Hero headline text colour. Defaults to --text-inverse. */
  heroTitleColor?: string;
  /** Hero subheadline colour. Defaults to --text-subtle. */
  heroSubtitleColor?: string;

  // ── Proof / testimonial tokens ──────────────────────────────────────────────
  /** Proof section background. */
  proofBg?: string;
  /** Proof section border. Defaults to "transparent". */
  proofBorder?: string;
  /** Proof card background. Defaults to --card-bg. */
  proofCardBg?: string;
  /** Proof card border. */
  proofCardBorder?: string;
  /** Proof card radius. */
  proofCardRadius?: string;
  /** Proof card shadow. */
  proofCardShadow?: string;
  /** Proof quote mark colour. */
  proofQuoteColor?: string;

  // ── Feature-grid tokens ─────────────────────────────────────────────────────
  /** Feature-grid section background. */
  featureGridBg?: string;
  /** Feature-grid section border. */
  featureGridBorder?: string;
  /** Feature-grid card background. */
  featureGridCardBg?: string;
  /** Feature-grid card border. */
  featureGridCardBorder?: string;
  /** Feature-grid card radius. */
  featureGridCardRadius?: string;
  /** Feature-grid card shadow. */
  featureGridCardShadow?: string;
  /** Feature-grid icon container background (icons-left variant). */
  featureGridIconBg?: string;

  // ── Header tokens ────────────────────────────────────────────────────────────
  /**
   * Header background at the top of the page (before scrolling).
   * Accepts any CSS color including semi-transparent values like
   * `rgba(255,255,255,0)` for a fully transparent overlay header.
   * Defaults to `rgba(255,255,255,0.95)` (the platform look).
   */
  headerBg?: string;
  /**
   * Header background after the user scrolls past 24 px.
   * Defaults to `rgba(255,255,255,0.95)` to keep the header readable.
   */
  headerBgScrolled?: string;
  /** Header text / icon foreground colour. Defaults to --text. */
  headerFg?: string;
  /** Header bottom-border colour. Defaults to --border. */
  headerBorder?: string;

  // ── Footer tokens ─────────────────────────────────────────────────────────────
  /** Footer section background. Defaults to --bg-subtle. */
  footerBg?: string;
  /** Footer text / icon foreground colour. Defaults to --text-muted. */
  footerFg?: string;
  /** Footer top-border colour. Defaults to --border. */
  footerBorder?: string;

  // ── Navigation / dropdown tokens ──────────────────────────────────────────────
  //
  // These break the purple-leak chain for nav components.  Without them,
  // dropdowns fall back to hardcoded bg-white / text-neutral-700 which produces
  // a jarring white panel on dark-background presets (dark-contrast etc.).
  // Each value is emitted as a concrete hex by tenantThemeToCSS() so components
  // never fall through to the :root indigo defaults.

  /** Dropdown panel background. Defaults to cardBg (white on light, dark on dark themes). */
  navDropdownBg?: string;
  /** Dropdown panel border colour. Defaults to --border. */
  navDropdownBorder?: string;
  /** Dropdown child-link text colour. Defaults to --text-muted. */
  navDropdownText?: string;
  /** Dropdown child-link :hover background. Defaults to --primary-subtle. */
  navDropdownLinkHoverBg?: string;
  /** Dropdown child-link :hover text. Defaults to --text-brand (the preset-correct value). */
  navDropdownLinkHoverText?: string;

  // ── Navigation typography tokens ───────────────────────────────────────────────
  //
  // Component-level typography overrides for the navigation bar.  These sit
  // ABOVE the theme family's base typography and BELOW any admin token override.
  //
  // When absent (the common case), nav components apply their own Tailwind class
  // defaults (text-sm / font-medium etc.) via per-variant fallback values in the
  // var() call — no default is emitted by buildThemeVarsArray() unless the preset
  // explicitly sets these fields.

  /**
   * Font size for top-level header nav links.
   * CSS value: "0.875rem", "1rem", "0.9375rem", etc.
   * Consumed as --nav-link-size; absent → per-variant Tailwind class applies.
   */
  navLinkSize?: string;

  /**
   * Font weight for top-level header nav links.
   * CSS value: "400", "500", "600", "700".
   * Consumed as --nav-link-weight; absent → per-variant fallback (500 or 600).
   */
  navLinkWeight?: string;

  /**
   * Letter-spacing for top-level header nav links.
   * CSS value: "normal", "0.025em", "0.05em", "-0.01em", etc.
   * Consumed as --nav-link-tracking; absent → per-variant fallback.
   */
  navLinkTracking?: string;

  /**
   * Font size for dropdown / submenu child links.
   * CSS value: "0.875rem", "0.8125rem", etc.
   * Consumed as --nav-dropdown-item-size; absent → 0.875rem (text-sm).
   */
  navDropdownItemSize?: string;

  /**
   * Font size for footer navigation links.
   * CSS value: "0.875rem", "0.8125rem", etc.
   * Consumed as --footer-nav-size; absent → 0.875rem (text-sm).
   */
  footerNavSize?: string;
}

// ── Brand / identity metadata ─────────────────────────────────────────────────

export interface TenantBrandMeta {
  /** Human-readable display name. */
  name: string;
  /** One-sentence positioning statement. */
  tagline?: string;
  /** Path to the tenant's logo, relative to /public. */
  logoPath?: string;
  /** Path to the favicon, relative to /public. */
  faviconPath?: string;
}

// ── Root TenantTheme ──────────────────────────────────────────────────────────

/**
 * Complete visual identity and brand configuration for a single tenant.
 *
 * Every field maps to one or more CSS custom properties that override the
 * design-system :root defaults. See tenantThemeToCSS() for the exact mapping.
 */
export interface TenantTheme {
  colors: {
    brand:      TenantBrandColors;
    text:       TenantTextColors;
    background: TenantBackgroundColors;
    border:     TenantBorderColors;
  };
  /** Corner radius personality. See RADIUS_PRESETS. */
  radius: RadiusPersonality;
  /** Brand identity metadata. */
  meta: TenantBrandMeta;
  /** Optional typography overrides. */
  typography?: ThemeTypography;
  /** Optional button component token overrides. */
  button?: ThemeButtonTokens;
  /** Optional motion / animation token overrides. */
  motion?: ThemeMotionTokens;
  /** Optional component-level style overrides. */
  componentStyles?: ThemeComponentStyles;
  /**
   * Block style profile — controls the visual character of block layouts beyond
   * raw colour / typography tokens.  When omitted the DEFAULT_BLOCK_STYLE_PROFILE
   * applies (marketing-default character: standard tracking, rounded media, 1px dividers).
   *
   * See design-system/theme/block-style-profile.ts for available profiles and
   * the full BlockStyleProfile interface.
   */
  blockStyle?: BlockStyleProfile;

  /**
   * Optional featured theme family key.
   *
   * When set to a recognised FeaturedFamilyKey value, the family's canonical
   * typography configuration (heading/body fonts, weights, line-height, and
   * fluid size scale) is appended to the CSS var output **after** all other
   * declarations.  This makes the family layer the highest-priority typography
   * override — presets no longer need to inline their own font definitions.
   *
   * See design-system/theme/theme-families.config.ts for the registry and the
   * full list of CSS variables emitted.
   *
   * Accepted values (as of writing):
   *   "editorial-classic" | "corporate-clean" | "bold-marketing"
   *   "portfolio-showcase" | "premium-luxury"
   */
  featuredFamilyKey?: string;
}

// ── CSS variable generator ────────────────────────────────────────────────────

/**
 * Builds the flat array of [cssVarName, value] pairs that represents the full
 * token set for a TenantTheme.  Shared by tenantThemeToCSS() and
 * tenantThemeToVarsRecord() so both outputs derive from a single source.
 *
 * @internal — not exported; use the two public helpers below.
 */
function buildThemeVarsArray(theme: TenantTheme): [string, string][] {
  const { colors, radius, typography, button, motion, componentStyles: cs, blockStyle } = theme;
  const r = RADIUS_PRESETS[radius];

  // ── Derived defaults ────────────────────────────────────────────────────────

  // Section / card
  const heroBg             = cs?.heroBg              ?? neutral[950];
  const ctaBg              = cs?.ctaBg               ?? colors.brand.primary;
  const ctaBodyText        = cs?.ctaBodyText          ?? colors.brand.primarySubtle;
  const subtleBg           = cs?.subtleSectionBg     ?? colors.background.bgSubtle;
  const subtleBorder       = cs?.subtleSectionBorder  ?? colors.border.border;
  const rawCardBg          = cs?.cardBg              ?? "#ffffff";
  const rawCardBorder      = cs?.cardBorderColor     ?? colors.border.border;
  // Card-on-dark separation: on a dark theme a card that is nearly the same
  // colour as the (subtle) section it sits on does not read as elevated (the CTA
  // card variant is the visible symptom). When the card barely separates from
  // that surface, lift it off the surface and strengthen its border so the card
  // stands out. Light themes and already-separated dark cards are untouched.
  const themeIsDark   = !isLight(colors.background.bg);
  const cardSeparation = contrastRatio(rawCardBg, subtleBg);
  const cardNeedsLift = themeIsDark && cardSeparation !== null && cardSeparation < 1.25;
  const cardBg             = cardNeedsLift ? lighten(subtleBg, 0.12)               : rawCardBg;
  const cardBorder         = cardNeedsLift ? mix(cardBg, colors.text.text, 0.24)   : rawCardBorder;
  const cardRadius         = cs?.cardRadius          ?? r.card;
  const cardShadow         = cs?.cardShadow          ?? shadows.sm;
  // Secondary-button readability: the secondary button pairs its brand-tint
  // surface (--btn-secondary-bg = primarySubtle) with brand text
  // (--btn-secondary-text = textBrand). On a light tint plus a light/amber brand
  // that pairing is light-on-light (the "Lees cases" hero button is the visible
  // symptom). Keep the brand text only while it stays legible on the tint
  // (>= 4.5:1), else flip to a readable colour. The tint surface is unchanged.
  const secBtnBg           = colors.brand.primarySubtle;
  const secBtnRatio        = contrastRatio(colors.brand.textBrand, secBtnBg);
  const secBtnText         = secBtnRatio !== null && secBtnRatio >= 4.5
    ? colors.brand.textBrand
    : readableText(secBtnBg);
  const quoteColor         = cs?.quoteColor          ?? colors.brand.primary;

  // Hero expansion
  const heroGlowColor      = cs?.heroGlowColor       ?? colors.brand.primary;
  const heroGlowOpacity    = cs?.heroGlowOpacity     ?? "0.2";
  const heroTitleColor     = cs?.heroTitleColor      ?? colors.text.textInverse;
  const heroSubtitleColor  = cs?.heroSubtitleColor   ?? colors.text.textSubtle;

  // Proof
  const proofBg            = cs?.proofBg             ?? colors.background.bg;
  const proofBorder        = cs?.proofBorder         ?? "transparent";
  const proofCardBg        = cs?.proofCardBg         ?? cardBg;
  const proofCardBorder    = cs?.proofCardBorder     ?? cardBorder;
  const proofCardRadius    = cs?.proofCardRadius     ?? cardRadius;
  const proofCardShadow    = cs?.proofCardShadow     ?? cardShadow;
  const proofQuoteColor    = cs?.proofQuoteColor     ?? quoteColor;

  // Feature-grid
  const fgBg               = cs?.featureGridBg          ?? subtleBg;
  const fgBorder           = cs?.featureGridBorder      ?? subtleBorder;
  const fgCardBg           = cs?.featureGridCardBg      ?? cardBg;
  const fgCardBorder       = cs?.featureGridCardBorder  ?? cardBorder;
  const fgCardRadius       = cs?.featureGridCardRadius  ?? cardRadius;
  const fgCardShadow       = cs?.featureGridCardShadow  ?? cardShadow;
  const fgIconBg           = cs?.featureGridIconBg      ?? subtleBg;

  // Header
  const headerDefaultBg    = "rgba(255,255,255,0.95)";
  const headerBg           = cs?.headerBg          ?? headerDefaultBg;
  const headerBgScrolled   = cs?.headerBgScrolled  ?? headerDefaultBg;
  const headerFg           = cs?.headerFg          ?? colors.text.text;
  const headerBorder       = cs?.headerBorder      ?? colors.border.border;

  // Footer
  const footerBg           = cs?.footerBg    ?? colors.background.bgSubtle;
  const footerFg           = cs?.footerFg    ?? colors.text.textMuted;
  const footerBorder       = cs?.footerBorder ?? colors.border.border;

  // Navigation — top-level link tokens
  //
  // --nav-link derives from headerFg (nav links sit against the header surface).
  // --nav-link-hover tracks textBrand (brand accent on hover — intentional).
  //
  // These are emitted as CONCRETE HEX so nav components always receive a
  // resolved colour rather than depending on the :root CSS var chain
  // `var(--header-fg, var(--text))` propagating correctly across the
  // [data-site] boundary.  The chain is correct in theory but unreliable in
  // admin preview, Storybook, and other contexts that skip [data-site].
  const navLink                     = headerFg;                           // top-level link resting text
  const navLinkHover                = colors.brand.textBrand;             // top-level link :hover text

  // Navigation / dropdown
  // navDropdownBg defaults to cardBg so light themes get white and dark themes
  // get their explicit dark card surface — no purple or white-on-dark surprises.
  const navDropdownBg               = cs?.navDropdownBg             ?? cardBg;
  const navDropdownBorder           = cs?.navDropdownBorder         ?? colors.border.border;
  const navDropdownText             = cs?.navDropdownText           ?? colors.text.textMuted;
  const navDropdownLinkHoverBg      = cs?.navDropdownLinkHoverBg    ?? colors.brand.primarySubtle;
  const navDropdownLinkHoverText    = cs?.navDropdownLinkHoverText  ?? colors.brand.textBrand;

  // Typography
  const fontSans           = typography?.fontSans        ?? null;
  const fontSerif          = typography?.fontSerif       ?? null;
  const fontMono           = typography?.fontMono        ?? null;
  const headingFont        = typography?.headingFont      ?? fontFamily.sans;
  const headingWeight      = typography?.headingWeight    ?? "700";
  const subheadingWeight   = typography?.subheadingWeight ?? "600";

  // Button
  const btnBg              = button?.bg         ?? colors.brand.primary;
  const btnText            = button?.text        ?? colors.brand.primaryText;
  const btnHoverBg         = button?.hoverBg     ?? colors.brand.primaryHover;
  const btnActiveBg        = button?.activeBg    ?? colors.brand.primaryActive;
  const btnRing            = button?.ring        ?? colors.brand.ring;
  const btnRadius          = button?.radius      ?? r.interactive;
  const btnShadow          = button?.shadow      ?? shadows.sm;
  const btnFontWeight      = button?.fontWeight  ?? "600";

  // Motion
  const easeBase           = "cubic-bezier(0.4, 0, 0.2, 1)";
  const transitionFast     = motion?.transitionFast  ?? `100ms ${easeBase}`;
  const transitionBase     = motion?.transitionBase  ?? `150ms ${easeBase}`;
  const transitionSlow     = motion?.transitionSlow  ?? `300ms ${easeBase}`;
  const easingDefault      = motion?.easingDefault   ?? easeBase;
  const easingSpring       = motion?.easingSpring    ?? "cubic-bezier(0.34, 1.56, 0.64, 1)";

  const vars: [string, string][] = [
    // ── Brand / interactive ───────────────────────────────────────────────────
    ["--primary",           colors.brand.primary],
    ["--primary-hover",     colors.brand.primaryHover],
    ["--primary-active",    colors.brand.primaryActive],
    ["--primary-subtle",    colors.brand.primarySubtle],
    ["--primary-text",      colors.brand.primaryText],
    ["--ring",              colors.brand.ring],
    ["--text-brand",        colors.brand.textBrand],

    // ── Text ─────────────────────────────────────────────────────────────────
    ["--text",              colors.text.text],
    ["--text-muted",        colors.text.textMuted],
    ["--text-subtle",       colors.text.textSubtle],
    ["--text-inverse",      colors.text.textInverse],

    // ── Foreground aliases (shadcn/ui convention) ─────────────────────────────
    //
    // Emitted alongside our native --text/* vars so any component that follows
    // the shadcn/ui naming convention ("foreground" instead of "text") also
    // receives the correct theme colour rather than falling through to the
    // browser default (purple link colour, undefined card-foreground, etc.).
    //
    // Mapping:
    //   --foreground            → body text colour  (--text)
    //   --card-foreground       → body text on cards (same as --text)
    //   --popover-foreground    → text in popovers/tooltips (same as --text)
    //   --muted-foreground      → de-emphasised text (--text-muted)
    ["--foreground",         colors.text.text],
    ["--card-foreground",    colors.text.text],
    ["--popover-foreground", colors.text.text],
    ["--muted-foreground",   colors.text.textMuted],

    // ── Backgrounds ───────────────────────────────────────────────────────────
    ["--bg",                colors.background.bg],
    ["--bg-subtle",         colors.background.bgSubtle],
    ["--bg-inverse",        colors.background.bgInverse],

    // ── Borders ───────────────────────────────────────────────────────────────
    ["--border",            colors.border.border],
    ["--border-strong",     colors.border.borderStrong],

    // ── Component radii ───────────────────────────────────────────────────────
    ["--radius-interactive", r.interactive],
    ["--radius-card",        r.card],
    ["--radius-popover",     r.popover],

    // ── Motion ────────────────────────────────────────────────────────────────
    ["--transition-fast",  transitionFast],
    ["--transition-base",  transitionBase],
    ["--transition-slow",  transitionSlow],
    ["--ease-default",     easingDefault],
    ["--ease-spring",      easingSpring],

    // ── Button ────────────────────────────────────────────────────────────────
    ["--btn-bg",           btnBg],
    ["--btn-text",         btnText],
    ["--btn-hover-bg",     btnHoverBg],
    ["--btn-active-bg",    btnActiveBg],
    ["--btn-ring",         btnRing],
    ["--btn-radius",       btnRadius],
    ["--btn-shadow",       btnShadow],
    ["--btn-font-weight",  btnFontWeight],

    // ── Section surface tokens ────────────────────────────────────────────────
    ["--section-hero-bg",        heroBg],
    ["--section-cta-bg",         ctaBg],
    ["--section-cta-body",       ctaBodyText],
    ["--section-subtle-bg",      subtleBg],
    ["--section-subtle-border",  subtleBorder],

    // ── Card tokens ───────────────────────────────────────────────────────────
    ["--card-bg",          cardBg],
    ["--card-border",      cardBorder],
    ["--card-radius",      cardRadius],
    ["--card-shadow",      cardShadow],
    ["--card-quote",       quoteColor],

    // ── Hero component tokens ─────────────────────────────────────────────────
    ["--hero-bg",              heroBg],
    ["--hero-glow-color",      heroGlowColor],
    ["--hero-glow-opacity",    heroGlowOpacity],
    ["--hero-title-color",     heroTitleColor],
    ["--hero-subtitle-color",  heroSubtitleColor],

    // ── Proof / testimonial tokens ────────────────────────────────────────────
    ["--proof-bg",           proofBg],
    ["--proof-border",       proofBorder],
    ["--proof-card-bg",      proofCardBg],
    ["--proof-card-border",  proofCardBorder],
    ["--proof-card-radius",  proofCardRadius],
    ["--proof-card-shadow",  proofCardShadow],
    ["--proof-quote-color",  proofQuoteColor],

    // ── Feature-grid tokens ───────────────────────────────────────────────────
    ["--feature-grid-bg",           fgBg],
    ["--feature-grid-border",       fgBorder],
    ["--feature-grid-card-bg",      fgCardBg],
    ["--feature-grid-card-border",  fgCardBorder],
    ["--feature-grid-card-radius",  fgCardRadius],
    ["--feature-grid-card-shadow",  fgCardShadow],
    ["--feature-grid-icon-bg",      fgIconBg],

    // ── Form component tokens ─────────────────────────────────────────────────
    //
    // Emitted as CONCRETE values at [data-site] so the form surface follows the
    // preset. In theme.css these are :root indirections (--form-input-text:
    // var(--text) etc.); a :root indirection is substituted against the :root
    // values and inherits down, so re-pinning --text at [data-site] does NOT
    // reach --form-input-text unless it too is re-pinned here. Without this,
    // dark presets rendered light form text on a light :root default surface
    // (light-on-light) and vice-versa. Same rationale as the nav/badge tokens.
    ["--form-bg",                subtleBg],
    ["--form-border",            subtleBorder],
    ["--form-input-bg",          cardBg],
    ["--form-input-border",      colors.border.borderStrong],
    ["--form-input-radius",      r.interactive],
    ["--form-input-text",        colors.text.text],
    ["--form-input-placeholder", colors.text.textSubtle],
    ["--form-input-focus-ring",  colors.brand.ring],
    ["--form-label-color",       colors.text.text],
    ["--form-help-color",        colors.text.textMuted],

    // ── Typography component tokens ───────────────────────────────────────────
    //
    // --font-sans and --font-serif are emitted only when the preset explicitly
    // specifies them (non-null).  When absent the theme.css baseline applies,
    // keeping the existing system-ui / font-family.sans defaults for all other
    // presets unchanged.
    ...(fontSans  ? [["--font-sans",  fontSans]  as [string, string]] : []),
    ...(fontSerif ? [["--font-serif", fontSerif] as [string, string]] : []),
    ...(fontMono  ? [["--font-mono",  fontMono]  as [string, string]] : []),
    // Font ROLE tokens (--font-body/-ui/-code) are :root indirections onto the
    // base families (var(--font-sans) / var(--font-mono)). When a preset pins a
    // base family at [data-site], the :root role indirection still resolves to
    // the :root base family and never sees the override — so re-pin the roles
    // here too whenever the matching base family is set. When a family key is set
    // its familyTypographyToVars() layer re-emits --font-body later and wins.
    ...(fontSans  ? [["--font-body", fontSans] as [string, string], ["--font-ui", fontSans] as [string, string]] : []),
    ...(fontMono  ? [["--font-code", fontMono] as [string, string]] : []),
    ["--font-heading",           headingFont],
    ["--font-heading-weight",    headingWeight],
    ["--font-subheading-weight", subheadingWeight],

    // ── Header component tokens ───────────────────────────────────────────────
    ["--header-bg",          headerBg],
    ["--header-bg-scrolled", headerBgScrolled],
    ["--header-fg",          headerFg],
    ["--header-border",      headerBorder],

    // ── Footer component tokens ───────────────────────────────────────────────
    ["--footer-bg",     footerBg],
    ["--footer-fg",     footerFg],
    ["--footer-border", footerBorder],

    // ── Navigation component tokens ───────────────────────────────────────────
    //
    // All seven nav tokens emitted as concrete hex values so components NEVER
    // fall back to the :root CSS var chains that could resolve to purple.
    //
    // --nav-link / --nav-link-hover: top-level links in the header bar.
    //   Concrete emission is the critical fix — the :root chain
    //   `var(--header-fg, var(--text))` works in theory but is unreliable in
    //   admin preview and Storybook where [data-site] is not in scope.
    //
    // --nav-dropdown-*: dropdown panel surface + child link colours.
    ["--nav-link",                      navLink],
    ["--nav-link-hover",                navLinkHover],
    ["--nav-dropdown-bg",               navDropdownBg],
    ["--nav-dropdown-border",           navDropdownBorder],
    ["--nav-dropdown-text",             navDropdownText],
    ["--nav-dropdown-link-hover-bg",    navDropdownLinkHoverBg],
    ["--nav-dropdown-link-hover-text",  navDropdownLinkHoverText],

    // ── Navigation typography tokens ─────────────────────────────────────────
    //
    // Emitted ONLY when the preset explicitly sets these fields.  When absent,
    // nav components apply their own Tailwind class defaults via per-variant
    // fallback values in their var() calls.  This lets NavContent use its
    // own font-semibold (600) fallback while NavFlyout/Mega/Grid use 500,
    // without needing a per-variant config in the preset.
    ...(cs?.navLinkSize         ? [["--nav-link-size",          cs.navLinkSize]         as [string, string]] : []),
    ...(cs?.navLinkWeight       ? [["--nav-link-weight",        cs.navLinkWeight]       as [string, string]] : []),
    ...(cs?.navLinkTracking     ? [["--nav-link-tracking",      cs.navLinkTracking]     as [string, string]] : []),
    ...(cs?.navDropdownItemSize ? [["--nav-dropdown-item-size", cs.navDropdownItemSize] as [string, string]] : []),
    ...(cs?.footerNavSize       ? [["--footer-nav-size",        cs.footerNavSize]       as [string, string]] : []),

    // ── Badge component tokens ────────────────────────────────────────────────
    //
    // Concrete values break the badge purple-leak chain:
    //   Badge primary: --badge-primary-bg (bg) + --badge-primary-text (text)
    // These default to primarySubtle / textBrand but are emitted as hex so the
    // :root chain-fallback to brand-500 never activates inside [data-site].
    ["--badge-primary-bg",   colors.brand.primarySubtle],
    ["--badge-primary-text", colors.brand.textBrand],

    // ── Secondary button tokens ───────────────────────────────────────────────
    //
    // Same rationale as badge: concrete hex values prevent the :root purple
    // fallback from showing on secondary buttons in any preset.
    ["--btn-secondary-bg",       secBtnBg],
    ["--btn-secondary-text",     secBtnText],
    ["--btn-secondary-hover-bg", secBtnBg],

    // Outline / ghost buttons are context-adaptive: they inherit currentColor
    // (the surrounding section's text colour) rather than a fixed preset colour,
    // so a single definition works on a light page and on a dark hero/cta alike.
    // See components/ui/Button.tsx (--btn-outline-* / --btn-ghost-* default to
    // currentColor) — no concrete colour is emitted here on purpose.

    // ── Block style profile ───────────────────────────────────────────────────
    //
    // Controls visual character beyond colour/font: heading treatment, media
    // framing, logo filter, section dividers, card density/spacing.
    // Falls back to DEFAULT_BLOCK_STYLE_PROFILE when the theme omits blockStyle.
    ...blockStyleProfileToVars(blockStyle ?? DEFAULT_BLOCK_STYLE_PROFILE),

    // ── Featured family typography override ───────────────────────────────────
    //
    // Appended LAST so the family layer always wins over preset-level typography.
    // ── Family typography layer ───────────────────────────────────────────────
    // Emits: --font-heading, --font-body, --font-sans, --font-serif (optional),
    //        --font-heading-weight, --font-subheading-weight, --font-body-weight,
    //        --font-line-height, --block-heading-tracking (overrides BlockStyleProfile),
    //        --font-size-h1…h3, --font-size-body, --font-size-small, --mc-family-key.
    ...(theme.featuredFamilyKey && isFeaturedFamilyKey(theme.featuredFamilyKey)
      ? familyTypographyToVars(theme.featuredFamilyKey)
      : []),

    // ── Family structural layer ───────────────────────────────────────────────
    // Emits: --btn-radius, --btn-font-weight, --btn-text-transform,
    //        --card-radius (overrides preset), --block-heading-transform,
    //        --family-hero-layout.
    // Appended last so the family layer wins over both the preset and
    // the BlockStyleProfile for all structural tokens.
    ...(theme.featuredFamilyKey && isFeaturedFamilyKey(theme.featuredFamilyKey)
      ? familyStructuralToVars(theme.featuredFamilyKey)
      : []),
  ];

  return vars;
}

/**
 * Converts a TenantTheme to a block of CSS custom property declarations.
 *
 * Returns the inner content of a :root { } rule — each line is indented
 * with two spaces and ends with a semicolon.
 */
export function tenantThemeToCSS(theme: TenantTheme): string {
  return buildThemeVarsArray(theme)
    .map(([key, val]) => `  ${key}: ${val};`)
    .join("\n") + "\n";
}

/**
 * Converts a TenantTheme to a flat Record of CSS custom property name → value.
 *
 * Useful when CSS vars need to be merged into an existing Record (e.g. the
 * theme resolver's var delta map) without going through CSS string parsing.
 *
 * @example
 * const vars = tenantThemeToVarsRecord(THEME_PRESETS["corporate-blue"]);
 * // { "--primary": "#1d4ed8", "--bg": "#f8fafc", ... }
 */
export function tenantThemeToVarsRecord(theme: TenantTheme): Record<string, string> {
  return Object.fromEntries(buildThemeVarsArray(theme));
}

// ── Re-export palette references ─────────────────────────────────────────────
export { brand, neutral };
