/**
 * Tenant Theme — Types, Presets, and CSS Variable Generator
 *
 * This file is the bridge between the design system and tenant configuration.
 *
 * ─── What lives here ─────────────────────────────────────────────────────────
 *
 *   TenantTheme          The shape every tenant theme must satisfy.
 *   RADIUS_PRESETS       Three personality presets — sharp, balanced, soft.
 *   tenantThemeToCSS()   Converts a TenantTheme to inline CSS custom property
 *                        declarations that override the :root defaults from
 *                        theme.css without touching any component code.
 *
 * ─── How it plugs into the design system ────────────────────────────────────
 *
 *   theme.css defines the base :root semantic vars (--primary, --bg, --text, …)
 *   that all components consume. The CSS generated by tenantThemeToCSS() uses
 *   the exact same variable names, so injecting it as an inline <style> block
 *   in the root layout overrides those defaults at the :root level — zero
 *   component changes needed.
 *
 *   The full palette (brand.50–950, neutral.0–950) remains unchanged in the
 *   @theme layer — TenantTheme only overrides the semantic alias variables,
 *   not the raw palette.
 *
 * ─── What TenantTheme does NOT control ──────────────────────────────────────
 *
 *   • The raw palette tokens (--color-brand-*, --color-neutral-*) — these are
 *     part of the Tailwind @theme layer and are compile-time constants.
 *   • Typography scale, spacing scale — shared across all tenants.
 *   • Dark mode overrides — tenants can add a `dark` sub-theme later if needed.
 *   • Component variants, layout structure — shared via the design system.
 *
 * ─── Adding a second tenant ──────────────────────────────────────────────────
 *
 *   Create tenant/<slug>-theme.ts satisfying TenantTheme, set the fields, and
 *   reference it from the tenant config. No other files change.
 */

import { brand, neutral } from "../tokens/colors";
import { radii } from "../tokens/radii";
import type { RadiusKey } from "../tokens/radii";
import { fontFamily } from "../tokens/typography";
import { shadows } from "../tokens/shadow";

// ── Brand color surface ───────────────────────────────────────────────────────

export interface TenantBrandColors {
  /** --primary: main interactive colour — button bg, active link, badge fill */
  primary: string;
  /** --primary-hover: :hover / :focus-visible state of primary elements */
  primaryHover: string;
  /** --primary-active: :active / pressed state of primary elements */
  primaryActive: string;
  /** --primary-subtle: lightly tinted background behind primary elements */
  primarySubtle: string;
  /** --primary-text: text on a primary-coloured background (usually white) */
  primaryText: string;
  /** --ring: colour of the keyboard focus ring */
  ring: string;
  /** --text-brand: brand-coloured inline text (links, callouts) */
  textBrand: string;
}

// ── Text color surface ────────────────────────────────────────────────────────

export interface TenantTextColors {
  /** --text: default body text colour */
  text: string;
  /** --text-muted: secondary / descriptive text */
  textMuted: string;
  /** --text-subtle: placeholder text, disabled states, timestamps */
  textSubtle: string;
  /** --text-inverse: text on dark / coloured backgrounds */
  textInverse: string;
}

// ── Background / surface color surface ───────────────────────────────────────

export interface TenantBackgroundColors {
  /** --bg: default page background */
  bg: string;
  /** --bg-subtle: recessed areas — sidebars, alternate rows, code blocks */
  bgSubtle: string;
  /** --bg-inverse: dark background for inverse sections */
  bgInverse: string;
}

// ── Border color surface ──────────────────────────────────────────────────────

export interface TenantBorderColors {
  /** --border: default dividers and input borders */
  border: string;
  /** --border-strong: stronger dividers, active input borders */
  borderStrong: string;
}

// ── Radius personality ────────────────────────────────────────────────────────
//
// Rather than exposing every radius token, tenants pick a personality.
// The RADIUS_PRESETS map translates each personality into component-level
// CSS var values injected alongside the colour vars.

export type RadiusPersonality = "sharp" | "balanced" | "soft";

export interface TenantRadiusValues {
  interactive: string; // --radius-interactive
  card: string;        // --radius-card
  popover: string;     // --radius-popover
}

export const RADIUS_PRESETS: Record<RadiusPersonality, TenantRadiusValues> = {
  sharp: {
    interactive: radii.xs,   //  2px
    card:        radii.sm,   //  4px
    popover:     radii.xs,   //  2px
  },
  balanced: {
    interactive: radii.md,   //  8px
    card:        radii.xl,   // 16px
    popover:     radii.lg,   // 12px
  },
  soft: {
    interactive: radii.lg,       // 12px
    card:        radii["2xl"],   // 24px
    popover:     radii.xl,       // 16px
  },
} as const satisfies Record<RadiusPersonality, Record<string, (typeof radii)[RadiusKey]>>;

// ── Typography overrides ──────────────────────────────────────────────────────

export interface ThemeTypography {
  /** Heading font-family stack. Overrides --font-heading. */
  headingFont?: string;
  /** Heading font-weight. Overrides --font-heading-weight. Defaults to "700". */
  headingWeight?: string;
  /** Sub-heading font-weight. Overrides --font-subheading-weight. Defaults to "600". */
  subheadingWeight?: string;
}

// ── Button component tokens ───────────────────────────────────────────────────
//
// A dedicated token group for button surfaces.  Using these instead of
// --primary / --primary-hover directly means button style can diverge from
// the global brand accent colour when needed.
//
// All fields are optional — absent values derive from the brand color surface
// in tenantThemeToCSS().

export interface ThemeButtonTokens {
  /** --btn-bg: default button background. Defaults to --primary. */
  bg?: string;
  /** --btn-text: text on the button background. Defaults to --primary-text. */
  text?: string;
  /** --btn-hover-bg: :hover / :focus-visible background. */
  hoverBg?: string;
  /** --btn-active-bg: :active / pressed background. */
  activeBg?: string;
  /** --btn-ring: focus ring colour. Defaults to --ring. */
  ring?: string;
  /** --btn-radius: border-radius. Defaults to --radius-interactive. */
  radius?: string;
  /** --btn-shadow: optional lift shadow. Defaults to shadow-sm. */
  shadow?: string;
  /** --btn-font-weight: label font-weight. Defaults to "600". */
  fontWeight?: string;
}

// ── Motion tokens ─────────────────────────────────────────────────────────────
//
// Transition timing and easing for the tenant's interaction feel.
// Optional — platform defaults (150ms ease-in-out) apply when absent.

export interface ThemeMotionTokens {
  /** --transition-fast: micro-interaction speed. Default "100ms ease-in-out". */
  transitionFast?: string;
  /** --transition-base: default speed. Default "150ms ease-in-out". */
  transitionBase?: string;
  /** --transition-slow: panel/overlay speed. Default "300ms ease-in-out". */
  transitionSlow?: string;
  /** --ease-default: standard easing. */
  easingDefault?: string;
  /** --ease-spring: bouncy easing for expressive interactions. */
  easingSpring?: string;
}

// ── Component-level style tokens ──────────────────────────────────────────────
//
// Optional per-tenant overrides for common component surface patterns.
// When absent, values are derived from the TenantTheme color fields.

export interface ThemeComponentStyles {
  // ── Section backgrounds ─────────────────────────────────────────────────────
  /** Hero section background. Defaults to neutral-950. */
  heroBg?: string;
  /** CTA section/block background. Defaults to --primary. */
  ctaBg?: string;
  /** Body text colour on a CTA background. Defaults to --primary-subtle. */
  ctaBodyText?: string;
  /** Subtle section background (proof, features, FAQ). */
  subtleSectionBg?: string;
  /** Border on subtle sections. */
  subtleSectionBorder?: string;

  // ── Card tokens ─────────────────────────────────────────────────────────────
  /** Card/panel background. Defaults to #ffffff. */
  cardBg?: string;
  /** Card border colour. */
  cardBorderColor?: string;
  /** Card border-radius. Defaults to --radius-card. */
  cardRadius?: string;
  /** Card box-shadow. Defaults to shadow-sm. */
  cardShadow?: string;
  /** Pull-quote / accent colour. Defaults to --primary. */
  quoteColor?: string;

  // ── Hero expansion ──────────────────────────────────────────────────────────
  /** Glow decoration colour. Defaults to --primary. */
  heroGlowColor?: string;
  /** Opacity of the hero glow (0–1 string). Defaults to "0.2". */
  heroGlowOpacity?: string;
  /** Hero headline text colour. Defaults to --text-inverse. */
  heroTitleColor?: string;
  /** Hero subheadline colour. Defaults to --text-subtle. */
  heroSubtitleColor?: string;

  // ── Proof / testimonial tokens ──────────────────────────────────────────────
  /** Proof section background. */
  proofBg?: string;
  /** Proof section border. Defaults to "transparent". */
  proofBorder?: string;
  /** Proof card background. Defaults to --card-bg. */
  proofCardBg?: string;
  /** Proof card border. */
  proofCardBorder?: string;
  /** Proof card radius. */
  proofCardRadius?: string;
  /** Proof card shadow. */
  proofCardShadow?: string;
  /** Proof quote mark colour. */
  proofQuoteColor?: string;

  // ── Feature-grid tokens ─────────────────────────────────────────────────────
  /** Feature-grid section background. */
  featureGridBg?: string;
  /** Feature-grid section border. */
  featureGridBorder?: string;
  /** Feature-grid card background. */
  featureGridCardBg?: string;
  /** Feature-grid card border. */
  featureGridCardBorder?: string;
  /** Feature-grid card radius. */
  featureGridCardRadius?: string;
  /** Feature-grid card shadow. */
  featureGridCardShadow?: string;
  /** Feature-grid icon container background (icons-left variant). */
  featureGridIconBg?: string;
}

// ── Brand / identity metadata ─────────────────────────────────────────────────

export interface TenantBrandMeta {
  /** Human-readable display name. */
  name: string;
  /** One-sentence positioning statement. */
  tagline?: string;
  /** Path to the tenant's logo, relative to /public. */
  logoPath?: string;
  /** Path to the favicon, relative to /public. */
  faviconPath?: string;
}

// ── Root TenantTheme ──────────────────────────────────────────────────────────

/**
 * Complete visual identity and brand configuration for a single tenant.
 *
 * Every field maps to one or more CSS custom properties that override the
 * design-system :root defaults. See tenantThemeToCSS() for the exact mapping.
 */
export interface TenantTheme {
  colors: {
    brand:      TenantBrandColors;
    text:       TenantTextColors;
    background: TenantBackgroundColors;
    border:     TenantBorderColors;
  };
  /** Corner radius personality. See RADIUS_PRESETS. */
  radius: RadiusPersonality;
  /** Brand identity metadata. */
  meta: TenantBrandMeta;
  /** Optional typography overrides. */
  typography?: ThemeTypography;
  /** Optional button component token overrides. */
  button?: ThemeButtonTokens;
  /** Optional motion / animation token overrides. */
  motion?: ThemeMotionTokens;
  /** Optional component-level style overrides. */
  componentStyles?: ThemeComponentStyles;
}

// ── CSS variable generator ────────────────────────────────────────────────────

/**
 * Converts a TenantTheme to a block of CSS custom property declarations.
 *
 * Returns the inner content of a :root { } rule — each line is indented
 * with two spaces and ends with a semicolon.
 */
export function tenantThemeToCSS(theme: TenantTheme): string {
  const { colors, radius, typography, button, motion, componentStyles: cs } = theme;
  const r = RADIUS_PRESETS[radius];

  // ── Derived defaults ────────────────────────────────────────────────────────

  // Section / card
  const heroBg             = cs?.heroBg              ?? neutral[950];
  const ctaBg              = cs?.ctaBg               ?? colors.brand.primary;
  const ctaBodyText        = cs?.ctaBodyText          ?? colors.brand.primarySubtle;
  const subtleBg           = cs?.subtleSectionBg     ?? colors.background.bgSubtle;
  const subtleBorder       = cs?.subtleSectionBorder  ?? colors.border.border;
  const cardBg             = cs?.cardBg              ?? "#ffffff";
  const cardBorder         = cs?.cardBorderColor     ?? colors.border.border;
  const cardRadius         = cs?.cardRadius          ?? r.card;
  const cardShadow         = cs?.cardShadow          ?? shadows.sm;
  const quoteColor         = cs?.quoteColor          ?? colors.brand.primary;

  // Hero expansion
  const heroGlowColor      = cs?.heroGlowColor       ?? colors.brand.primary;
  const heroGlowOpacity    = cs?.heroGlowOpacity     ?? "0.2";
  const heroTitleColor     = cs?.heroTitleColor      ?? colors.text.textInverse;
  const heroSubtitleColor  = cs?.heroSubtitleColor   ?? colors.text.textSubtle;

  // Proof
  const proofBg            = cs?.proofBg             ?? colors.background.bg;
  const proofBorder        = cs?.proofBorder         ?? "transparent";
  const proofCardBg        = cs?.proofCardBg         ?? cardBg;
  const proofCardBorder    = cs?.proofCardBorder     ?? cardBorder;
  const proofCardRadius    = cs?.proofCardRadius     ?? cardRadius;
  const proofCardShadow    = cs?.proofCardShadow     ?? cardShadow;
  const proofQuoteColor    = cs?.proofQuoteColor     ?? quoteColor;

  // Feature-grid
  const fgBg               = cs?.featureGridBg          ?? subtleBg;
  const fgBorder           = cs?.featureGridBorder      ?? subtleBorder;
  const fgCardBg           = cs?.featureGridCardBg      ?? cardBg;
  const fgCardBorder       = cs?.featureGridCardBorder  ?? cardBorder;
  const fgCardRadius       = cs?.featureGridCardRadius  ?? cardRadius;
  const fgCardShadow       = cs?.featureGridCardShadow  ?? cardShadow;
  const fgIconBg           = cs?.featureGridIconBg      ?? subtleBg;

  // Typography
  const headingFont        = typography?.headingFont      ?? fontFamily.sans;
  const headingWeight      = typography?.headingWeight    ?? "700";
  const subheadingWeight   = typography?.subheadingWeight ?? "600";

  // Button
  const btnBg              = button?.bg         ?? colors.brand.primary;
  const btnText            = button?.text        ?? colors.brand.primaryText;
  const btnHoverBg         = button?.hoverBg     ?? colors.brand.primaryHover;
  const btnActiveBg        = button?.activeBg    ?? colors.brand.primaryActive;
  const btnRing            = button?.ring        ?? colors.brand.ring;
  const btnRadius          = button?.radius      ?? r.interactive;
  const btnShadow          = button?.shadow      ?? shadows.sm;
  const btnFontWeight      = button?.fontWeight  ?? "600";

  // Motion
  const easeBase           = "cubic-bezier(0.4, 0, 0.2, 1)";
  const transitionFast     = motion?.transitionFast  ?? `100ms ${easeBase}`;
  const transitionBase     = motion?.transitionBase  ?? `150ms ${easeBase}`;
  const transitionSlow     = motion?.transitionSlow  ?? `300ms ${easeBase}`;
  const easingDefault      = motion?.easingDefault   ?? easeBase;
  const easingSpring       = motion?.easingSpring    ?? "cubic-bezier(0.34, 1.56, 0.64, 1)";

  const vars: [string, string][] = [
    // ── Brand / interactive ───────────────────────────────────────────────────
    ["--primary",           colors.brand.primary],
    ["--primary-hover",     colors.brand.primaryHover],
    ["--primary-active",    colors.brand.primaryActive],
    ["--primary-subtle",    colors.brand.primarySubtle],
    ["--primary-text",      colors.brand.primaryText],
    ["--ring",              colors.brand.ring],
    ["--text-brand",        colors.brand.textBrand],

    // ── Text ─────────────────────────────────────────────────────────────────
    ["--text",              colors.text.text],
    ["--text-muted",        colors.text.textMuted],
    ["--text-subtle",       colors.text.textSubtle],
    ["--text-inverse",      colors.text.textInverse],

    // ── Backgrounds ───────────────────────────────────────────────────────────
    ["--bg",                colors.background.bg],
    ["--bg-subtle",         colors.background.bgSubtle],
    ["--bg-inverse",        colors.background.bgInverse],

    // ── Borders ───────────────────────────────────────────────────────────────
    ["--border",            colors.border.border],
    ["--border-strong",     colors.border.borderStrong],

    // ── Component radii ───────────────────────────────────────────────────────
    ["--radius-interactive", r.interactive],
    ["--radius-card",        r.card],
    ["--radius-popover",     r.popover],

    // ── Motion ────────────────────────────────────────────────────────────────
    ["--transition-fast",  transitionFast],
    ["--transition-base",  transitionBase],
    ["--transition-slow",  transitionSlow],
    ["--ease-default",     easingDefault],
    ["--ease-spring",      easingSpring],

    // ── Button ────────────────────────────────────────────────────────────────
    ["--btn-bg",           btnBg],
    ["--btn-text",         btnText],
    ["--btn-hover-bg",     btnHoverBg],
    ["--btn-active-bg",    btnActiveBg],
    ["--btn-ring",         btnRing],
    ["--btn-radius",       btnRadius],
    ["--btn-shadow",       btnShadow],
    ["--btn-font-weight",  btnFontWeight],

    // ── Section surface tokens ────────────────────────────────────────────────
    ["--section-hero-bg",        heroBg],
    ["--section-cta-bg",         ctaBg],
    ["--section-cta-body",       ctaBodyText],
    ["--section-subtle-bg",      subtleBg],
    ["--section-subtle-border",  subtleBorder],

    // ── Card tokens ───────────────────────────────────────────────────────────
    ["--card-bg",          cardBg],
    ["--card-border",      cardBorder],
    ["--card-radius",      cardRadius],
    ["--card-shadow",      cardShadow],
    ["--card-quote",       quoteColor],

    // ── Hero component tokens ─────────────────────────────────────────────────
    ["--hero-bg",              heroBg],
    ["--hero-glow-color",      heroGlowColor],
    ["--hero-glow-opacity",    heroGlowOpacity],
    ["--hero-title-color",     heroTitleColor],
    ["--hero-subtitle-color",  heroSubtitleColor],

    // ── Proof / testimonial tokens ────────────────────────────────────────────
    ["--proof-bg",           proofBg],
    ["--proof-border",       proofBorder],
    ["--proof-card-bg",      proofCardBg],
    ["--proof-card-border",  proofCardBorder],
    ["--proof-card-radius",  proofCardRadius],
    ["--proof-card-shadow",  proofCardShadow],
    ["--proof-quote-color",  proofQuoteColor],

    // ── Feature-grid tokens ───────────────────────────────────────────────────
    ["--feature-grid-bg",           fgBg],
    ["--feature-grid-border",       fgBorder],
    ["--feature-grid-card-bg",      fgCardBg],
    ["--feature-grid-card-border",  fgCardBorder],
    ["--feature-grid-card-radius",  fgCardRadius],
    ["--feature-grid-card-shadow",  fgCardShadow],
    ["--feature-grid-icon-bg",      fgIconBg],

    // ── Typography component tokens ───────────────────────────────────────────
    ["--font-heading",           headingFont],
    ["--font-heading-weight",    headingWeight],
    ["--font-subheading-weight", subheadingWeight],
  ];

  return vars.map(([key, val]) => `  ${key}: ${val};`).join("\n") + "\n";
}

// ── Re-export palette references ─────────────────────────────────────────────
export { brand, neutral };
