/**
 * demo/types.ts
 *
 * Shared type definitions for the Prospect Demo Mode feature.
 * Client-safe — type definitions only, no logic or env vars.
 */

// ── Core enums ────────────────────────────────────────────────────────────────

export type SiteCategory =
  | "b2b_saas"
  | "agency"
  | "ecommerce"
  | "recruitment"
  | "general";

export type DemoLanguage = "en" | "nl";
export type DemoMode    = "brand_match" | "structure_match" | "personalization_demo";

export type DemoScenarioId =
  | "new_visitor"
  | "returning_visitor"
  | "high_intent"
  | "careers"
  | "evening";

// ── Brand signals extracted from source site ──────────────────────────────────

export interface BrandSignals {
  primaryColor:     string;         // hex, e.g. "#3b82f6"
  secondaryColor:   string;         // hex, darkened variant
  textColor:        string;         // inferred text color
  surfaceColor:     string;         // background surface
  headingFont:      string | null;  // detected heading font family
  bodyFont:         string | null;  // detected body font family
  googleFontsUrl:   string | null;  // Google Fonts CSS URL if found
  borderRadius:     "none" | "sm" | "md" | "lg" | "full";
  hasPricingPage:   boolean;
  hasCareersPage:   boolean;
  hasCasesPage:     boolean;
  hasBlogPage:      boolean;
  navLinks:         string[];       // detected nav link labels
  confidence:       "high" | "medium" | "low";
}

// ── Block types — rich structured content ─────────────────────────────────────

export interface HeroBlock {
  headline:      string;
  subheadline:   string;
  primaryCta:    string;
  secondaryCta?: string;
  imageUrl?:     string;
  imageAlt?:     string;
}

export interface ServiceCard {
  icon:        string;   // emoji
  title:       string;
  description: string;
}

export interface ServicesBlock {
  heading:     string;
  subheading?: string;
  services:    ServiceCard[];
}

export interface ProofMetric {
  value: string;
  label: string;
}

export interface Testimonial {
  quote:   string;
  author:  string;
  role:    string;
  company: string;
}

export interface ProofBlock {
  heading:      string;
  metrics:      ProofMetric[];
  testimonial?: Testimonial;
  imageUrl?:    string;
}

export interface CaseCard {
  company:     string;
  industry?:   string;
  description: string;
  result:      string;
}

export interface CasesBlock {
  heading: string;
  cases:   CaseCard[];
}

export interface CtaBlock {
  heading:       string;
  body:          string;
  primaryCta:    string;
  secondaryCta?: string;
}

export interface PricingTier {
  name:        string;
  price:       string;
  period:      string;
  description: string;
  features:    string[];
  ctaLabel:    string;
  highlighted: boolean;
}

export interface PricingBlock {
  heading:     string;
  subheading?: string;
  tiers:       PricingTier[];
}

export interface RoleCard {
  title:      string;
  department: string;
  location:   string;
}

export interface CareersBlock {
  heading:  string;
  body:     string;
  roles:    RoleCard[];
  ctaLabel: string;
}

/**
 * Per-scenario overrides — only the changed fields need to be defined.
 * Applied on top of the base DemoPageContent for each scenario.
 */
export interface ScenarioOverride {
  heroHeadline?:    string;
  heroSubheadline?: string;
  heroCta?:         string;
  proofHeading?:    string;
  ctaHeading?:      string;
  ctaBody?:         string;
  ctaCta?:          string;
}

/**
 * Full page content for one language.
 * Generated by AI (preferred) or rich templates (fallback).
 */
export interface DemoPageContent {
  language:          DemoLanguage;
  hero:              HeroBlock;
  services:          ServicesBlock;
  proof:             ProofBlock;
  cases?:            CasesBlock;
  cta:               CtaBlock;
  pricing?:          PricingBlock;
  careers?:          CareersBlock;
  /** Per-scenario overrides applied on top of the base content. */
  scenarioOverrides: Partial<Record<DemoScenarioId, ScenarioOverride>>;
}

/** Curated image URLs selected for the demo (hero, services, cases). */
export interface DemoImages {
  hero?:     string;
  services?: string;
  cases?:    string;
}

// ── Legacy scenario types (kept for backward compat + scenario switcher) ──────

export interface DemoVisitorContext {
  description:  string;
  segment?:     string;
  intent?:      "browsing" | "researching" | "buying";
  source?:      string;
  timeContext?: string;
}

export interface DemoHeroContent {
  headline:    string;
  subheadline: string;
  ctaLabel:    string;
}

export interface DemoProofContent {
  heading: string;
  body:    string;
  stat?:   string;
}

export interface DemoCtaContent {
  heading:  string;
  body:     string;
  ctaLabel: string;
}

export interface DemoExperience {
  hero:  DemoHeroContent;
  proof: DemoProofContent;
  cta:   DemoCtaContent;
}

export interface DemoScenario {
  id:          DemoScenarioId;
  label:       string;
  description: string;
  context:     DemoVisitorContext;
  experience:  DemoExperience;
}

/** Legacy brand theme (preserved for backward compat). */
export interface DemoTheme {
  primaryColor:   string;
  secondaryColor: string;
  logoUrl?:       string;
  faviconUrl?:    string;
}

// ── Site analysis ──────────────────────────────────────────────────────────────

export interface SiteAnalysis {
  fetchedUrl:        string;
  title:             string;
  description:       string;
  category:          SiteCategory;
  primaryColor:      string;
  secondaryColor:    string;
  logoUrl?:          string;
  faviconUrl?:       string;
  firstH1?:          string;
  keywords:          string[];
  fetchSucceeded:    boolean;
  // Enhanced signals (added in v2)
  brandSignals?:     BrandSignals;
  detectedLanguage?: DemoLanguage;
}

// ── Demo instance ──────────────────────────────────────────────────────────────

/** Generation mode for a demo instance: "synthetic" = AI-generated, "mirror" = live site copy */
export type DemoInstanceMode = "synthetic" | "mirror";

export interface DemoInstance {
  id:              string;
  source_url:      string;
  site_name:       string;
  site_description: string;
  site_category:   SiteCategory;

  // Brand colors
  primary_color:   string;
  secondary_color: string;
  logo_url:        string | null;
  favicon_url:     string | null;

  // Legacy scenario array (always present for backward compat)
  scenarios:       DemoScenario[];

  // Rich bilingual content (null for demos generated before v2)
  content_en:      DemoPageContent | null;
  content_nl:      DemoPageContent | null;
  brand_signals:   BrandSignals | null;
  page_images:     DemoImages | null;

  // Mirror mode (v3) — instrumented copy of the prospect's own homepage
  demo_mode:       DemoInstanceMode;
  mirrored_html:   string | null;

  // Lifecycle
  created_at:      string;
  expires_at:      string;
  view_count:      number;

  // Generator metadata
  generated_by:    string | null;
  generation_ms:   number | null;
}

// ── API contracts ─────────────────────────────────────────────────────────────

export interface GenerateDemoInput {
  url:          string;
  generatedBy?: string;
  expiryDays?:  number;
}

export interface GenerateDemoResponse {
  demoId:    string;
  demoUrl:   string;
  siteName:  string;
  expiresAt: string;
}
