/**
 * Noise Detection — Anti-False-Positive Layer
 *
 * Detects repetitive, bursty, or shallow behavioral patterns that resemble
 * noise or friction rather than genuine buying intent.
 *
 * ─── Problem statement ────────────────────────────────────────────────────────
 *
 *   Without this layer, a visitor who clicks the pricing page 5 times in
 *   10 seconds accumulates 5× the intent score of a single visit.  That is
 *   incorrect — repeated identical actions in a short window are more likely
 *   to signal confusion or friction than strong interest.
 *
 * ─── Solutions provided ───────────────────────────────────────────────────────
 *
 *   1. Event deduplication / downweighting
 *      Same (event_type + page_path) within DEDUP_WINDOW_MS → weight = 0.10.
 *      Canonical first occurrence stays at weight 1.0.
 *      This alone reduces 5 identical page views from 5× to ~1.4× score impact.
 *
 *   2. Signal diversity scoring
 *      Counts distinct high-value signal types that have fired.
 *      Pricing + Pricing + Pricing = 1 unique signal.
 *      Pricing + About + Form start = 3 unique signals.
 *      A visitor who triggers 6/10 signal types is meaningfully more credible
 *      than one who only triggers 1 type at high volume.
 *
 *   3. Burst / tempo detection
 *      If ≥ BURST_EVENT_THRESHOLD events occur within BURST_WINDOW_MS and the
 *      diversity of those events is < BURST_DIVERSITY_THRESHOLD distinct keys,
 *      a burst penalty (0–0.5) is applied.  This reduces confidence in signals
 *      generated by rapid, repetitive navigation.
 *
 *   4. Friction score
 *      Composite 0–100 score reflecting confusion/friction signals:
 *        • Repetition rate (what % of events were downweighted as duplicates)
 *        • Lack of progression (many views, no high-value actions)
 *        • Burst presence
 *        • Single-signal dominance (one signal type accounts for most events)
 *      A high friction score reduces intentConfidence in compute-confidence.ts.
 *
 * ─── Configuration ────────────────────────────────────────────────────────────
 *
 *   All tuneable constants are exported so they can be overridden in tests.
 *
 * ─── Pure function — no I/O ───────────────────────────────────────────────────
 */

import type { JourneyEventRow } from "./types";

// ── Configuration constants ───────────────────────────────────────────────────

/** Events with the same dedup key within this window are considered duplicates. */
export const DEDUP_WINDOW_MS = 30_000; // 30 seconds

/** Number of events in a burst window to trigger burst detection. */
export const BURST_EVENT_THRESHOLD = 4;

/** Time window for burst detection. */
export const BURST_WINDOW_MS = 60_000; // 60 seconds

/**
 * Min distinct dedup keys within the burst window to NOT be considered a burst.
 * If distinct keys < this value, the burst is "low-diversity" → penalty applies.
 */
export const BURST_DIVERSITY_THRESHOLD = 3;

/** Weight applied to duplicate events when scoring rules. */
export const DUPLICATE_EVENT_WEIGHT = 0.10;

/**
 * Ten high-value behavioral signals. Each is a named slot that is either
 * "active" (1) or "inactive" (0) regardless of how many times it fired.
 * Signal diversity = count(active) / SIGNAL_SLOT_COUNT.
 */
export const SIGNAL_SLOT_COUNT = 10;

// ── Result types ──────────────────────────────────────────────────────────────

/**
 * A journey event annotated with its deduplication weight.
 *
 *   weight = 1.0 → canonical event; scored normally
 *   weight = 0.1 → duplicate within dedup window; score is heavily discounted
 */
export interface WeightedEvent {
  event:          JourneyEventRow;
  /**
   * Scoring weight: 1.0 for canonical events, DUPLICATE_EVENT_WEIGHT for
   * duplicates detected within DEDUP_WINDOW_MS of the same dedup key.
   */
  weight:         number;
  /** True when this event was downweighted as a near-duplicate. */
  isDuplicate:    boolean;
  /**
   * The string key used to detect duplicates.
   * Format: `${event_type}:${page_path ?? event_value ?? ""}`.
   */
  deduplicatedKey: string;
}

export interface BurstAnalysis {
  /** 0–0.5 penalty factor (0 = no burst, 0.5 = severe burst). */
  burstPenalty:       number;
  /** True when a burst was detected in the event stream. */
  burstDetected:      boolean;
  /** Human-readable explanation of the burst (null when no burst). */
  burstReason:        string | null;
  /** Number of events that fell within the tightest detected burst window. */
  burstEventCount:    number;
  /** Number of distinct signal keys within the burst window. */
  burstDistinctKeys:  number;
}

export interface DiversityAnalysis {
  /**
   * 0–1 ratio: how many of the SIGNAL_SLOT_COUNT high-value signal types
   * are currently active.
   *   0.0  = only one type of signal (pure repetition)
   *   0.5  = 5 of 10 signal types fired
   *   1.0  = all 10 types fired (exceptional breadth)
   */
  signalDiversityScore: number;
  /** Count of active high-value signal types (0–10). */
  uniqueSignalCount:    number;
  /** Names of the active high-value signals (for debug). */
  activeSignals:        string[];
}

export interface NoiseAnalysisResult {
  /** Events annotated with deduplication weights (same order as input). */
  weightedEvents:       WeightedEvent[];
  /** Count of events that were downweighted as duplicates. */
  deduplicatedCount:    number;
  /** Ratio of downweighted events to total events (0–1). */
  duplicationRatio:     number;
  /** Burst analysis result. */
  burst:                BurstAnalysis;
  /** Signal diversity analysis result. */
  diversity:            DiversityAnalysis;
  /**
   * Friction / confusion score (0–100).
   *
   *   0–20  = clean signal, no friction detected
   *   20–40 = mild repetition, monitor
   *   40–60 = moderate noise, reduce confidence
   *   60–80 = strong friction, likely confusion
   *   80–100 = extreme noise (e.g. pricing spam), heavily penalised
   */
  frictionScore:        number;
  /** Human-readable list of friction signals detected. */
  frictionReasons:      string[];
}

// ── High-value signal slot definitions ───────────────────────────────────────

/**
 * The 10 high-value behavioral signal slots used for diversity scoring.
 * These represent distinct, meaningful TYPES of engagement — not raw counts.
 *
 * A visitor who triggers 6+ of these is broadly engaged and credible.
 * A visitor who triggers only 1 (even 20 times) is not diverse.
 */
export interface SignalSlotInput {
  hasVisitedPricing:    boolean;
  hasVisitedAbout:      boolean;
  hasVisitedCases:      boolean;
  hasVisitedContact:    boolean;
  hasClickedCta:        boolean;
  hasStartedForm:       boolean;   // formStartCount > 0
  hasSubmittedForm:     boolean;
  hasDownloaded:        boolean;   // downloadCount > 0
  hasMatchedSequence:   boolean;   // matchedSequences.length > 0
  isReturnVisitor:      boolean;   // repeatSessionBonus > 0.4
}

// ── Deduplication key ─────────────────────────────────────────────────────────

/**
 * Returns the deduplication key for an event.
 *
 * Two events with the same key that occur within DEDUP_WINDOW_MS are
 * considered near-duplicates; the second gets a reduced weight.
 *
 * Key format: `${event_type}:${page_path || event_value || ""}`
 *
 * Rationale:
 *   - page_view: keyed by page_path (so /pricing + /pricing = duplicate)
 *   - cta_click: keyed by event_value (button ID)
 *   - form_start / form_submit: keyed by event_value (form ID)
 *   - download: keyed by event_value (file path)
 */
function dedupKey(event: JourneyEventRow): string {
  const discriminator = event.page_path ?? event.event_value ?? "";
  return `${event.event_type}:${discriminator}`;
}

// ── Event weight annotation ───────────────────────────────────────────────────

/**
 * Annotates each event with a deduplication weight.
 *
 * Events that share the same dedupKey as an event within the previous
 * DEDUP_WINDOW_MS are marked as duplicates (weight = DUPLICATE_EVENT_WEIGHT).
 *
 * The very first occurrence of a key is always canonical (weight = 1.0).
 *
 * @param events  Chronologically-sorted journey events (oldest first).
 */
function annotateWeights(events: JourneyEventRow[]): WeightedEvent[] {
  // key → timestamp (ms) of the most recent canonical occurrence
  const lastCanonical = new Map<string, number>();

  return events.map((event) => {
    const key    = dedupKey(event);
    const nowMs  = new Date(event.occurred_at).getTime();
    const lastMs = lastCanonical.get(key);

    const isDuplicate = lastMs !== undefined && (nowMs - lastMs) < DEDUP_WINDOW_MS;
    const weight      = isDuplicate ? DUPLICATE_EVENT_WEIGHT : 1.0;

    // Always update the last-canonical time to the most recent event of this key,
    // so that a third visit re-starts the dedup window from the second visit.
    if (!isDuplicate) {
      lastCanonical.set(key, nowMs);
    }

    return { event, weight, isDuplicate, deduplicatedKey: key };
  });
}

// ── Burst detection ───────────────────────────────────────────────────────────

/**
 * Detects whether the event stream contains a "burst" — a cluster of many
 * events in a very short window with low signal diversity.
 *
 * A burst is suspicious because real intent-driven research typically shows
 * progression over minutes or hours, not rapid-fire identical clicks.
 *
 * Penalty scale:
 *   No burst:                          0.00
 *   4 events, 1 distinct key:          0.10
 *   6 events, 1 distinct key:          0.20
 *   8+ events, 1 distinct key:         0.40
 *   (capped at 0.50)
 *
 * @param events  Chronological event list.
 */
function detectBurst(events: JourneyEventRow[]): BurstAnalysis {
  if (events.length < BURST_EVENT_THRESHOLD) {
    return {
      burstPenalty: 0, burstDetected: false,
      burstReason: null, burstEventCount: 0, burstDistinctKeys: 0,
    };
  }

  // Sliding-window scan: find the worst (densest + least diverse) burst
  let maxPenalty      = 0;
  let worstCount      = 0;
  let worstDistinct   = BURST_DIVERSITY_THRESHOLD;
  let worstReason: string | null = null;

  for (let i = 0; i < events.length; i++) {
    const anchorMs = new Date(events[i]!.occurred_at).getTime();
    const keySet   = new Set<string>();
    let count      = 0;

    for (let j = i; j < events.length; j++) {
      const evMs = new Date(events[j]!.occurred_at).getTime();
      if (evMs - anchorMs > BURST_WINDOW_MS) break;

      count++;
      keySet.add(dedupKey(events[j]!));
    }

    const distinct = keySet.size;

    if (count >= BURST_EVENT_THRESHOLD && distinct < BURST_DIVERSITY_THRESHOLD) {
      // Penalty: scales with event count excess and inversely with diversity
      const countExcess  = Math.max(0, count - BURST_EVENT_THRESHOLD);
      const divDeficit   = Math.max(0, BURST_DIVERSITY_THRESHOLD - distinct);
      const rawPenalty   = (countExcess * 0.05 + divDeficit * 0.05 + 0.05);
      const penalty      = Math.min(0.50, rawPenalty);

      if (penalty > maxPenalty) {
        maxPenalty    = penalty;
        worstCount    = count;
        worstDistinct = distinct;
        worstReason   = `${count} events in ${BURST_WINDOW_MS / 1000}s window with only ${distinct} distinct signal type${distinct !== 1 ? "s" : ""}`;
      }
    }
  }

  if (maxPenalty === 0) {
    return {
      burstPenalty: 0, burstDetected: false,
      burstReason: null, burstEventCount: 0, burstDistinctKeys: 0,
    };
  }

  return {
    burstPenalty:      Math.round(maxPenalty * 100) / 100,
    burstDetected:     true,
    burstReason:       worstReason,
    burstEventCount:   worstCount,
    burstDistinctKeys: worstDistinct,
  };
}

// ── Signal diversity ──────────────────────────────────────────────────────────

/**
 * Computes the diversity of high-value behavioral signals.
 *
 * Each of the 10 signal slots is binary (active / not active), regardless
 * of how many times the underlying event occurred.  This means:
 *   - /pricing visited once → slot 1 active
 *   - /pricing visited 20 times → still slot 1 active (same slot)
 *   - /pricing + /about + form_start → 3 slots active
 *
 * diversityScore = activeCount / SIGNAL_SLOT_COUNT (0–1).
 */
function computeDiversity(slots: SignalSlotInput): DiversityAnalysis {
  const slotMap: Array<[string, boolean]> = [
    ["pricing_visit",   slots.hasVisitedPricing],
    ["about_visit",     slots.hasVisitedAbout],
    ["cases_visit",     slots.hasVisitedCases],
    ["contact_visit",   slots.hasVisitedContact],
    ["cta_click",       slots.hasClickedCta],
    ["form_start",      slots.hasStartedForm],
    ["form_submit",     slots.hasSubmittedForm],
    ["download",        slots.hasDownloaded],
    ["sequence_match",  slots.hasMatchedSequence],
    ["return_visitor",  slots.isReturnVisitor],
  ];

  const active = slotMap.filter(([, v]) => v);
  const activeSignals  = active.map(([k]) => k);
  const uniqueSignalCount   = active.length;
  const signalDiversityScore = Math.round((uniqueSignalCount / SIGNAL_SLOT_COUNT) * 100) / 100;

  return { signalDiversityScore, uniqueSignalCount, activeSignals };
}

// ── Friction score ────────────────────────────────────────────────────────────

/**
 * Computes a composite friction / confusion score (0–100).
 *
 * Four components:
 *
 *   1. Repetition rate (0–50)
 *      Contribution from the percentage of events that were near-duplicates.
 *      deduplicationRatio = deduped / total
 *      score_1 = deduplicationRatio × 50
 *      Example: 4 of 5 events duped → 0.8 × 50 = 40
 *
 *   2. No-progression penalty (0–25)
 *      Applied when page views exceed a threshold AND the visitor has taken
 *      no high-value action (no CTA click, no form start, no contact visit,
 *      no sequence match).
 *      Applied only when most events are page_views (depth ≥ 0.75).
 *
 *   3. Burst echo (0–15)
 *      Reflects burstPenalty in the friction score so both signals reinforce.
 *      score_3 = burstPenalty × 30, capped at 15.
 *
 *   4. Single-signal dominance (0–15)
 *      If one dedup key accounts for more than 70% of all events, that
 *      signals unhealthy fixation on a single page.
 *
 * Total is clamped to [0, 100].
 */
function computeFriction(
  weightedEvents:    WeightedEvent[],
  deduplicatedCount: number,
  burst:             BurstAnalysis,
  diversity:         DiversityAnalysis,
  totalEvents:       number,
  pageViewCount:     number,
): { frictionScore: number; frictionReasons: string[] } {

  const reasons: string[] = [];
  let score = 0;

  // ── Component 1: Repetition rate ──────────────────────────────────────────
  const duplicationRatio = totalEvents > 0 ? deduplicatedCount / totalEvents : 0;
  const repetitionScore  = Math.round(duplicationRatio * 50);
  if (repetitionScore > 0) {
    score += repetitionScore;
    reasons.push(
      `${Math.round(duplicationRatio * 100)}% of events deduplicated as near-identical repetition → +${repetitionScore} friction`,
    );
  }

  // ── Component 2: No-progression penalty ───────────────────────────────────
  const pageViewDominance = totalEvents > 0 ? pageViewCount / totalEvents : 0;
  const noProgression     =
    pageViewCount >= 4 &&
    pageViewDominance >= 0.75 &&
    diversity.uniqueSignalCount <= 1;

  if (noProgression) {
    const progressionPenalty = 25;
    score += progressionPenalty;
    reasons.push(
      `${pageViewCount} page views with no meaningful high-value actions → +${progressionPenalty} friction (no progression)`,
    );
  }

  // ── Component 3: Burst echo ────────────────────────────────────────────────
  if (burst.burstDetected) {
    const burstEcho = Math.min(15, Math.round(burst.burstPenalty * 30));
    score += burstEcho;
    reasons.push(`burst detected (${burst.burstReason}) → +${burstEcho} friction`);
  }

  // ── Component 4: Single-signal dominance ──────────────────────────────────
  // Count occurrences per dedup key
  const keyCounts = new Map<string, number>();
  for (const { deduplicatedKey } of weightedEvents) {
    keyCounts.set(deduplicatedKey, (keyCounts.get(deduplicatedKey) ?? 0) + 1);
  }
  const maxKeyCount     = Math.max(0, ...Array.from(keyCounts.values()));
  const dominanceRatio  = totalEvents > 0 ? maxKeyCount / totalEvents : 0;

  if (dominanceRatio > 0.7 && totalEvents >= 3) {
    const dominanceScore = Math.round((dominanceRatio - 0.7) / 0.3 * 15);
    score += dominanceScore;
    const dominantKey = [...keyCounts.entries()].sort((a, b) => b[1] - a[1])[0]?.[0];
    reasons.push(
      `"${dominantKey}" accounts for ${Math.round(dominanceRatio * 100)}% of all events → +${dominanceScore} friction (single-signal dominance)`,
    );
  }

  return {
    frictionScore:   Math.min(100, Math.round(score)),
    frictionReasons: reasons,
  };
}

// ── Main export ───────────────────────────────────────────────────────────────

/**
 * Performs full noise analysis on a session's event stream.
 *
 * Returns weighted events (for use in scoring), burst analysis, signal
 * diversity, and the composite friction score.
 *
 * All values are deterministic — identical inputs produce identical outputs.
 * The function has no I/O and no side effects.
 *
 * @param events      Chronological journey events (oldest first).
 * @param signalSlots High-value signal slot booleans (aggregated from flags).
 */
export function analyzeNoise(
  events:      JourneyEventRow[],
  signalSlots: SignalSlotInput,
): NoiseAnalysisResult {
  // Step 1: annotate dedup weights
  const weightedEvents    = annotateWeights(events);
  const deduplicatedCount = weightedEvents.filter((e) => e.isDuplicate).length;
  const duplicationRatio  = events.length > 0 ? deduplicatedCount / events.length : 0;

  // Step 2: burst detection
  const burst = detectBurst(events);

  // Step 3: signal diversity
  const diversity = computeDiversity(signalSlots);

  // Step 4: page view count
  const pageViewCount = events.filter((e) => e.event_type === "page_view").length;

  // Step 5: friction score
  const { frictionScore, frictionReasons } = computeFriction(
    weightedEvents,
    deduplicatedCount,
    burst,
    diversity,
    events.length,
    pageViewCount,
  );

  return {
    weightedEvents,
    deduplicatedCount,
    duplicationRatio: Math.round(duplicationRatio * 100) / 100,
    burst,
    diversity,
    frictionScore,
    frictionReasons,
  };
}
