/**
 * Provisioning — design-token CSS generator.
 *
 * Emits a plain `:root { --mc-* }` stylesheet from the platform's design tokens
 * so provisioned blocks share the platform design system exactly. A tenant may
 * override brand/neutral hues via tenant.theme; those overrides win, otherwise
 * the platform defaults are used. This is what keeps "styling" part of the
 * build pipeline the platform owns.
 */

import { brand, neutral } from "@/design-system/tokens/colors";
import { radii } from "@/design-system/tokens/radii";
import { fontFamily } from "@/design-system/tokens/typography";

export interface TokenOverrides {
  /** e.g. { 500: "#0ea5e9", 600: "#0284c7" } */
  brand?: Partial<Record<keyof typeof brand, string>>;
  neutral?: Partial<Record<keyof typeof neutral, string>>;
  fontSans?: string;
}

export function generateTokensCss(overrides: TokenOverrides = {}): string {
  const b = { ...brand, ...(overrides.brand ?? {}) };
  const n = { ...neutral, ...(overrides.neutral ?? {}) };
  const sans = overrides.fontSans ?? fontFamily.sans;

  return `/*
 * Mister Chameleon — design tokens (provisioned).
 * Generated by the platform build pipeline. Do not edit by hand:
 * run \`php please mc:sync\` to refresh from the platform.
 */
:root {
  --mc-brand-50: ${b[50]};
  --mc-brand-100: ${b[100]};
  --mc-brand-500: ${b[500]};
  --mc-brand-600: ${b[600]};
  --mc-brand-700: ${b[700]};
  --mc-ink-700: ${n[700]};
  --mc-ink-900: ${n[900]};
  --mc-ink-950: ${n[950]};
  --mc-surface: ${n[0]};
  --mc-surface-subtle: ${n[50]};
  --mc-border: ${n[200]};
  --mc-radius-interactive: ${radii.md};
  --mc-radius-card: ${radii.xl};
  --mc-font-sans: ${sans};
}

.mc-slot { font-family: var(--mc-font-sans); color: var(--mc-ink-900); }
.mc-eyebrow { color: var(--mc-brand-600); font-weight: 600; letter-spacing: .04em; text-transform: uppercase; font-size: .8rem; }
.mc-heading { font-weight: 700; line-height: 1.1; }
.mc-body { color: var(--mc-ink-700); }
.mc-btn { display: inline-block; border-radius: var(--mc-radius-interactive); padding: .75rem 1.25rem; font-weight: 600; text-decoration: none; }
.mc-btn--primary { background: var(--mc-brand-600); color: #fff; }
.mc-slot--cta, .mc-slot--conversion { background: var(--mc-surface-subtle); border-radius: var(--mc-radius-card); padding: 2.5rem; }
`;
}
