-- Nascita: variant-content in de platform-store (snippet-slots platform-first) — NL-teksten
-- Draai op PROD (project kdhfpvjeriszteqhpgll). Idempotent.
--
-- BELANGRIJK: zet cms_provider NIET op 'platform'. Door de platform-first-code leest de
-- snippet deze platform-varianten al automatisch als eerste, en gebruikt hij de tenant-CMS
-- (Sanity) als vangnet voor keys die hier nog niet staan. Zet je de provider op 'platform',
-- dan wordt óók de fallback de (deels lege) platform-store, en krijg je lege slots voor
-- niet-gemigreerde keys ("soms wel, soms niet"). Laat cms_provider dus op null/Sanity staan.
--
-- Deze varianten zijn bewerkbaar in de Content-tab van de admin. Wil je nascita 100%
-- platform-native, migreer dan alle overige keys die de regels kunnen kiezen en pas daarna
-- eventueel cms_provider aan.

insert into platform_cms_content (tenant_id, variant_type, variant_key, content) values
  ('nascita','hero','hero_direct_brand','{"tag":"Bedrijfstransformatie die beklijft","title":"Je volgende hoofdstuk begint met de juiste strategie.","subtitle":"Nascita werkt samen met directieteams aan transformaties die blijven hangen. Van strategie tot uitvoering staan we naast je, niet alleen ervoor.","ctas":[{"label":"Start het gesprek","href":"/contact","variant":"primary"},{"label":"Ontdek onze aanpak","href":"/approach","variant":"secondary"}]}'::jsonb),
  ('nascita','hero','hero_google_problem','{"tag":"Er is een slimmere weg","title":"Vast tussen de strategie en de uitvoering?","subtitle":"De meeste transformaties mislukken niet omdat de strategie fout is, maar omdat de uitvoering vastloopt. Nascita dicht dat gat, van diagnose tot oplevering.","ctas":[{"label":"Zie hoe we werken","href":"/approach","variant":"primary"},{"label":"Plan een kennismaking","href":"/contact","variant":"secondary"}]}'::jsonb),
  ('nascita','hero','hero_linkedin_vision','{"tag":"De toekomst van wendbare organisaties","title":"Organisaties die zich aanpassen, presteren beter.","subtitle":"De sterkste directieteams reageren niet alleen op verandering, ze bouwen het vermogen om die te sturen. Nascita helpt je dat vermogen van binnenuit op te bouwen.","ctas":[{"label":"Ontdek onze visie","href":"/insights","variant":"primary"},{"label":"Praat met ons","href":"/contact","variant":"secondary"}]}'::jsonb),
  ('nascita','hero','hero_consideration','{"tag":"Je hebt gezien wat we doen. Dit is de volgende stap.","title":"Klaar om van verkennen naar doen te gaan?","subtitle":"Je hebt het werk gezien. Je weet welke transformaties we leveren. De volgende stap is een direct gesprek over waar je staat en wat er mogelijk is. Geen pitch, geen verplichting.","ctas":[{"label":"Plan een gesprek van 30 minuten","href":"/contact","variant":"primary"},{"label":"Lees een case","href":"/cases","variant":"secondary"}]}'::jsonb),
  ('nascita','hero','hero_intent_direct','{"tag":"Eén gesprek verwijderd van een plan","title":"Je weet al wat er moet veranderen. Laten we het pad bouwen.","subtitle":"Of het nu gaat om groei, een structurele herinrichting of een strategische ommezwaai: Nascita brengt de kaders, de ervaring en de hands-on begeleiding om het voor elkaar te krijgen. Laten we deze week praten.","ctas":[{"label":"Plan een kennismaking","href":"/contact","variant":"primary"},{"label":"Bekijk eerst onze aanpak","href":"/approach","variant":"secondary"}]}'::jsonb),
  ('nascita','proof','proof_platform','{"title":"Bewezen over sectoren en schaal heen","items":[{"title":"120+ transformaties geleverd","text":"Van PE-gedreven mid-market tot beursgenoteerde multinationals. Elke opdracht is hands-on, gericht op resultaat en bedoeld om intern vermogen op te bouwen, geen afhankelijkheid."},{"title":"Ingebed, niet alleen adviserend","text":"Onze consultants werken binnen je organisatie voor de duur van het programma. Strategie en uitvoering onder één dak betekent geen gaten bij de overdracht."},{"title":"Sectoronafhankelijke scherpte","text":"Financiële dienstverlening, industrie, technologie, zakelijke dienstverlening. We brengen overdraagbare kaders en dagen sectorbrede blinde vlekken uit."}]}'::jsonb),
  ('nascita','proof','proof_cases','{"title":"Resultaten die het bedrijf vooruithelpen","items":[{"title":"40% kortere time-to-market","text":"Een operationele herinrichting bij een B2B-technologiebedrijf verkortte de releasecyclus van 18 naar 11 weken, zonder extra mensen."},{"title":"€18M aan geïdentificeerde besparingen","text":"Een diagnose van 90 dagen bij een dienstverlener van 600 man legde structurele inefficiënties van €18M per jaar bloot, met een helder plan om ze te verzilveren."},{"title":"3 portfoliobedrijven naar exit geschaald","text":"Ingebedde strategie en operationele steun bij drie PE-bedrijven, elk met een succesvolle exit binnen de investeringshorizon."}]}'::jsonb),
  ('nascita','proof','proof_default','{"title":"Vertrouwd door directieteams die meer nodig hebben dan een slide-deck","items":[{"title":"Van diagnose tot oplevering","text":"We leveren geen strategie af om daarna te verdwijnen. Nascita blijft betrokken tot in de uitvoering, want daar worden transformaties gewonnen of verloren."},{"title":"Resultaatgericht, niet uren-gedreven","text":"Onze opdrachten zijn opgebouwd rond mijlpalen, niet rond retainers. We slagen als jij slaagt, en onze tarieven zijn zo ingericht."},{"title":"Gebouwd voor complexe organisaties","text":"Matrixstructuren, veel belanghebbenden, verouderde processen: we hebben het allemaal genavigeerd. Complexiteit is het werk, geen reden om het probleem te versimpelen."}]}'::jsonb),
  ('nascita','proof','proof_vision','{"title":"Waar organisaties naartoe bewegen","items":[{"title":"Van reageren naar sturen","text":"De sterkste organisaties bouwen het vermogen om verandering zelf te sturen, in plaats van er alleen op te reageren."},{"title":"Uitvoering maakt het verschil","text":"Strategie is een commodity geworden; het onderscheid zit in wie de verandering ook echt oplevert."},{"title":"Wendbaarheid wordt de norm","text":"Structuur, mensen en processen die meebewegen worden de standaard, niet de uitzondering."}]}'::jsonb),
  ('nascita','cta','cta_meeting','{"title":"Laten we het hebben over wat er nu nodig is voor je organisatie","text":"Een kennismaking van 30 minuten is genoeg om te zien of Nascita past. Geen pitch, geen druk, gewoon een eerlijk gesprek over je situatie en wat er mogelijk is.","ctas":[{"label":"Plan een kennismaking","href":"/contact","variant":"primary"},{"label":"Stuur eerst een briefing","href":"/contact","variant":"secondary"}]}'::jsonb),
  ('nascita','cta','cta_guide','{"title":"De Transformation Readiness Diagnostic","text":"Een praktische zelfscan die 400+ directieteams gebruiken om de drie factoren te vinden die hun volgende verandertraject het meest waarschijnlijk laten ontsporen. Gratis, geen e-mailmuur.","ctas":[{"label":"Download de diagnose","href":"/resources/diagnostic","variant":"primary"},{"label":"Ontdek onze visie","href":"/insights","variant":"secondary"}]}'::jsonb),
  ('nascita','cta','cta_platform','{"title":"Zie hoe wij transformatie aanpakken","text":"Ons ingebedde leveringsmodel combineert strategische scherpte met hands-on steun in elke fase. Lees hoe we werken, en waarom klanten terugkomen.","ctas":[{"label":"Ontdek onze aanpak","href":"/approach","variant":"primary"},{"label":"Praat met ons","href":"/contact","variant":"secondary"}]}'::jsonb)
on conflict (tenant_id, variant_type, variant_key) do update set content = excluded.content;

-- Verificatie
select variant_type, variant_key, left(content->>'title',56) as title
from platform_cms_content where tenant_id='nascita' order by variant_type, variant_key;
