-- Nascita: van Sanity naar platform-CMS (snippet-slots uit het platform)
-- Draai op PROD (project kdhfpvjeriszteqhpgll). Idempotent.

-- 1. Zet nascita's CMS-provider op 'platform' zodat getHeroVariant/getCTAVariant uit
--    platform_cms_content lezen (bewerkbaar in de admin, geserveerd aan de snippet).
update tenant_settings set cms_provider = 'platform' where tenant_id = 'nascita';

-- 2. Migreer de huidige slot-varianten (1:1 uit de Sanity-seed) naar platform_cms_content,
--    zodat de live-site niet verandert. Daarna bewerk je ze in de Content-tab van nascita.
insert into platform_cms_content (tenant_id, variant_type, variant_key, content) values
  ('nascita','hero','hero_direct_brand','{"tag":"Business transformation, built to last","title":"Your next chapter starts with the right strategy.","subtitle":"Nascita partners with leadership teams to design and deliver transformations that stick. From strategy to execution, we work alongside you — not just in front of you.","ctas":[{"label":"Start the conversation","href":"/contact","variant":"primary"},{"label":"Explore our approach","href":"/approach","variant":"secondary"}]}'::jsonb),
  ('nascita','hero','hero_google_problem','{"tag":"There''s a smarter way through this","title":"Stuck between the strategy and the execution?","subtitle":"Most transformation programmes fail not because the strategy is wrong, but because implementation runs out of steam. Nascita closes that gap — from diagnosis through delivery.","ctas":[{"label":"See how we work","href":"/approach","variant":"primary"},{"label":"Book a discovery call","href":"/contact","variant":"secondary"}]}'::jsonb),
  ('nascita','hero','hero_linkedin_vision','{"tag":"The future of resilient organisations","title":"Organisations that adapt, outperform.","subtitle":"The most effective leadership teams don''t just react to change — they build the capability to drive it. Nascita helps you build that capability from the inside out.","ctas":[{"label":"Explore our thinking","href":"/insights","variant":"primary"},{"label":"Talk to us","href":"/contact","variant":"secondary"}]}'::jsonb),
  ('nascita','hero','hero_consideration','{"tag":"You''ve seen what we do. Here''s the next step.","title":"Ready to move from exploration to action?","subtitle":"You''ve seen the work. You know the kind of transformations we deliver. The next step is a direct conversation about where you are and what''s possible — no pitch deck, no obligation.","ctas":[{"label":"Book a 30-minute call","href":"/contact","variant":"primary"},{"label":"Read a case study","href":"/cases","variant":"secondary"}]}'::jsonb),
  ('nascita','hero','hero_intent_direct','{"tag":"One conversation away from a plan","title":"You already know what needs to change. Let''s build the path.","subtitle":"Whether you''re facing a growth challenge, a structural overhaul, or a strategic pivot — Nascita brings the frameworks, the experience, and the hands-on support to get it done. Let''s talk this week.","ctas":[{"label":"Book a discovery call","href":"/contact","variant":"primary"},{"label":"See our approach first","href":"/approach","variant":"secondary"}]}'::jsonb),
  ('nascita','proof','proof_platform','{"title":"Proven across industries and scale","items":[{"title":"120+ transformations delivered","text":"From PE-backed mid-market to listed multinationals — every engagement is hands-on, outcomes-focused, and designed to build internal capability, not dependency."},{"title":"Embedded, not advisory-only","text":"Our consultants work inside your organisation for the duration of the programme. Strategy and execution under the same roof means no handover gaps."},{"title":"Sector-agnostic rigour","text":"Financial services, industrial, technology, professional services — we bring transferable frameworks and challenge cross-sector blind spots."}]}'::jsonb),
  ('nascita','proof','proof_cases','{"title":"Results that move the business forward","items":[{"title":"40% reduction in time-to-market","text":"Operational redesign for a B2B technology company cut their product release cycle from 18 weeks to 11 — without adding headcount."},{"title":"€18M in identified efficiency gains","text":"A 90-day diagnostic across a 600-person professional services firm surfaced structural inefficiencies worth €18M annually — with a clear roadmap to capture them."},{"title":"3 portfolio companies scaled to exit","text":"Embedded strategy and operational support across three PE-backed businesses, each achieving a successful exit within the investment horizon."}]}'::jsonb),
  ('nascita','proof','proof_default','{"title":"Trusted by leadership teams who need more than a slide deck","items":[{"title":"From diagnosis to delivery","text":"We don''t hand over a strategy and disappear. Nascita stays involved through implementation — because that''s where transformations are won or lost."},{"title":"Outcome-obsessed, not hours-billed","text":"Our engagements are structured around milestones, not retainers. We succeed when you do — and we structure our fees to reflect that."},{"title":"Built for complex organisations","text":"Matrix structures, multiple stakeholders, legacy processes — we''ve navigated all of it. Complexity is the job, not a reason to simplify the problem."}]}'::jsonb),
  ('nascita','cta','cta_meeting','{"title":"Let''s talk about what''s next for your organisation","text":"A 30-minute discovery call is all it takes to understand whether Nascita is the right fit. No pitch, no pressure — just an honest conversation about your situation and what''s possible.","ctas":[{"label":"Book a discovery call","href":"/contact","variant":"primary"},{"label":"Send us a brief first","href":"/contact","variant":"secondary"}]}'::jsonb),
  ('nascita','cta','cta_guide','{"title":"The Transformation Readiness Diagnostic","text":"A practical self-assessment used by 400+ leadership teams to identify the three factors most likely to derail their next change programme. Free — no email gate.","ctas":[{"label":"Download the diagnostic","href":"/resources/diagnostic","variant":"primary"},{"label":"Explore our thinking","href":"/insights","variant":"secondary"}]}'::jsonb),
  ('nascita','cta','cta_platform','{"title":"See how we approach transformation","text":"Our embedded delivery model combines strategic rigour with hands-on support at every stage. Read how we work — and why clients come back.","ctas":[{"label":"Explore our approach","href":"/approach","variant":"primary"},{"label":"Talk to us","href":"/contact","variant":"secondary"}]}'::jsonb)
on conflict (tenant_id, variant_type, variant_key) do update set content = excluded.content;

-- 3. Verificatie
select variant_type, variant_key, left(content->>'title',48) as title
from platform_cms_content where tenant_id='nascita' order by variant_type, variant_key;
