-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: create ai_decision_logs table
-- ─────────────────────────────────────────────────────────────────────────────
--
-- Shadow-mode comparison log for AI decision providers.
--
-- When SHADOW_AI_ENABLED=true the homepage fires an AI decision provider in
-- parallel with the live rules provider. Both plans are written here after the
-- HTTP response has been sent (via Next.js after()). The rendered output is
-- always the live (rules) plan — this table exists purely for observability,
-- model evaluation, and gradual confidence building before promoting an AI
-- provider to production.
--
-- ─── Column reference ────────────────────────────────────────────────────────
--
--   id               — UUID PK, generated by Postgres
--   session_id       — FK to sessions.id; ON DELETE CASCADE
--   created_at       — row timestamp, set by Postgres
--   page_type        — which page the decision was for, e.g. "homepage"
--   live_provider    — name of the provider that produced the rendered plan
--                      (e.g. "rules")
--   live_plan        — JSONB snapshot of the rendered ExperiencePlan
--                      { heroKey, proofKey, ctaKey, reason }
--   shadow_provider  — name of the AI provider that ran in shadow
--                      (e.g. "claude" | "openai")
--   shadow_plan      — JSONB snapshot of the AI ExperiencePlan
--                      { heroKey, proofKey, ctaKey, reason, confidence? }
--   plans_match      — true when heroKey + proofKey + ctaKey are identical
--                      across live and shadow; computed by the application layer
--   context          — JSONB snapshot of the VisitorContext at decision time
--                      { source, device, visitType, utm*, referrer, pathname }
--
-- ─── Query patterns ──────────────────────────────────────────────────────────
--
--   Agreement rate over time:
--     SELECT date_trunc('day', created_at) AS day,
--            AVG(plans_match::int) AS agreement_rate
--     FROM ai_decision_logs
--     GROUP BY 1 ORDER BY 1 DESC;
--
--   Disagreements by traffic source:
--     SELECT context->>'source' AS source,
--            COUNT(*) FILTER (WHERE NOT plans_match) AS disagreements,
--            COUNT(*) AS total
--     FROM ai_decision_logs
--     GROUP BY 1 ORDER BY 2 DESC;
--
--   Shadow plan distribution:
--     SELECT shadow_plan->>'heroKey' AS hero_key, COUNT(*)
--     FROM ai_decision_logs
--     GROUP BY 1 ORDER BY 2 DESC;
--
-- ─── Indexes ─────────────────────────────────────────────────────────────────
--
--   idx_ai_decision_logs_session_id  — FK lookup
--   idx_ai_decision_logs_created_at  — time-range queries (DESC for recency)
--   idx_ai_decision_logs_plans_match — quick filter for disagreement rows
--   idx_ai_decision_logs_live_gin    — JSONB containment on live_plan
--   idx_ai_decision_logs_shadow_gin  — JSONB containment on shadow_plan
--   idx_ai_decision_logs_context_gin — JSONB containment on context
--
-- Run AFTER: 20240101000001_create_sessions.sql
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.ai_decision_logs (
  id              uuid        NOT NULL DEFAULT gen_random_uuid(),
  session_id      uuid        NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  page_type       text        NOT NULL,
  live_provider   text        NOT NULL,
  live_plan       jsonb       NOT NULL,
  shadow_provider text        NOT NULL,
  shadow_plan     jsonb       NOT NULL,
  plans_match     boolean     NOT NULL,
  context         jsonb       NOT NULL,

  CONSTRAINT ai_decision_logs_pkey       PRIMARY KEY (id),
  CONSTRAINT ai_decision_logs_session_fk FOREIGN KEY (session_id)
    REFERENCES public.sessions (id)
    ON DELETE CASCADE
);

-- ── Indexes ───────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_ai_decision_logs_session_id
  ON public.ai_decision_logs (session_id);

CREATE INDEX IF NOT EXISTS idx_ai_decision_logs_created_at
  ON public.ai_decision_logs (created_at DESC);

-- Fast filter for rows where the providers disagreed.
CREATE INDEX IF NOT EXISTS idx_ai_decision_logs_plans_match
  ON public.ai_decision_logs (plans_match);

-- GIN indexes for JSONB containment and key-existence queries on all three
-- JSONB columns. Enables queries like:
--   WHERE live_plan @> '{"heroKey": "hero_google_problem"}'
--   WHERE context @> '{"source": "linkedin"}'
CREATE INDEX IF NOT EXISTS idx_ai_decision_logs_live_gin
  ON public.ai_decision_logs USING gin (live_plan);

CREATE INDEX IF NOT EXISTS idx_ai_decision_logs_shadow_gin
  ON public.ai_decision_logs USING gin (shadow_plan);

CREATE INDEX IF NOT EXISTS idx_ai_decision_logs_context_gin
  ON public.ai_decision_logs USING gin (context);

-- ── Row Level Security ────────────────────────────────────────────────────────

ALTER TABLE public.ai_decision_logs ENABLE ROW LEVEL SECURITY;

-- No browser-accessible policies — service-role only.

-- ── Comments ──────────────────────────────────────────────────────────────────

COMMENT ON TABLE  public.ai_decision_logs                  IS 'Shadow-mode log comparing live (rules) decisions with parallel AI provider decisions. Written post-response; does not affect rendered output.';
COMMENT ON COLUMN public.ai_decision_logs.id               IS 'UUID primary key, generated by Postgres.';
COMMENT ON COLUMN public.ai_decision_logs.session_id       IS 'FK to sessions.id; cascades on delete.';
COMMENT ON COLUMN public.ai_decision_logs.created_at       IS 'Row timestamp, set by Postgres.';
COMMENT ON COLUMN public.ai_decision_logs.page_type        IS 'Page the decision was made for, e.g. homepage.';
COMMENT ON COLUMN public.ai_decision_logs.live_provider    IS 'Name of the provider that produced the rendered plan, e.g. rules.';
COMMENT ON COLUMN public.ai_decision_logs.live_plan        IS 'JSONB snapshot of the rendered ExperiencePlan { heroKey, proofKey, ctaKey, reason }.';
COMMENT ON COLUMN public.ai_decision_logs.shadow_provider  IS 'Name of the AI provider that ran in shadow, e.g. claude or openai.';
COMMENT ON COLUMN public.ai_decision_logs.shadow_plan      IS 'JSONB snapshot of the AI ExperiencePlan { heroKey, proofKey, ctaKey, reason, confidence? }.';
COMMENT ON COLUMN public.ai_decision_logs.plans_match      IS 'True when heroKey, proofKey, and ctaKey are identical across live and shadow plans.';
COMMENT ON COLUMN public.ai_decision_logs.context          IS 'JSONB snapshot of the VisitorContext at decision time { source, device, visitType, utm*, referrer, pathname }.';
