-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: create served_variants table
-- ─────────────────────────────────────────────────────────────────────────────
--
-- Records the variant set selected by the decision engine for each session.
-- Enables analytics queries such as "which hero variant was served most often
-- to LinkedIn visitors?" and "how many sessions used the fallback plan?".
--
-- ─── Column reference ────────────────────────────────────────────────────────
--
--   id         — UUID PK, generated by Postgres
--   session_id — FK to sessions.id; ON DELETE CASCADE so that deleting a
--                session also removes its variant record
--   created_at — timestamp when the variant set was persisted
--   hero_key   — selected hero variant, e.g. "hero_google_problem"
--   proof_key  — selected proof variant, e.g. "proof_cases"
--   cta_key    — selected CTA variant, e.g. "cta_meeting"
--   reason     — human-readable rule explanation from the decision engine
--
-- ─── Indexes ─────────────────────────────────────────────────────────────────
--
--   idx_served_variants_session_id — FK lookup (standard practice)
--   idx_served_variants_hero_key   — filter by hero variant for analytics
--   idx_served_variants_cta_key    — filter by CTA variant for conversion funnels
--
-- Run AFTER: 20240101000001_create_sessions.sql
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.served_variants (
  id         uuid        NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid        NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  hero_key   text        NOT NULL,
  proof_key  text        NOT NULL,
  cta_key    text        NOT NULL,
  reason     text        NOT NULL,

  CONSTRAINT served_variants_pkey       PRIMARY KEY (id),
  CONSTRAINT served_variants_session_fk FOREIGN KEY (session_id)
    REFERENCES public.sessions (id)
    ON DELETE CASCADE
);

-- ── Indexes ───────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_served_variants_session_id
  ON public.served_variants (session_id);

CREATE INDEX IF NOT EXISTS idx_served_variants_hero_key
  ON public.served_variants (hero_key);

CREATE INDEX IF NOT EXISTS idx_served_variants_cta_key
  ON public.served_variants (cta_key);

-- ── Row Level Security ────────────────────────────────────────────────────────

ALTER TABLE public.served_variants ENABLE ROW LEVEL SECURITY;

-- No browser-accessible policies — service-role only.

-- ── Comments ──────────────────────────────────────────────────────────────────

COMMENT ON TABLE  public.served_variants            IS 'Records the variant set served to each session by the decision engine.';
COMMENT ON COLUMN public.served_variants.id         IS 'UUID primary key, generated by Postgres.';
COMMENT ON COLUMN public.served_variants.session_id IS 'FK to sessions.id; cascades on delete.';
COMMENT ON COLUMN public.served_variants.created_at IS 'Timestamp when the variant set was persisted.';
COMMENT ON COLUMN public.served_variants.hero_key   IS 'Selected hero variant key, e.g. hero_google_problem.';
COMMENT ON COLUMN public.served_variants.proof_key  IS 'Selected proof variant key, e.g. proof_cases.';
COMMENT ON COLUMN public.served_variants.cta_key    IS 'Selected CTA variant key, e.g. cta_meeting.';
COMMENT ON COLUMN public.served_variants.reason     IS 'Human-readable explanation of why this plan was selected.';
