-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: create sessions table
-- ─────────────────────────────────────────────────────────────────────────────
--
-- Records one row per visitor request to the adaptive homepage.
-- Captures the resolved visitor context so that served variants and
-- downstream events can be attributed back to the originating signal set.
--
-- ─── Column reference ────────────────────────────────────────────────────────
--
--   id           — UUID PK, generated by Postgres (no application round-trip)
--   created_at   — request timestamp, set by Postgres
--   source       — resolved traffic source: linkedin | google | direct | unknown
--   device       — device class: mobile | desktop
--   visit_type   — first or repeat visit: new | returning
--   pathname     — URL path that triggered the session, e.g. "/"
--   referrer     — full Referer header value, null if absent
--   utm_source   — utm_source query parameter, null if absent
--   utm_medium   — utm_medium query parameter, null if absent
--   utm_campaign — utm_campaign query parameter, null if absent
--
-- ─── Indexes ─────────────────────────────────────────────────────────────────
--
--   idx_sessions_created_at — supports time-range analytics queries
--   idx_sessions_source     — supports filtering by traffic source
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.sessions (
  id           uuid        NOT NULL DEFAULT gen_random_uuid(),
  created_at   timestamptz NOT NULL DEFAULT now(),
  source       text        NOT NULL,
  device       text        NOT NULL,
  visit_type   text        NOT NULL,
  pathname     text        NOT NULL,
  referrer     text,
  utm_source   text,
  utm_medium   text,
  utm_campaign text,

  CONSTRAINT sessions_pkey PRIMARY KEY (id)
);

-- ── Indexes ───────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_sessions_created_at
  ON public.sessions (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_sessions_source
  ON public.sessions (source);

-- ── Row Level Security ────────────────────────────────────────────────────────
-- All writes come from the server-side service-role client, which bypasses RLS.
-- Enable RLS anyway so that no anon or authenticated user can read/write rows
-- directly from the browser via the anon key.

ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;

-- No SELECT/INSERT/UPDATE/DELETE policies are created intentionally.
-- Only the service-role key (bypasses RLS) is permitted to access this table.

-- ── Comments ──────────────────────────────────────────────────────────────────

COMMENT ON TABLE  public.sessions              IS 'One row per adaptive homepage visitor request.';
COMMENT ON COLUMN public.sessions.id           IS 'UUID primary key, generated by Postgres.';
COMMENT ON COLUMN public.sessions.created_at   IS 'Request timestamp, set by Postgres.';
COMMENT ON COLUMN public.sessions.source       IS 'Resolved traffic source: linkedin | google | direct | unknown.';
COMMENT ON COLUMN public.sessions.device       IS 'Device class: mobile | desktop.';
COMMENT ON COLUMN public.sessions.visit_type   IS 'First or repeat visit: new | returning.';
COMMENT ON COLUMN public.sessions.pathname     IS 'URL pathname that triggered the session.';
COMMENT ON COLUMN public.sessions.referrer     IS 'Full Referer header value, null if absent.';
COMMENT ON COLUMN public.sessions.utm_source   IS 'utm_source query parameter.';
COMMENT ON COLUMN public.sessions.utm_medium   IS 'utm_medium query parameter.';
COMMENT ON COLUMN public.sessions.utm_campaign IS 'utm_campaign query parameter.';
