/**
 * Migration 064 — Demo instances: add v2 content columns
 *
 * Adds four nullable JSONB columns to public.demo_instances to support
 * the v2 AI-generated bilingual content pipeline:
 *
 *   content_en    — DemoPageContent (English) generated by Claude
 *   content_nl    — DemoPageContent (Dutch)   generated by Claude
 *   brand_signals — BrandSignals extracted from the prospect's HTML
 *   page_images   — DemoImages (hero / services / cases URLs from Unsplash)
 *
 * All columns are nullable so that:
 *   1. Existing rows are unaffected (NULL = pre-v2 demo, viewer falls back to legacy rendering)
 *   2. New rows set them when AI generation succeeds; leave them NULL on failure
 *
 * Idempotent: ADD COLUMN IF NOT EXISTS is safe to re-run.
 */

ALTER TABLE public.demo_instances
  ADD COLUMN IF NOT EXISTS content_en    JSONB,
  ADD COLUMN IF NOT EXISTS content_nl    JSONB,
  ADD COLUMN IF NOT EXISTS brand_signals JSONB,
  ADD COLUMN IF NOT EXISTS page_images   JSONB;

COMMENT ON COLUMN public.demo_instances.content_en IS
  'AI-generated English DemoPageContent (hero, services, proof, cases, cta, pricing, careers, scenarioOverrides). NULL for pre-v2 demos.';

COMMENT ON COLUMN public.demo_instances.content_nl IS
  'AI-generated Dutch DemoPageContent. NULL for pre-v2 demos or when NL generation failed.';

COMMENT ON COLUMN public.demo_instances.brand_signals IS
  'BrandSignals extracted from the prospect site: primary colour, fonts, nav links, page structure hints.';

COMMENT ON COLUMN public.demo_instances.page_images IS
  'DemoImages: curated Unsplash image URLs for hero, services, and cases sections.';
