-- migration 071 — billing_defaults ensure
--
-- Belt-and-suspenders migration that guarantees billing_defaults exists and
-- contains its seed row, regardless of whether migration 065 applied cleanly.
--
-- ─── Why this exists ─────────────────────────────────────────────────────────
--
--   Migration 065 (billing_plans_defaults) creates billing_defaults.  However,
--   if that migration failed mid-transaction (e.g. a later ALTER TABLE statement
--   referenced a table that didn't exist yet), the entire transaction rolls back
--   — including the CREATE TABLE billing_defaults that happened earlier in the
--   same file.  The admin page at /admin/platform/billing/defaults then shows
--   the amber "Migration 065 not yet applied" warning even after other
--   migrations (066–070) have been applied successfully.
--
--   This migration uses CREATE TABLE IF NOT EXISTS + INSERT … ON CONFLICT DO
--   NOTHING so it is 100% idempotent whether or not 065 has been applied.
--   Running it when billing_defaults already exists is a safe no-op.
--
-- ─── id vs key ────────────────────────────────────────────────────────────────
--
--   id  — UUID primary key, auto-generated by gen_random_uuid().
--          NEVER set id to a string literal such as 'default'.
--   key — text column, stable string anchor for the singleton row.
--          Use key = 'default' in all queries and upserts.
--
-- ─── Canonical schema ─────────────────────────────────────────────────────────
--
--   id                       UUID PRIMARY KEY DEFAULT gen_random_uuid()
--   key                      TEXT NOT NULL DEFAULT 'default'   ← stable anchor
--   currency                 TEXT NOT NULL DEFAULT 'eur'
--   low_balance_threshold    NUMERIC(12,3)  — EUR, wallet notification trigger
--   auto_reload_trigger      NUMERIC(12,3)  — EUR, auto top-up activation level
--   auto_reload_amount       NUMERIC(12,3)  — EUR, amount per auto-reload event
--   monthly_auto_reload_cap  NUMERIC(12,3)  — EUR, monthly cap; NULL = unlimited
--   created_at               TIMESTAMPTZ NOT NULL DEFAULT now()
--   updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()

-- ── Create table if absent ────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS billing_defaults (
  id                        UUID              PRIMARY KEY DEFAULT gen_random_uuid(),
  key                       TEXT              NOT NULL DEFAULT 'default',
  currency                  TEXT              NOT NULL DEFAULT 'eur',
  low_balance_threshold     NUMERIC(12, 3)    NOT NULL DEFAULT 3.000
                                              CHECK (low_balance_threshold >= 0),
  auto_reload_trigger       NUMERIC(12, 3)    NOT NULL DEFAULT 2.000
                                              CHECK (auto_reload_trigger >= 0),
  auto_reload_amount        NUMERIC(12, 3)    NOT NULL DEFAULT 22.000
                                              CHECK (auto_reload_amount >= 0),
  monthly_auto_reload_cap   NUMERIC(12, 3)
                                              CHECK (monthly_auto_reload_cap IS NULL OR monthly_auto_reload_cap >= 0),
  created_at                TIMESTAMPTZ       NOT NULL DEFAULT now(),
  updated_at                TIMESTAMPTZ       NOT NULL DEFAULT now()
);

-- When billing_defaults was previously created with id UUID but without a
-- DEFAULT, ensure gen_random_uuid() is set so that INSERT without an explicit
-- id value works correctly.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'billing_defaults'
      AND column_name = 'id' AND data_type = 'uuid'
  ) THEN
    ALTER TABLE billing_defaults ALTER COLUMN id SET DEFAULT gen_random_uuid();
  END IF;
END $$;

-- Add key column if the table was created by an older version of 065 that
-- used id TEXT and did not include this column.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name   = 'billing_defaults'
      AND column_name  = 'key'
  ) THEN
    ALTER TABLE billing_defaults
      ADD COLUMN key TEXT NOT NULL DEFAULT 'default';
  END IF;
END $$;

-- Add created_at if table was created by the original 065 which omitted it.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name   = 'billing_defaults'
      AND column_name  = 'created_at'
  ) THEN
    ALTER TABLE billing_defaults
      ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now();
  END IF;
END $$;

-- Add updated_at if somehow absent.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name   = 'billing_defaults'
      AND column_name  = 'updated_at'
  ) THEN
    ALTER TABLE billing_defaults
      ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT now();
  END IF;
END $$;

-- Unique index on key so that ON CONFLICT (key) works in the seed INSERT below.
-- Safe to run even if the index already exists (IF NOT EXISTS).
CREATE UNIQUE INDEX IF NOT EXISTS billing_defaults_key_uniq
  ON billing_defaults (key);

-- ── Seed the canonical default row ────────────────────────────────────────────
-- Keyed on `key`, not `id`.  id is auto-generated as UUID; key is the stable
-- string anchor.  ON CONFLICT (key) requires the unique index created above.

INSERT INTO billing_defaults (
  key,
  currency,
  low_balance_threshold,
  auto_reload_trigger,
  auto_reload_amount,
  monthly_auto_reload_cap
)
VALUES (
  'default',
  'eur',
  3.000,
  2.000,
  22.000,
  NULL
)
ON CONFLICT (key) DO NOTHING;

-- ── Row-level security ────────────────────────────────────────────────────────

ALTER TABLE billing_defaults ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'billing_defaults'
      AND policyname = 'service_role_all_billing_defaults'
  ) THEN
    CREATE POLICY "service_role_all_billing_defaults"
      ON billing_defaults FOR ALL TO service_role
      USING (true) WITH CHECK (true);
  END IF;
END $$;
