-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: create events table
-- ─────────────────────────────────────────────────────────────────────────────
--
-- Lightweight named-event log tied to a session.
-- Supports page-level analytics and future funnel analysis:
--   page_view      — fired on every adaptive homepage render
--   cta_click      — fired when a visitor clicks a primary CTA
--   form_submit    — fired when the contact form is submitted
--
-- ─── Column reference ────────────────────────────────────────────────────────
--
--   id         — UUID PK, generated by Postgres
--   session_id — FK to sessions.id; ON DELETE CASCADE
--   created_at — event timestamp, set by Postgres
--   event_type — snake_case event name, e.g. "page_view"
--   payload    — open JSONB metadata; defaults to {}
--
-- ─── Payload convention ──────────────────────────────────────────────────────
--
--   Keep payload keys snake_case and flat for easy querying:
--     { "variant_key": "hero_google_problem", "position": "above_fold" }
--
--   Use Postgres JSONB operators in analytics queries:
--     SELECT * FROM events WHERE payload->>'variant_key' = 'hero_google_problem';
--
-- ─── Indexes ─────────────────────────────────────────────────────────────────
--
--   idx_events_session_id  — FK lookup
--   idx_events_event_type  — filter by event type for funnel queries
--   idx_events_created_at  — time-range queries
--   idx_events_payload_gin — JSONB containment / key-existence queries
--
-- Run AFTER: 20240101000001_create_sessions.sql
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.events (
  id         uuid        NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid        NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  event_type text        NOT NULL,
  payload    jsonb       NOT NULL DEFAULT '{}'::jsonb,

  CONSTRAINT events_pkey       PRIMARY KEY (id),
  CONSTRAINT events_session_fk FOREIGN KEY (session_id)
    REFERENCES public.sessions (id)
    ON DELETE CASCADE
);

-- ── Indexes ───────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_events_session_id
  ON public.events (session_id);

CREATE INDEX IF NOT EXISTS idx_events_event_type
  ON public.events (event_type);

CREATE INDEX IF NOT EXISTS idx_events_created_at
  ON public.events (created_at DESC);

-- GIN index for JSONB containment and key-existence queries.
CREATE INDEX IF NOT EXISTS idx_events_payload_gin
  ON public.events USING gin (payload);

-- ── Row Level Security ────────────────────────────────────────────────────────

ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;

-- No browser-accessible policies — service-role only.

-- ── Comments ──────────────────────────────────────────────────────────────────

COMMENT ON TABLE  public.events            IS 'Named events tied to a visitor session — page views, CTA clicks, form submits, etc.';
COMMENT ON COLUMN public.events.id         IS 'UUID primary key, generated by Postgres.';
COMMENT ON COLUMN public.events.session_id IS 'FK to sessions.id; cascades on delete.';
COMMENT ON COLUMN public.events.created_at IS 'Event timestamp, set by Postgres.';
COMMENT ON COLUMN public.events.event_type IS 'Snake-case event name, e.g. page_view or cta_click.';
COMMENT ON COLUMN public.events.payload    IS 'Open JSONB metadata for the event; defaults to {}.';
