-- ============================================================================
-- Migration 048: Prospect Demo Instances
--
-- Stores temporary, auto-expiring demo sites generated from a prospect URL.
-- Each row represents one "Prospect Demo" — a self-contained personalisation
-- preview generated by the Mr. Chameleon sales tool.
--
-- Design:
--   • No FK to tenant_settings — demos are fully isolated and anonymous.
--   • scenarios is JSONB — 5 pre-generated scenarios stored inline.
--   • expires_at is enforced by the API route (returns 410 Gone on expiry).
--   • No RLS — demos are public-read via a server-side API route.
--     The API route validates expiry; no sensitive data is stored.
--   • Cleanup: expired rows can be purged with a cron job or pg_cron:
--       DELETE FROM public.demo_instances WHERE expires_at < now();
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.demo_instances (
  -- ── Identity ─────────────────────────────────────────────────────────────
  id              text        PRIMARY KEY,  -- short random ID used in /demo/[id] URL

  -- ── Source site metadata ──────────────────────────────────────────────────
  source_url      text        NOT NULL,     -- the URL the demo was generated from
  site_name       text        NOT NULL DEFAULT '',  -- extracted from <title> / og:title
  site_description text       NOT NULL DEFAULT '',  -- extracted from meta description / og:description
  site_category   text        NOT NULL DEFAULT 'general',
                              -- detected industry: b2b_saas | agency | ecommerce | recruitment | general

  -- ── Brand signals (extracted from source site) ────────────────────────────
  primary_color   text        NOT NULL DEFAULT '#3b82f6',  -- hex color for theming
  secondary_color text        NOT NULL DEFAULT '#1e3a8a',  -- darker variant
  logo_url        text,       -- og:image or detected logo
  favicon_url     text,       -- favicon href from source

  -- ── Generated content ─────────────────────────────────────────────────────
  -- Array of DemoScenario objects (5 entries for v1):
  --   id, label, description, context{}, experience{ hero, proof, cta }
  scenarios       jsonb       NOT NULL DEFAULT '[]',

  -- ── Lifecycle ─────────────────────────────────────────────────────────────
  created_at      timestamptz NOT NULL DEFAULT now(),
  expires_at      timestamptz NOT NULL,   -- typically now() + 7 days
  view_count      integer     NOT NULL DEFAULT 0,

  -- ── Generator metadata ────────────────────────────────────────────────────
  -- Stored for analytics and debugging; not shown in the demo viewer.
  generated_by    text,       -- admin user email or 'system'
  generation_ms   integer     -- how long the generation took (wall clock)
);

-- ── Indexes ───────────────────────────────────────────────────────────────────

-- Fast lookup for cleanup job and expiry check in API route.
CREATE INDEX IF NOT EXISTS demo_instances_expires_idx
  ON public.demo_instances (expires_at);

-- Fast lookup by source URL (for deduplication / list-by-site in admin).
CREATE INDEX IF NOT EXISTS demo_instances_source_url_idx
  ON public.demo_instances (source_url);

-- ── Comments ──────────────────────────────────────────────────────────────────

COMMENT ON TABLE public.demo_instances IS
  'Temporary prospect demo sites generated from a URL. One row per demo. '
  'Auto-expires — safe to purge after expires_at passes. '
  'Readable publicly via /api/demo/[id] (expiry enforced in code).';

COMMENT ON COLUMN public.demo_instances.id IS
  'Short random ID used in /demo/[id] URL. 12 alphanumeric chars.';

DO $$ BEGIN COMMENT ON COLUMN public.demo_instances.scenarios IS
  'JSON array of 5 DemoScenario objects. Each has: id, label, description, '
  'context (simulated visitor context), and experience { hero, proof, cta }.';
EXCEPTION WHEN undefined_column OR undefined_table THEN NULL; END $$;

DO $$ BEGIN COMMENT ON COLUMN public.demo_instances.primary_color IS
  'Primary brand color extracted from meta[name=theme-color] or favicon analysis. '
  'Falls back to a category-appropriate default if extraction fails.';
EXCEPTION WHEN undefined_column OR undefined_table THEN NULL; END $$;
