/**
 * interest-profiles/behavioral-scoring.ts
 *
 * Event-driven behavioral scoring engine for interest profiles.
 *
 * ─── Relationship to scoring.ts ──────────────────────────────────────────────
 *
 *   scoring.ts           — keyword-cloud model (server-side, UTM/meta keywords)
 *   behavioral-scoring.ts — event-signal model  (client-side, real behavior)
 *
 *   Both produce interestPrimary / interestConfidence context variables.
 *   Behavioral scores are richer and more actionable — they accumulate across
 *   the entire session and fire on concrete user actions (clicks, form starts,
 *   repeat visits) rather than just keyword co-occurrence.
 *
 * ─── Scoring model ────────────────────────────────────────────────────────────
 *
 *   Each behavioral event fires one or more (profileKey, points) pairs as
 *   defined by the signal map.  Points accumulate per profile, capped at
 *   MAX_SCORE_PER_PROFILE.
 *
 *   Profiles cross SCORE_THRESHOLDS to become "weakly" or "strongly" active.
 *   Multiple profiles can be active simultaneously.  The profile with the
 *   highest score is the "dominant" profile.
 *
 * ─── Decay ────────────────────────────────────────────────────────────────────
 *
 *   Exponential half-life decay is applied lazily when state is loaded.
 *   A profile that received 40 pts but received no events for 24 h has 20 pts;
 *   after 48 h it has 10 pts (below STRONG threshold).
 *
 *   Half-life: DECAY_HALF_LIFE_MS (default 24 h).
 *
 * ─── Thresholds ───────────────────────────────────────────────────────────────
 *
 *   WEAK   ≥ 15 pts   Profile is weakly activated
 *   STRONG ≥ 40 pts   Profile is strongly activated
 *
 * ─── Event types ──────────────────────────────────────────────────────────────
 *
 *   page_view       Visitor views a page              → URL-based signals
 *   repeat_visit    Visitor returns to a viewed URL   → URL signals × 1.5
 *   cta_click       Visitor clicks a CTA button       → label-based signals
 *   form_start      Visitor starts a form             → URL signals × 0.5
 *   form_submit     Visitor submits a form            → URL signals × 2.0
 *
 * ─── Pure functions — no browser APIs ───────────────────────────────────────
 *
 *   All functions in this file are pure (no DOM, no localStorage).
 *   Browser persistence is handled by session-store.ts.
 */

// ── Constants ─────────────────────────────────────────────────────────────────

/** Points required for weak / strong activation. */
export const SCORE_THRESHOLDS = {
  WEAK:   15,
  STRONG: 40,
} as const;

/** Exponential decay half-life: after this many ms, points are halved. */
export const DECAY_HALF_LIFE_MS = 24 * 60 * 60 * 1000; // 24 hours

/** Maximum points a single profile can accumulate (prevents runaway scores). */
export const MAX_SCORE_PER_PROFILE = 200;

/** Maximum number of score contributions stored per profile (for debug). */
export const MAX_STORED_CONTRIBUTIONS = 12;

// ── Event types ───────────────────────────────────────────────────────────────

export type BehavioralEventType =
  | "page_view"
  | "repeat_visit"
  | "cta_click"
  | "form_start"
  | "form_submit";

// ── Core event shape ──────────────────────────────────────────────────────────

export interface BehavioralEvent {
  /** What kind of user action this is. */
  type:   BehavioralEventType;
  /**
   * The page URL or pathname.
   * Required for page_view, repeat_visit, form_start, form_submit.
   * Optional for cta_click (used to augment label signals with URL context).
   */
  url?:   string;
  /**
   * CTA action label — e.g. "pricing", "apply", "add_to_cart", "book_viewing".
   * Required for cta_click.
   */
  label?: string;
  /** Unix milliseconds. */
  at:     number;
}

// ── Signal shape ──────────────────────────────────────────────────────────────

/**
 * A resolved signal: the (profileKey, points, reason) triple that
 * will be applied to the scoring state for a given event.
 *
 * Generated by resolveSignals() in signal-map.ts.
 */
export interface ResolvedSignal {
  profileKey: string;
  points:     number;
  /** Human-readable explanation, e.g. "page_view:/pricing — pricing page". */
  reason:     string;
}

// ── State shapes ──────────────────────────────────────────────────────────────

/**
 * A single scored contribution to a profile's total — stored for debug display.
 */
export interface ScoreContribution {
  profileKey: string;
  points:     number;
  /** Short human-readable reason for this contribution. */
  reason:     string;
  /** Unix ms when this contribution was added. */
  at:         number;
}

/**
 * Per-profile scoring state.
 */
export interface ProfileScoreEntry {
  key:           string;
  /** Current accumulated points (after any decay applied on load). */
  points:        number;
  /** Unix ms of the most recent event contributing to this profile. */
  lastEventAt:   number;
  /** Most recent up to MAX_STORED_CONTRIBUTIONS contributions (newest first). */
  contributions: ScoreContribution[];
}

/**
 * Complete behavioral scoring state.
 * Persisted in localStorage between page navigations.
 */
export interface BehavioralScoreState {
  /** Schema version — increment when breaking changes are made. */
  version:     1;
  /** Stable visitor identifier (from session-store.ts). */
  visitorId:   string;
  /** Unix ms of last state mutation. */
  updatedAt:   number;
  /** Per-profile score entries, keyed by profileKey. */
  profiles:    Record<string, ProfileScoreEntry>;
  /**
   * Number of times each pathname was visited this session.
   * Used to detect repeat visits and apply the repeat multiplier.
   */
  visitedUrls: Record<string, number>;
}

// ── Output shapes ─────────────────────────────────────────────────────────────

export type ActivationLevel = "none" | "weak" | "strong" | "disabled";

/** An interest profile that has crossed a scoring threshold. */
export interface ActiveProfile {
  key:        string;
  points:     number;
  activation: "weak" | "strong";
  /** True for the profile with the highest score. */
  isDominant: boolean;
}

/** Per-profile debug entry used in the debug snapshot. */
export interface ProfileDebugEntry {
  key:           string;
  points:        number;
  activation:    ActivationLevel;
  contributions: ScoreContribution[];
}

/** Full debug snapshot — everything needed to explain why profiles are active. */
export interface ScoringDebugSnapshot {
  /** Unix ms when this snapshot was taken. */
  timestamp:       number;
  visitorId:       string;
  /** Key of the dominant (highest-scoring active) profile, or null. */
  dominant:        string | null;
  /** Profiles above WEAK threshold, sorted by score descending. */
  activeProfiles:  ActiveProfile[];
  /** All scored profiles that are enabled for this tenant (including sub-threshold). */
  allScores:       ProfileDebugEntry[];
  /**
   * Profiles that have accumulated scores but are disabled for the tenant.
   * Empty when no `enabledKeys` filter is passed to buildDebugSnapshot.
   */
  disabledProfiles: ProfileDebugEntry[];
  /** Human-readable decay note. */
  decayNote:       string;
  /** Number of unique URLs visited this session. */
  urlsVisited:     number;
}

// ── State helpers ─────────────────────────────────────────────────────────────

/** Create a fresh, empty scoring state for a new visitor. */
export function createEmptyState(visitorId: string): BehavioralScoreState {
  return {
    version:     1,
    visitorId,
    updatedAt:   Date.now(),
    profiles:    {},
    visitedUrls: {},
  };
}

/** Empty profile entry for a key never scored before. */
function emptyProfileEntry(key: string, now: number): ProfileScoreEntry {
  return { key, points: 0, lastEventAt: now, contributions: [] };
}

// ── Decay ─────────────────────────────────────────────────────────────────────

/**
 * Applies exponential decay to a single profile entry.
 *
 * Formula: decayedPoints = points × 0.5^(elapsed / HALF_LIFE)
 * Applied lazily — only when state is loaded from storage.
 */
function decayEntry(
  entry: ProfileScoreEntry,
  now:   number,
): ProfileScoreEntry {
  const elapsed = now - entry.lastEventAt;
  if (elapsed <= 0 || entry.points === 0) return entry;

  const decayFactor   = Math.pow(0.5, elapsed / DECAY_HALF_LIFE_MS);
  const decayedPoints = Math.max(0, Math.round(entry.points * decayFactor * 10) / 10);

  return { ...entry, points: decayedPoints };
}

/**
 * Applies decay to all profiles in a state object.
 * Call this immediately after loading state from storage.
 */
export function applyDecayToState(
  state: BehavioralScoreState,
  now:   number = Date.now(),
): BehavioralScoreState {
  const profiles: Record<string, ProfileScoreEntry> = {};
  for (const [key, entry] of Object.entries(state.profiles)) {
    profiles[key] = decayEntry(entry, now);
  }
  return { ...state, profiles };
}

// ── Score application ─────────────────────────────────────────────────────────

/**
 * Applies a resolved list of signals to the current state.
 *
 * Returns a new (immutable) state — does not mutate the input.
 * Signals come from resolveSignals() in signal-map.ts.
 */
export function applySignals(
  state:   BehavioralScoreState,
  signals: ResolvedSignal[],
  now:     number = Date.now(),
): BehavioralScoreState {
  if (signals.length === 0) return state;

  const profiles = { ...state.profiles };

  for (const signal of signals) {
    const existing    = profiles[signal.profileKey] ?? emptyProfileEntry(signal.profileKey, now);
    const newPoints   = Math.min(MAX_SCORE_PER_PROFILE, existing.points + signal.points);

    const contribution: ScoreContribution = {
      profileKey: signal.profileKey,
      points:     signal.points,
      reason:     signal.reason,
      at:         now,
    };

    // Keep most-recent contributions first; trim to cap.
    const contributions = [contribution, ...existing.contributions].slice(
      0,
      MAX_STORED_CONTRIBUTIONS,
    );

    profiles[signal.profileKey] = {
      ...existing,
      points:        newPoints,
      lastEventAt:   now,
      contributions,
    };
  }

  return { ...state, profiles, updatedAt: now };
}

/**
 * Records a URL visit into state and returns the (possibly updated) state.
 * Returns `isRepeat: true` when this URL has been visited before.
 */
export function recordUrlVisit(
  state:    BehavioralScoreState,
  pathname: string,
  now:      number = Date.now(),
): { state: BehavioralScoreState; isRepeat: boolean } {
  const count   = state.visitedUrls[pathname] ?? 0;
  const isRepeat = count > 0;
  const visitedUrls = { ...state.visitedUrls, [pathname]: count + 1 };
  return { state: { ...state, visitedUrls, updatedAt: now }, isRepeat };
}

// ── Activation ────────────────────────────────────────────────────────────────

/** Returns the activation level for a given point total. */
export function getActivationLevel(points: number): ActivationLevel {
  if (points >= SCORE_THRESHOLDS.STRONG) return "strong";
  if (points >= SCORE_THRESHOLDS.WEAK)   return "weak";
  return "none";
}

/**
 * Returns all profiles above the WEAK threshold, sorted by score descending.
 * The first entry (if any) has `isDominant: true`.
 *
 * @param enabledKeys When provided, only profiles whose key is in this set are
 *   returned.  Profiles disabled at the tenant level (absent from enabledKeys)
 *   are silently excluded — they do not activate, cannot be dominant, and do
 *   not appear in contextVars.  Pass undefined to include all profiles.
 */
export function getActiveProfiles(
  state:       BehavioralScoreState,
  enabledKeys?: ReadonlySet<string>,
): ActiveProfile[] {
  const entries = Object.values(state.profiles)
    .filter((e) => e.points >= SCORE_THRESHOLDS.WEAK)
    .filter((e) => !enabledKeys || enabledKeys.has(e.key))
    .sort((a, b) => b.points - a.points);

  return entries.map((e, i): ActiveProfile => ({
    key:        e.key,
    points:     e.points,
    activation: getActivationLevel(e.points) as "weak" | "strong",
    isDominant: i === 0,
  }));
}

/**
 * Returns the dominant (highest-scoring active) profile key, or null.
 * Disabled profiles (absent from enabledKeys) are never selected as dominant.
 */
export function getDominantProfile(
  state:       BehavioralScoreState,
  enabledKeys?: ReadonlySet<string>,
): string | null {
  const active = getActiveProfiles(state, enabledKeys);
  return active[0]?.key ?? null;
}

// ── Debug snapshot ────────────────────────────────────────────────────────────

/**
 * Builds a human-readable debug snapshot of the current scoring state.
 *
 * Exposed via useInterestScoring() hook and rendered by InterestDebugPanel.
 *
 * @param enabledKeys When provided, profiles absent from this set are moved to
 *   `disabledProfiles` in the snapshot so the debug panel can explain why they
 *   are not contributing to decisions.
 */
export function buildDebugSnapshot(
  state:       BehavioralScoreState,
  now:         number = Date.now(),
  enabledKeys?: ReadonlySet<string>,
): ScoringDebugSnapshot {
  const activeProfiles = getActiveProfiles(state, enabledKeys);
  const dominant       = activeProfiles[0]?.key ?? null;

  // All scored profiles that are ENABLED, sorted by points descending.
  const allScores: ProfileDebugEntry[] = Object.values(state.profiles)
    .filter((e) => !enabledKeys || enabledKeys.has(e.key))
    .sort((a, b) => b.points - a.points)
    .map((e): ProfileDebugEntry => ({
      key:           e.key,
      points:        e.points,
      activation:    getActivationLevel(e.points),
      contributions: e.contributions,
    }));

  // Profiles that have scores but are DISABLED for this tenant.
  const disabledProfiles: ProfileDebugEntry[] = enabledKeys
    ? Object.values(state.profiles)
        .filter((e) => !enabledKeys.has(e.key) && e.points > 0)
        .sort((a, b) => b.points - a.points)
        .map((e): ProfileDebugEntry => ({
          key:           e.key,
          points:        e.points,
          activation:    "disabled" as ActivationLevel,
          contributions: e.contributions,
        }))
    : [];

  // Compute decay age note using the most recently active profile.
  const latestEvent = Math.max(
    ...Object.values(state.profiles).map((e) => e.lastEventAt),
    state.updatedAt,
  );
  const msSinceLastEvent = now - latestEvent;
  const hoursSince       = Math.round(msSinceLastEvent / (60 * 60 * 1000));
  const decayNote = hoursSince < 1
    ? "Scores are fresh — no decay applied yet."
    : `${hoursSince}h since last event — decay applied (24h half-life).`;

  return {
    timestamp:       now,
    visitorId:       state.visitorId,
    dominant,
    activeProfiles,
    allScores,
    disabledProfiles,
    decayNote,
    urlsVisited:     Object.keys(state.visitedUrls).length,
  };
}

// ── Context variable bridge ───────────────────────────────────────────────────

/**
 * Converts behavioral scores into the same InterestContextVars shape as
 * the keyword-cloud scorer (scoring.ts), so they can feed the decision engine.
 *
 * Normalizes: points are divided by MAX_SCORE_PER_PROFILE (200) to produce
 * a 0–1 interestConfidence value consistent with the keyword scorer.
 *
 * @param enabledKeys When provided, disabled profiles are completely excluded
 *   from primary/secondary/perProfile output so the decision engine never sees
 *   them.
 */
export function behavioralScoresToContextVars(
  state:       BehavioralScoreState,
  enabledKeys?: ReadonlySet<string>,
): {
  interestPrimary:    string;
  interestSecondary:  string;
  interestConfidence: number;
  perProfile:         Record<string, number>;
} {
  const sorted = Object.values(state.profiles)
    .filter((e) => !enabledKeys || enabledKeys.has(e.key))
    .sort((a, b) => b.points - a.points);

  const primary   = sorted[0];
  const secondary = sorted[1];

  const perProfile: Record<string, number> = {};
  for (const entry of sorted) {
    const normalized = parseFloat(
      Math.min(1, entry.points / MAX_SCORE_PER_PROFILE).toFixed(4),
    );
    if (normalized > 0) perProfile[entry.key] = normalized;
  }

  const primaryNorm = primary
    ? Math.min(1, primary.points / MAX_SCORE_PER_PROFILE)
    : 0;

  return {
    interestPrimary:   primary?.points  >= SCORE_THRESHOLDS.WEAK ? primary.key  : "",
    interestSecondary: secondary?.points >= SCORE_THRESHOLDS.WEAK ? secondary.key : "",
    interestConfidence: parseFloat(primaryNorm.toFixed(2)),
    perProfile,
  };
}
