/**
 * Form Submissions Repository
 *
 * Encapsulates all database access for the `form_submissions` table.
 * A submission row is written by the /api/forms/[formKey] route handler
 * when FormDefinition.action.storeSubmissions is true.
 *
 * ─── Table schema ─────────────────────────────────────────────────────────────
 *
 *   form_submissions (
 *     id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
 *     created_at  timestamptz NOT NULL DEFAULT now(),
 *     form_key    text        NOT NULL,
 *     values      jsonb       NOT NULL,
 *     session_id  uuid        NULL REFERENCES sessions(id) ON DELETE SET NULL,
 *     tenant_id   text        NULL
 *   )
 *
 * ─── Error handling ───────────────────────────────────────────────────────────
 *
 *   Returns a `RepositoryResult<T>` — never throws.  Callers check `result.ok`
 *   and handle the error case without try/catch at every call site.
 *
 * ─── Usage ────────────────────────────────────────────────────────────────────
 *
 *   import { saveFormSubmission } from "@/data/repositories/form-submissions-repository";
 *
 *   const result = await saveFormSubmission({
 *     formKey:   "contact",
 *     values:    { name: "Jane", email: "jane@example.com", message: "Hello" },
 *     sessionId: "…uuid…",        // optional — omit when session is unavailable
 *     tenantId:  "acme",          // optional — omit for un-scoped submissions
 *   });
 *
 *   if (!result.ok) {
 *     // log the error, but do NOT block the submission response
 *     logger.warn("[forms] storage failed", { error: result.error });
 *   }
 */

import { getDb } from "../db";
import { logger } from "@/lib/logger";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { RepositoryResult } from "./sessions-repository";

// ── Row type ──────────────────────────────────────────────────────────────────

/**
 * Shape of a row returned from the `form_submissions` table.
 */
export interface FormSubmissionRow {
  /** UUID primary key, generated by the database. */
  id:         string;
  /** ISO-8601 timestamp set by the database on insert. */
  created_at: string;
  /** Registered form key, e.g. "contact" | "application" */
  form_key:   string;
  /** Validated, trimmed submission values keyed by field key. */
  values:     Record<string, string>;
  /** FK → sessions.id — nullable; absent for submissions without a platform session. */
  session_id: string | null;
  /** Owning tenant slug, e.g. "workengine". Null for legacy un-scoped rows. */
  tenant_id:  string | null;
}

// ── Input types ───────────────────────────────────────────────────────────────

/**
 * Data required to persist a validated form submission.
 */
export interface SaveFormSubmissionInput {
  /** Registered form key, e.g. "contact" | "application" */
  formKey:    string;
  /** Validated, trimmed field values keyed by field key. */
  values:     Record<string, string>;
  /**
   * Platform session ID from the visitor's `mc_session_id` cookie.
   * Omit (or pass null/undefined) when the session is not available.
   * The submission is always written; session_id is nullable.
   */
  sessionId?: string | null;
  /**
   * Tenant slug that owns this submission.
   * Omit (or pass null/undefined) for un-scoped / legacy submissions.
   */
  tenantId?:  string | null;
}

/**
 * Filters for listing submissions for a tenant.
 */
export interface ListFormSubmissionsInput {
  /** Tenant slug — required for scoped queries. */
  tenantId:  string;
  /** When provided, filter to this specific form key. */
  formKey?:  string;
  /** Full-text search across the JSONB values column. */
  search?:   string;
  /** ISO-8601 date lower bound (inclusive). */
  from?:     string;
  /** ISO-8601 date upper bound (inclusive). */
  to?:       string;
  /** Page size — defaults to 50. */
  limit?:    number;
  /** Zero-based row offset — defaults to 0. */
  offset?:   number;
}

/**
 * Paginated result of a form submissions list query.
 */
export interface FormSubmissionsPage {
  rows:  FormSubmissionRow[];
  total: number;
}

// ── Repository ────────────────────────────────────────────────────────────────

/**
 * Inserts a form submission row into the `form_submissions` table.
 *
 * Always returns a `RepositoryResult` — never throws.  Storage failures are
 * safe to log and swallow so the site never shows an error to the submitter
 * because of a DB write failing after successful validation.
 *
 * @param input  Submission data: formKey, validated values, optional sessionId.
 * @returns      RepositoryResult<FormSubmissionRow> — { ok: true, data } on success.
 */
export async function saveFormSubmission(
  input: SaveFormSubmissionInput,
): Promise<RepositoryResult<FormSubmissionRow>> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data, error } = await (getDb() as any)
    .from("form_submissions")
    .insert({
      form_key:   input.formKey,
      values:     input.values,
      session_id: input.sessionId ?? null,
      tenant_id:  input.tenantId  ?? null,
    })
    .select()
    .single();

  if (error) {
    logger.error("[form-submissions-repository] saveFormSubmission failed", {
      error:   (error as { message: string }).message,
      code:    (error as { code?: string }).code,
      formKey: input.formKey,
    });
    return { ok: false, error: (error as { message: string }).message };
  }

  return { ok: true, data: data as FormSubmissionRow };
}

/**
 * List form submissions for a tenant with optional filters and pagination.
 */
export async function listFormSubmissions(
  client: SupabaseClient,
  input: ListFormSubmissionsInput,
): Promise<RepositoryResult<FormSubmissionsPage>> {
  const limit  = input.limit  ?? 50;
  const offset = input.offset ?? 0;

  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let query = (client as any)
      .from("form_submissions")
      .select("*", { count: "exact" })
      .eq("tenant_id", input.tenantId)
      .order("created_at", { ascending: false });

    if (input.formKey) {
      query = query.eq("form_key", input.formKey);
    }

    if (input.from) {
      query = query.gte("created_at", input.from);
    }

    if (input.to) {
      // Add one day to make the `to` date inclusive at end-of-day.
      const toDate = new Date(input.to);
      toDate.setDate(toDate.getDate() + 1);
      query = query.lt("created_at", toDate.toISOString());
    }

    if (input.search) {
      // Search across the JSONB values column cast to text.
      query = query.ilike("values::text", `%${input.search}%`);
    }

    query = query.range(offset, offset + limit - 1);

    const { data, error, count } = await query;

    if (error) {
      logger.error("[form-submissions-repository] listFormSubmissions failed", {
        error:    (error as { message: string }).message,
        tenantId: input.tenantId,
      });
      return { ok: false, error: (error as { message: string }).message };
    }

    return {
      ok:   true,
      data: {
        rows:  (data ?? []) as FormSubmissionRow[],
        total: count ?? 0,
      },
    };
  } catch (err) {
    logger.error("[form-submissions-repository] listFormSubmissions unexpected error", {
      error: String(err),
    });
    return { ok: false, error: String(err) };
  }
}

/**
 * Fetch a single submission by ID, guarded by tenant ownership.
 */
export async function getFormSubmission(
  client: SupabaseClient,
  id:       string,
  tenantId: string,
): Promise<RepositoryResult<FormSubmissionRow>> {
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { data, error } = await (client as any)
      .from("form_submissions")
      .select("*")
      .eq("id",        id)
      .eq("tenant_id", tenantId)
      .single();

    if (error) {
      return { ok: false, error: (error as { message: string }).message };
    }

    return { ok: true, data: data as FormSubmissionRow };
  } catch (err) {
    return { ok: false, error: String(err) };
  }
}

/**
 * Delete a single submission, guarded by tenant ownership.
 */
export async function deleteFormSubmission(
  client:   SupabaseClient,
  id:       string,
  tenantId: string,
): Promise<RepositoryResult<{ deleted: boolean }>> {
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { error } = await (client as any)
      .from("form_submissions")
      .delete()
      .eq("id",        id)
      .eq("tenant_id", tenantId);

    if (error) {
      return { ok: false, error: (error as { message: string }).message };
    }

    return { ok: true, data: { deleted: true } };
  } catch (err) {
    return { ok: false, error: String(err) };
  }
}

/**
 * Delete all submissions older than `retentionDays` days for the given tenant.
 * Used by the GDPR purge cron.
 */
export async function purgeExpiredSubmissions(
  client:        SupabaseClient,
  tenantId:      string,
  retentionDays: number,
): Promise<RepositoryResult<{ deletedCount: number }>> {
  try {
    const cutoff = new Date();
    cutoff.setDate(cutoff.getDate() - retentionDays);

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { data, error } = await (client as any)
      .from("form_submissions")
      .delete()
      .eq("tenant_id", tenantId)
      .lt("created_at", cutoff.toISOString())
      .select("id");

    if (error) {
      return { ok: false, error: (error as { message: string }).message };
    }

    return { ok: true, data: { deletedCount: Array.isArray(data) ? data.length : 0 } };
  } catch (err) {
    return { ok: false, error: String(err) };
  }
}

/**
 * Iterate all tenants that have a `submissionRetentionDays` setting > 0,
 * and purge expired submissions for each.
 * Designed to be called by the /api/cron/form-submission-purge endpoint.
 */
export async function purgeAllExpiredSubmissions(
  client: SupabaseClient,
): Promise<RepositoryResult<{ totalDeleted: number }>> {
  try {
    // Load all tenant_form_settings rows that have a retentionDays value set.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const { data: rows, error } = await (client as any)
      .from("tenant_form_settings")
      .select("tenant_id, settings");

    if (error) {
      return { ok: false, error: (error as { message: string }).message };
    }

    let totalDeleted = 0;

    for (const row of (rows ?? []) as Array<{ tenant_id: string; settings: Record<string, unknown> }>) {
      const retention = row.settings?.submissionRetentionDays;
      if (typeof retention !== "number" || retention <= 0) continue;

      const result = await purgeExpiredSubmissions(client, row.tenant_id, retention);
      if (result.ok) {
        totalDeleted += result.data.deletedCount;
      } else {
        logger.warn("[form-submissions-repository] purgeAllExpiredSubmissions: tenant purge failed", {
          tenantId: row.tenant_id,
          error:    result.error,
        });
      }
    }

    return { ok: true, data: { totalDeleted } };
  } catch (err) {
    return { ok: false, error: String(err) };
  }
}
