/**
 * Sanity Schema — conversionVariant
 *
 * Defines the content structure for an adaptive conversion-focused block variant.
 * One document per variant key.  Each document contains a display headline,
 * supporting paragraph, 1–2 call-to-action buttons, and optional fields for
 * embedded forms and urgency copy.
 *
 * ─── Variant keys ─────────────────────────────────────────────────────────────
 *
 *   conversion_signup   Email / account signup form or direct CTA.
 *   conversion_demo     Demo request form or booking embed.
 *   conversion_contact  Contact / enquiry form.
 *
 * ─── Tenant-scoped identity ───────────────────────────────────────────────────
 *
 *   A variant is identified by the composite (tenantId, key) pair:
 *
 *     • The same key (e.g. "conversion_signup") is reusable across tenants.
 *       Each tenant maintains its own copy with tenant-specific copy/CTAs.
 *     • Uniqueness is enforced per-tenant: two documents may share a key only
 *       if they belong to different tenants.
 *     • tenantId absent → shared/platform variant, available to ALL tenants
 *       as a fallback when no tenant-specific document exists.
 *
 * ─── Resolution order (GROQ) ──────────────────────────────────────────────────
 *
 *   1. Tenant-specific document  (tenantId == $tenantId)  — highest priority
 *   2. Shared/platform document  (!defined(tenantId))     — fallback
 *
 *   Full query is generated by buildVariantQuery() in cms/queries/sanity/query-builder.ts.
 *
 * ─── Studio tabs ─────────────────────────────────────────────────────────────
 *
 *   Content             — headline, supporting copy, CTAs, form key, urgency label
 *   AI / Decision       — decisionMeta (audience, intent, goals, readiness gate)
 *   Identity & settings — tenant ID, variant key, layout, active flag
 *   Editorial tags      — sourceTags, stageTags
 *
 * ─── Field reference ──────────────────────────────────────────────────────────
 *
 *   tenantId      string   Optional. Tenant owner slug, e.g. "workengine".
 *                          Absent = shared platform variant served to all tenants.
 *   key           string   Required. Business key, e.g. "conversion_signup".
 *                          Unique within the same tenantId scope (not globally).
 *   layoutVariant string   Optional. Layout variant for the block renderer.
 *   title         string   Required. Display headline. ≤120 chars.
 *   text          text     Required. Supporting paragraph. ≤300 chars.
 *   ctas          array    Preferred. 1–2 CTA objects { label, href, variant? }.
 *   formKey       string   Optional. Key referencing an embedded form definition.
 *   urgencyLabel  string   Optional. Urgency / social-proof label, e.g. "Join 2,000+ teams".
 *   decisionMeta  object   Optional. AI / decision metadata (aiReady gate).
 *   sourceTags    array    Optional. Traffic-source editorial taxonomy.
 *   stageTags     array    Optional. Funnel-stage editorial taxonomy.
 *   isActive      boolean  Required. Default: true.
 */

import { defineField, defineType } from "sanity";

export default defineType({
  name:  "conversionVariant",
  title: "Conversion Variant",
  type:  "document",

  // ── Field groups (Studio tabs) ────────────────────────────────────────────
  groups: [
    { name: "content",   title: "Content",              default: true },
    { name: "ai",        title: "AI / Decision"                       },
    { name: "identity",  title: "Identity & settings"                 },
    { name: "editorial", title: "Editorial tags"                      },
  ],

  fields: [

    // ── Layout variant ── (identity group) ────────────────────────────────────
    defineField({
      name:  "layoutVariant",
      title: "Layout Variant",
      type:  "string",
      group: "identity",
      description:
        "Controls the structural layout of the conversion block. " +
        "The content (headline, text, CTAs, form) is the same regardless of layout.",
      options: {
        list: [
          { title: "Centered — headline + copy + CTAs (default)", value: "conversion_centered" },
          { title: "Split — copy left, form / CTA right",         value: "conversion_split"    },
          { title: "Card — contained card on neutral background",  value: "conversion_card"    },
          { title: "Modal — triggered via a button click",         value: "conversion_modal"   },
        ],
        layout: "radio",
      },
      initialValue: "conversion_centered",
    }),

    // ── Tenant ── (identity group) ─────────────────────────────────────────────
    defineField({
      name:  "tenantId",
      title: "Tenant ID",
      type:  "string",
      group: "identity",
      description:
        "Tenant that owns this variant, e.g. \"workengine\". " +
        "Leave blank for shared platform variants available to all tenants.",
      validation: (Rule) =>
        Rule.custom((value) => {
          if (!value) return true;
          if (!/^[a-z][a-z0-9-]*[a-z0-9]$|^[a-z]$/.test(value)) {
            return "Tenant ID must be lowercase letters, numbers, and hyphens only.";
          }
          return true;
        }),
    }),

    // ── Variant key ── (identity group) ───────────────────────────────────────
    defineField({
      name:  "key",
      title: "Variant Key",
      type:  "string",
      group: "identity",
      description:
        "Business key for this variant, e.g. \"conversion_signup\". " +
        "Use underscores, not spaces or hyphens. Must start with \"conversion_\". " +
        "Unique within this Tenant ID — two tenants can independently use the same key. " +
        "Leave Tenant ID blank to create a shared platform variant.",
      validation: (Rule) =>
        Rule.required().custom(async (value, ctx) => {
          if (!value) return "Variant key is required.";
          if (!/^conversion_[a-z][a-z0-9_]*$/.test(value)) {
            return 'Key must start with "conversion_" and contain only lowercase letters, numbers, and underscores.';
          }

          const document = ctx.document;
          if (!document) return true;

          const client = ctx.getClient({ apiVersion: "2024-01-01" });

          const rawTenantId = (document as Record<string, unknown>)["tenantId"];
          const tenantId: string | null =
            typeof rawTenantId === "string" && rawTenantId.trim() !== ""
              ? rawTenantId.trim()
              : null;

          const baseId = document._id.replace(/^drafts\./, "");

          const conflictId = await client.fetch<string | null>(
            `*[
              _type == $type
              && key == $key
              && (
                ($tenantId == null && !defined(tenantId))
                || ($tenantId != null && tenantId == $tenantId)
              )
              && _id != $id
              && _id != "drafts." + $id
            ][0]._id`,
            {
              type:     document._type,
              key:      value,
              tenantId,
              id:       baseId,
            },
          );

          if (conflictId) {
            return tenantId
              ? `Key "${value}" already exists for tenant "${tenantId}". Choose a different key.`
              : `Shared key "${value}" already exists. Choose a different key or set a Tenant ID.`;
          }
          return true;
        }),
    }),

    // ── Locale ── (identity group) ────────────────────────────────────────────
    defineField({
      name:  "locale",
      title: "Locale",
      type:  "string",
      group: "identity",
      description:
        "Optional locale code (e.g. \"nl\" or \"de\"). " +
        "When set, this variant is returned in preference to the locale-neutral default " +
        "for visitors whose UI language matches. Leave blank for the EN / default version.",
      options: {
        list: [
          { title: "English (default — no locale)",  value: ""   },
          { title: "Nederlands (nl)",                value: "nl" },
          { title: "Deutsch (de)",                   value: "de" },
        ],
        layout: "radio",
      },
    }),

    // ── Active flag ── (identity group) ───────────────────────────────────────
    defineField({
      name:         "isActive",
      title:        "Active",
      type:         "boolean",
      group:        "identity",
      description:  "Only active documents are returned by GROQ queries. Default: true.",
      initialValue: true,
      validation:   (Rule) => Rule.required(),
    }),

    // ── Headline ── (content group) ────────────────────────────────────────────
    defineField({
      name:        "title",
      title:       "Headline",
      type:        "string",
      group:       "content",
      description: "Display headline for the conversion section. Max 120 chars.",
      validation:  (Rule) => Rule.required().max(120),
    }),

    // ── Supporting copy ── (content group) ────────────────────────────────────
    defineField({
      name:        "text",
      title:       "Supporting Copy",
      type:        "text",
      rows:        3,
      group:       "content",
      description: "Paragraph below the headline. 1–2 sentences. Max 300 chars.",
      validation:  (Rule) => Rule.required().max(300),
    }),

    // ── CTAs (flexible array) ── (content group) ──────────────────────────────
    //
    // 1–2 CTA buttons. First renders as primary, second as secondary unless
    // an explicit `variant` is chosen.
    defineField({
      name:  "ctas",
      title: "Call-to-action buttons",
      type:  "array",
      group: "content",
      description:
        "1–2 CTA buttons. First is primary, second is secondary (unless variant is set). " +
        "Leave empty when the block uses a form (formKey) as its primary conversion path.",
      of: [
        {
          type:  "object",
          name:  "ctaItem",
          title: "CTA",
          fields: [
            defineField({
              name:        "label",
              title:       "Label",
              type:        "string",
              description: "Button text. Keep short and action-oriented. Max 60 chars.",
              validation:  (Rule) => Rule.required().max(60),
            }),
            defineField({
              name:  "href",
              title: "Destination",
              type:  "string",
              description:
                "Destination URL. Use a relative path (e.g. /contact) or an absolute URL.",
              validation: (Rule) =>
                Rule.required().custom((href) => {
                  if (!href) return "CTA destination is required.";
                  if (href.trim() === "") return "CTA destination cannot be blank.";
                  return true;
                }),
            }),
            defineField({
              name:  "variant",
              title: "Style variant",
              type:  "string",
              description:
                'Override the automatic style. Leave blank to use position-based default ' +
                '("primary" for first, "secondary" for second).',
              options: {
                list: [
                  { title: "Primary",   value: "primary"   },
                  { title: "Secondary", value: "secondary" },
                  { title: "Outline",   value: "outline"   },
                  { title: "Ghost",     value: "ghost"     },
                ],
                layout: "radio",
              },
            }),
          ],
          preview: {
            select: { label: "label", href: "href", variant: "variant" },
            prepare(selection: Record<string, string | undefined>) {
              const { label, href, variant } = selection;
              return {
                title:    label ?? "(no label)",
                subtitle: `${href ?? "(no href)"}${variant ? ` · ${variant}` : ""}`,
              };
            },
          },
        },
      ],
      validation: (Rule) => Rule.max(2).warning("Maximum 2 CTAs are rendered in the conversion block."),
    }),

    // ── Form key ── (content group) ────────────────────────────────────────────
    defineField({
      name:  "formKey",
      title: "Form Key",
      type:  "string",
      group: "content",
      description:
        "Optional. Key referencing an embedded form definition (e.g. \"signup\", \"demo-request\"). " +
        "When set, the block renderer embeds the matching form in place of or alongside CTAs.",
    }),

    // ── Urgency label ── (content group) ──────────────────────────────────────
    defineField({
      name:  "urgencyLabel",
      title: "Urgency / Social Proof Label",
      type:  "string",
      group: "content",
      description:
        "Optional short label displayed beneath the CTAs or form for social proof or urgency. " +
        "Examples: \"Join 2,000+ teams\", \"No credit card required\", \"Free for 14 days\". " +
        "Max 80 chars.",
      validation: (Rule) => Rule.max(80),
    }),

    // ── AI / Decision metadata ── (ai group) ──────────────────────────────────
    //
    // Complete all fields here to make this variant eligible for AI-driven
    // personalisation.  AI readiness is derived automatically from field
    // completeness — there is no "AI-ready" toggle to set manually.
    defineField({
      name:  "decisionMeta",
      title: "AI / Decision metadata",
      type:  "variantDecisionMeta",
      group: "ai",
      description:
        "Structured metadata the AI uses to decide whether to show this variant to a visitor. " +
        "Complete ALL required fields to enable AI-driven selection — readiness is derived " +
        "automatically from field completeness, no toggle needed. " +
        "Incomplete variants may still be used as a manual or rule-based fallback.",
    }),

    // ── Source tags ── (editorial group) ──────────────────────────────────────
    defineField({
      name:  "sourceTags",
      title: "Source Tags",
      type:  "array",
      group: "editorial",
      of:    [{ type: "string" }],
      description:
        "Informational: traffic sources this variant is optimised for. " +
        "Used for editorial filtering in Studio only — not consumed by the decision engine.",
      options: {
        list: [
          { title: "Google Organic", value: "google-organic" },
          { title: "Google Paid",    value: "google-paid"    },
          { title: "LinkedIn",       value: "linkedin"       },
          { title: "Direct",         value: "direct"         },
          { title: "Referral",       value: "referral"       },
          { title: "Email",          value: "email"          },
        ],
        layout: "tags",
      },
    }),

    // ── Stage tags ── (editorial group) ───────────────────────────────────────
    defineField({
      name:  "stageTags",
      title: "Stage Tags",
      type:  "array",
      group: "editorial",
      of:    [{ type: "string" }],
      description:
        "Informational: funnel stages this variant targets. " +
        "Used for editorial filtering in Studio only.",
      options: {
        list: [
          { title: "Awareness",     value: "awareness"     },
          { title: "Consideration", value: "consideration" },
          { title: "Decision",      value: "decision"      },
          { title: "Retention",     value: "retention"     },
        ],
        layout: "tags",
      },
    }),
  ],

  // ── Studio preview ──────────────────────────────────────────────────────────
  //
  // Shows: headline · key [tenantId / platform] · AI ready / not ready · inactive
  //
  // AI readiness is derived from the 8 required decisionMeta field values.
  // No stored aiReady boolean is read — completeness is computed in prepare().
  preview: {
    select: {
      title:    "title",
      key:      "key",
      tenantId: "tenantId",
      active:   "isActive",
      dLabel:   "decisionMeta.decisionLabel",
      dSummary: "decisionMeta.decisionSummary",
      dAudience:"decisionMeta.intendedAudience",
      dIntent:  "decisionMeta.intentLevel",
      dFunnel:  "decisionMeta.funnelStages",
      dSources: "decisionMeta.bestForSources",
      dTone:    "decisionMeta.tone",
      dGoal:    "decisionMeta.primaryGoal",
    },
    prepare({ title, key, tenantId, active,
              dLabel, dSummary, dAudience, dIntent, dFunnel, dSources, dTone, dGoal }) {
      const aiReady = Boolean(
        typeof dLabel    === "string" && dLabel.trim() &&
        typeof dSummary  === "string" && dSummary.trim() &&
        typeof dAudience === "string" && dAudience.trim() &&
        dIntent &&
        Array.isArray(dFunnel)  && (dFunnel  as unknown[]).length > 0 &&
        Array.isArray(dSources) && (dSources as unknown[]).length > 0 &&
        dTone &&
        typeof dGoal === "string" && dGoal.trim()
      );
      const tenantLabel = tenantId ? ` [${tenantId}]` : " [platform]";
      const aiLabel     = aiReady ? " · ✓ AI-ready" : " · ✗ AI not ready";
      const activeLabel = active === false ? " · ⚠ inactive" : "";
      return {
        title:    title ?? "(No headline)",
        subtitle: `${key ?? "(no key)"}${tenantLabel}${aiLabel}${activeLabel}`,
      };
    },
  },
});
