/**
 * Sanity Schema — featureVariant
 *
 * Defines the content structure for an adaptive feature highlights / benefit
 * grid block variant.  One document per variant key.  Each document contains a
 * section heading, an optional subheading, and an array of feature items
 * (icon + title + body).
 *
 * ─── Variant keys ─────────────────────────────────────────────────────────────
 *
 *   feature_grid_primary  Icon + headline + body grid (default layout).
 *   feature_highlights    Larger, alternating left/right feature rows.
 *   feature_comparison    Side-by-side comparison table / matrix.
 *
 * ─── Tenant-scoped identity ───────────────────────────────────────────────────
 *
 *   A variant is identified by the composite (tenantId, key) pair:
 *
 *     • The same key (e.g. "feature_grid_primary") is reusable across tenants.
 *       Each tenant maintains its own copy with tenant-specific copy/items.
 *     • Uniqueness is enforced per-tenant: two documents may share a key only
 *       if they belong to different tenants.
 *     • tenantId absent → shared/platform variant, available to ALL tenants
 *       as a fallback when no tenant-specific document exists.
 *
 * ─── Resolution order (GROQ) ──────────────────────────────────────────────────
 *
 *   1. Tenant-specific document  (tenantId == $tenantId)  — highest priority
 *   2. Shared/platform document  (!defined(tenantId))     — fallback
 *
 *   Full query is generated by buildVariantQuery() in cms/queries/sanity/query-builder.ts.
 *
 * ─── Studio tabs ─────────────────────────────────────────────────────────────
 *
 *   Content             — heading, subheading, feature items
 *   AI / Decision       — decisionMeta (audience, intent, goals, readiness gate)
 *   Identity & settings — tenant ID, variant key, layout, active flag
 *   Editorial tags      — sourceTags, stageTags
 *
 * ─── Field reference ──────────────────────────────────────────────────────────
 *
 *   tenantId      string   Optional. Tenant owner slug, e.g. "workengine".
 *                          Absent = shared platform variant served to all tenants.
 *   key           string   Required. Business key, e.g. "feature_grid_primary".
 *                          Unique within the same tenantId scope (not globally).
 *   layoutVariant string   Optional. Layout variant for the block renderer.
 *   title         string   Required. Section heading. ≤120 chars.
 *   subtitle      string   Optional. Subheading beneath section heading. ≤200 chars.
 *   items         array    Required. Feature items. 3–6 recommended.
 *   decisionMeta  object   Optional. AI / decision metadata (aiReady gate).
 *   sourceTags    array    Optional. Traffic-source editorial taxonomy.
 *   stageTags     array    Optional. Funnel-stage editorial taxonomy.
 *   isActive      boolean  Required. Default: true.
 *
 * ─── featureItem fields ───────────────────────────────────────────────────────
 *
 *   title   string  Required. Feature name / benefit label. ≤80 chars.
 *   body    text    Required. 1–2 sentences of supporting copy. ≤300 chars.
 *   icon    string  Optional. Icon name string from the design system icon set.
 */

import { defineArrayMember, defineField, defineType } from "sanity";

export default defineType({
  name:  "featureVariant",
  title: "Feature Variant",
  type:  "document",

  // ── Field groups (Studio tabs) ────────────────────────────────────────────
  groups: [
    { name: "content",   title: "Content",              default: true },
    { name: "ai",        title: "AI / Decision"                       },
    { name: "identity",  title: "Identity & settings"                 },
    { name: "editorial", title: "Editorial tags"                      },
  ],

  fields: [

    // ── Layout variant ── (identity group) ────────────────────────────────────
    defineField({
      name:  "layoutVariant",
      title: "Layout Variant",
      type:  "string",
      group: "identity",
      description:
        "Controls the structural layout of the feature block. " +
        "The content (heading, items) is the same regardless of layout.",
      options: {
        list: [
          { title: "Grid — icon + headline + body cards (default)", value: "feature_grid"        },
          { title: "Highlights — alternating left/right rows",       value: "feature_highlights" },
          { title: "Comparison — side-by-side comparison table",     value: "feature_comparison" },
        ],
        layout: "radio",
      },
      initialValue: "feature_grid",
    }),

    // ── Tenant ── (identity group) ─────────────────────────────────────────────
    defineField({
      name:  "tenantId",
      title: "Tenant ID",
      type:  "string",
      group: "identity",
      description:
        "Tenant that owns this variant, e.g. \"workengine\". " +
        "Leave blank for shared platform variants available to all tenants.",
      validation: (Rule) =>
        Rule.custom((value) => {
          if (!value) return true;
          if (!/^[a-z][a-z0-9-]*[a-z0-9]$|^[a-z]$/.test(value)) {
            return "Tenant ID must be lowercase letters, numbers, and hyphens only.";
          }
          return true;
        }),
    }),

    // ── Variant key ── (identity group) ───────────────────────────────────────
    defineField({
      name:  "key",
      title: "Variant Key",
      type:  "string",
      group: "identity",
      description:
        "Business key for this variant, e.g. \"feature_grid_primary\". " +
        "Use underscores, not spaces or hyphens. Must start with \"feature_\". " +
        "Unique within this Tenant ID — two tenants can independently use the same key. " +
        "Leave Tenant ID blank to create a shared platform variant.",
      validation: (Rule) =>
        Rule.required().custom(async (value, ctx) => {
          if (!value) return "Variant key is required.";
          if (!/^feature_[a-z][a-z0-9_]*$/.test(value)) {
            return 'Key must start with "feature_" and contain only lowercase letters, numbers, and underscores.';
          }

          const document = ctx.document;
          if (!document) return true;

          const client = ctx.getClient({ apiVersion: "2024-01-01" });

          const rawTenantId = (document as Record<string, unknown>)["tenantId"];
          const tenantId: string | null =
            typeof rawTenantId === "string" && rawTenantId.trim() !== ""
              ? rawTenantId.trim()
              : null;

          const baseId = document._id.replace(/^drafts\./, "");

          const conflictId = await client.fetch<string | null>(
            `*[
              _type == $type
              && key == $key
              && (
                ($tenantId == null && !defined(tenantId))
                || ($tenantId != null && tenantId == $tenantId)
              )
              && _id != $id
              && _id != "drafts." + $id
            ][0]._id`,
            {
              type:     document._type,
              key:      value,
              tenantId,
              id:       baseId,
            },
          );

          if (conflictId) {
            return tenantId
              ? `Key "${value}" already exists for tenant "${tenantId}". Choose a different key.`
              : `Shared key "${value}" already exists. Choose a different key or set a Tenant ID.`;
          }
          return true;
        }),
    }),

    // ── Locale ── (identity group) ────────────────────────────────────────────
    defineField({
      name:  "locale",
      title: "Locale",
      type:  "string",
      group: "identity",
      description:
        "Optional locale code (e.g. \"nl\" or \"de\"). " +
        "When set, this variant is returned in preference to the locale-neutral default " +
        "for visitors whose UI language matches. Leave blank for the EN / default version.",
      options: {
        list: [
          { title: "English (default — no locale)",  value: ""   },
          { title: "Nederlands (nl)",                value: "nl" },
          { title: "Deutsch (de)",                   value: "de" },
        ],
        layout: "radio",
      },
    }),

    // ── Active flag ── (identity group) ───────────────────────────────────────
    defineField({
      name:         "isActive",
      title:        "Active",
      type:         "boolean",
      group:        "identity",
      description:  "Only active documents are returned by GROQ queries. Default: true.",
      initialValue: true,
      validation:   (Rule) => Rule.required(),
    }),

    // ── Section heading ── (content group) ────────────────────────────────────
    defineField({
      name:        "title",
      title:       "Section Heading",
      type:        "string",
      group:       "content",
      description: "Main heading displayed above the feature items. Max 120 chars.",
      validation:  (Rule) => Rule.required().max(120),
    }),

    // ── Subheading ── (content group) ─────────────────────────────────────────
    defineField({
      name:        "subtitle",
      title:       "Subheading",
      type:        "string",
      group:       "content",
      description: "Optional subheading beneath the section heading. Max 200 chars.",
      validation:  (Rule) => Rule.max(200),
    }),

    // ── Feature items ── (content group) ──────────────────────────────────────
    defineField({
      name:        "items",
      title:       "Feature Items",
      type:        "array",
      group:       "content",
      description: "3–6 items recommended. Each item shows an optional icon, a bold title, and 1–2 lines of body copy.",
      of: [
        defineArrayMember({
          type:  "object",
          name:  "featureItem",
          title: "Feature Item",
          fields: [
            defineField({
              name:        "title",
              title:       "Feature Name",
              type:        "string",
              description: "Short feature name or benefit label. Max 80 chars.",
              validation:  (Rule) => Rule.required().max(80),
            }),
            defineField({
              name:        "body",
              title:       "Body Copy",
              type:        "text",
              rows:        2,
              description: "1–2 sentences expanding on the feature. Max 300 chars.",
              validation:  (Rule) => Rule.required().max(300),
            }),
            defineField({
              name:        "icon",
              title:       "Icon",
              type:        "string",
              description: "Icon name from the design system icon set (e.g. \"zap\", \"shield\", \"globe\"). Optional.",
            }),
          ],
          preview: {
            select: { title: "title", subtitle: "body" },
          },
        }),
      ],
      validation: (Rule) =>
        Rule.required()
          .min(1)
          .max(9)
          .warning("3–6 feature items is the recommended layout. More than 6 may overflow on smaller screens."),
    }),

    // ── AI / Decision metadata ── (ai group) ──────────────────────────────────
    //
    // Complete all fields here to make this variant eligible for AI-driven
    // personalisation.  AI readiness is derived automatically from field
    // completeness — there is no "AI-ready" toggle to set manually.
    defineField({
      name:  "decisionMeta",
      title: "AI / Decision metadata",
      type:  "variantDecisionMeta",
      group: "ai",
      description:
        "Structured metadata the AI uses to decide whether to show this variant to a visitor. " +
        "Complete ALL required fields to enable AI-driven selection — readiness is derived " +
        "automatically from field completeness, no toggle needed. " +
        "Incomplete variants may still be used as a manual or rule-based fallback.",
    }),

    // ── Source tags ── (editorial group) ──────────────────────────────────────
    defineField({
      name:  "sourceTags",
      title: "Source Tags",
      type:  "array",
      group: "editorial",
      of:    [{ type: "string" }],
      description:
        "Informational: traffic sources this variant is optimised for. " +
        "Used for editorial filtering in Studio only — not consumed by the decision engine.",
      options: {
        list: [
          { title: "Google Organic", value: "google-organic" },
          { title: "Google Paid",    value: "google-paid"    },
          { title: "LinkedIn",       value: "linkedin"       },
          { title: "Direct",         value: "direct"         },
          { title: "Referral",       value: "referral"       },
          { title: "Email",          value: "email"          },
        ],
        layout: "tags",
      },
    }),

    // ── Stage tags ── (editorial group) ───────────────────────────────────────
    defineField({
      name:  "stageTags",
      title: "Stage Tags",
      type:  "array",
      group: "editorial",
      of:    [{ type: "string" }],
      description:
        "Informational: funnel stages this variant targets. " +
        "Used for editorial filtering in Studio only.",
      options: {
        list: [
          { title: "Awareness",     value: "awareness"     },
          { title: "Consideration", value: "consideration" },
          { title: "Decision",      value: "decision"      },
          { title: "Retention",     value: "retention"     },
        ],
        layout: "tags",
      },
    }),
  ],

  // ── Studio preview ──────────────────────────────────────────────────────────
  //
  // Shows: heading · key [tenantId / platform] · AI ready / not ready · inactive
  //
  // AI readiness is derived from the 8 required decisionMeta field values.
  // No stored aiReady boolean is read — completeness is computed in prepare().
  preview: {
    select: {
      title:      "title",
      key:        "key",
      tenantId:   "tenantId",
      active:     "isActive",
      itemCount:  "items",
      dLabel:     "decisionMeta.decisionLabel",
      dSummary:   "decisionMeta.decisionSummary",
      dAudience:  "decisionMeta.intendedAudience",
      dIntent:    "decisionMeta.intentLevel",
      dFunnel:    "decisionMeta.funnelStages",
      dSources:   "decisionMeta.bestForSources",
      dTone:      "decisionMeta.tone",
      dGoal:      "decisionMeta.primaryGoal",
    },
    prepare({ title, key, tenantId, active, itemCount,
              dLabel, dSummary, dAudience, dIntent, dFunnel, dSources, dTone, dGoal }) {
      const aiReady = Boolean(
        typeof dLabel    === "string" && dLabel.trim() &&
        typeof dSummary  === "string" && dSummary.trim() &&
        typeof dAudience === "string" && dAudience.trim() &&
        dIntent &&
        Array.isArray(dFunnel)  && (dFunnel  as unknown[]).length > 0 &&
        Array.isArray(dSources) && (dSources as unknown[]).length > 0 &&
        dTone &&
        typeof dGoal === "string" && dGoal.trim()
      );
      const count       = Array.isArray(itemCount) ? itemCount.length : 0;
      const tenantLabel = tenantId ? ` [${tenantId}]` : " [platform]";
      const aiLabel     = aiReady ? " · ✓ AI-ready" : " · ✗ AI not ready";
      const activeLabel = active === false ? " · ⚠ inactive" : "";
      return {
        title:    title ?? "(No heading)",
        subtitle: `${key ?? "(no key)"}${tenantLabel} · ${count} item${count !== 1 ? "s" : ""}${aiLabel}${activeLabel}`,
      };
    },
  },
});
